### ISSUE TITLE
Not exit bug when editing cross reference

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#1000]
Please watch:
https://drive.google.com/file/d/1BE3r7uV4KMLuYD58BOCt4Ea9J46-5-Z8/view?usp=sharing

if its not streaming please download the file and watch.

**Comment by knirirr** [comment]
Steps to reproduce:

1. Edit a record, go to "additional information" and attempt to add a cross reference.
2. Leave the "portal" field blank.
3. Save.
4. An error message will be displayed:

```json
{ "metadata": [ "The property '#/cross_references/0/portal' value nil did not match one of the following values: BioPortal, OLS, OBO Foundry, AgroPortal, Other in schema https://api.fairsharing.org/model/database_repository_schema.json#", "The property '#/cross_references/0/portal' of type null did not match the following type: string in schema https://api.fairsharing.org/model/database_repository_schema.json#" ] }
```

This might be addressed by making the portal field compulsory, but this could require analysing the server's response to determine which fields are compulsory.

**Comment by knirirr** [comment]
This is part of a larger issue; the `required` fields from the schema definitions are not being used to set the `isRequired()` rule.
Additionally, `isDisabled()` in `EditAdditionalInfo.vue` doesn't use the `isRequired()` rule when added; it seems to be based simply on number of fields completed.
