### ISSUE TITLE
incorrect numbering of items in Educational page

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#1009]

**Comment by hoseinmirian** [comment]
I spotted inconsistencies in numbering the items in educational page. @allysonlister I appreciate letting me know if the number and order of them is correct so I can number them from 8-1 8-2 etc. thanks. 
https://dev--fairsharing.netlify.app/#/educational

![image](https://user-images.githubusercontent.com/25683981/120322393-4586fc00-c2dc-11eb-8045-1d4dda1d5676.png)

**Comment by allysonlister** [comment]
Thank you very much for spotting this, @hoseinmirian - please update those numbers 8-1, 8-2 etc as you suggest.

Thanks!
