### ISSUE TITLE
Discrepancies new/old site when displaying policies relationships

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/fairsharing.github.io#1021]
When displaying the relationships of records that are policies, there are two discrepancies that happen when comparing old and new system:
1) In "Related Policies" seems to appear both the relationship "A related_to B" and "B related_to A" when displaying record A in the old system but not in the new. For instance check the record https://dev--fairsharing.netlify.app/#/3446 that it is record https://fairsharing.org/policy/2034 in the old system. In the new DB there is only one relationship created "3446 related_to B" (recordAssociations), but for the same record in the field (reverseRecordAssociation, there are 16 relationships "X related_to 3446". In the old system, when they are displayed in the record page (https://fairsharing.org/policy/2034 ), there are shown 17 records in the section "Related Policies" (1 that is "3446 related_to X"+16 that are "X related_to 3446"), meanwhile in the new system (https://dev--fairsharing.netlify.app/#/3446 ) only one is displayed in section "other related records" ("3446 related_to B"). Questions, 1.1) do we have to shown both (recordAssociation and reverseRecordAssociation) when displaying the records in section "other related records"?, 1.2) do we have to create in the DB the relationship "A related_to B" when there is "B related_to A"? 

2) In the old DB, there are the relationship "Standards and Databases mentioned in this policy " that are not shown in the new system. For the example https://dev--fairsharing.netlify.app/#/3446 (old system https://fairsharing.org/policy/2034), there are 30 records in the old system and in the DB of the new system they are imported "3346 recommends X" for 30 different records. They are not displayed in the new system, is it fine?

**Comment by knirirr** [comment]
1.1: The "other related records" tab seems only to be showing outgoing relationships, whereas there are significant numbers of incoming relationships. It will need to be modified to display these. 
1.2: A second relationship should not be created. If A related_to B exists and you try to create B related_to A then the server will fail to validate the second relation. 
2: These will be outgoing "recommends" relationships and they have been excluded from the related records display.

1.1 and 2 could be addressed by:
- Changing the other related records tab to allow incoming relations. 
- Changing all the related records tabs to allow outgoing "recommends" relationships.

**Comment by allysonlister** [comment]
@delphinedauga  and I agree that "Changing the other related records tab to allow incoming relations" is the right solution to 1.1.

The display of the outgoing recommends relationships is something we should talk about tomorrow (see zulip request). 

Thanks!

**Comment by knirirr** [comment]
This has been dealt with by https://github.com/FAIRsharing/fairsharing.github.io/pull/1045
