### ISSUE TITLE
Improve Record loading

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/fairsharing.github.io#104]
When viewing a single record, only reload the data and the history if the ID/DOI changed.
Keep the data in the store when leaving the page; check the ID/DOI when re-renteering the page.

**Comment by Drosophilic** [comment]
By 'store', do you mean a local store using cookies? I'm wondering about shared computers and account details (e.g. someone logs in to look at something from their account then someone else without an account logs in and sees extra data). It's a naive question, but I though to raise it just in case.

**Comment by terazus** [comment]
Local storage and cookies are not the same thing but they globaly serve the same purpose: store data on the client side.
By store, here, i mean neither: it's the Vuex Store. What I mean here is that we should prevent reloading the current record if it's already in the store (so by either ID or DOI).

**Comment by Drosophilic** [comment]
OK, got it. Thanks.
