### ISSUE TITLE
"Edit Profile" burger behaviour

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1068]
**Describe the bug**
When a super curator visits another user's profile page, they should be able to edit that page using "Edit Profile" from the burger in the top right. Currently, when Edit Profile is chosen, it takes the super curator to their own profile to edit, which is confusing.

**To Reproduce**
1. Log into FAIRsharing as a super curator or equivalent role (developer?)
2. Visit https://dev--fairsharing.netlify.app/?#/users/5492
3. Click on burger in top right
4. Choose "Edit Profile"
5. See that the profile that opens to edit is your own, and not the user's.

**Expected behavior**
Depending on complexity of the fix, I would be happy with either of the following behaviours:
1. (preferred). Super curators have access to the "Edit Profile" option for the user (all other options unavailable)
2. (good temporary fix, with 1 being developed as there is time). Any user other than the owner of that profile would see only greyed-out options for it.

In both cases, if anyone other than a supercurator attempts to use any of the options in the burger for another user, they should be unable to (e.g. those options are greyed out).

**Screenshots**
![editprofile](https://user-images.githubusercontent.com/143586/122246419-719aa380-cebe-11eb-8b30-d1cfc8b9664f.gif)

**Operating system and browser version**
Ubuntu using Firefox 89.0 (64-bit)

**Additional context**

**Comment by knirirr** [comment]
I'd say that this is not actually a bug - that menu does what it's supposed to do. But, I see how the result might look unexpected. 
As it happens there's an entire controller available on the server for super_curators to edit users, but it has yet to be used in any way by the client. My plan will therefore be to use option (2) and create a separate ticket for an "administer user" option in that menu for super_curators only. This would also give access to modifications not available through the normal editing shown above (e.g. the deactivation of users).
