### ISSUE TITLE
Community Page Updates

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1085]
Good afternoon!

Here are the updates for the new community pages please (old page at https://fairsharing.org/communities). Please make the new page match the old page, except for the changes below:

1. Please change the tagline (the old text begins with "FAIRsharing is a community-driven resource with a growing number of users[...]") to the following: ~~"Making standards, databases and policies count"~~ "FAIRsharing is a community-driven resource with a growing number of users and collaborators, all working to enable the FAIR Principles and to make standards, databases and policies FAIR."
2. Rearrange the three sections to be in this order: Activities, Adopters, Governance.
3. Within Governance, "Meet the Team" comes first, and then "Advisory Board".
4. Move Pete from "Meet the Team" to the Advisory Board section, under "Executive Advisors". His text would be "Peter McQuilton, GSK".
5. Please modify the text for the "Meet the Team section as follows: 
> Based at the University of Oxford, UK, FAIRsharing has become a sustainable service, operating since 2011 with and for the researchers and all other stakeholders involved in the data life cycle.
> The operational team is based in the [Data Readiness Group](https://datareadiness.eng.ox.ac.uk/#people), the DOI generation is provided by the [Bodleian Library](https://www.bodleian.ox.ac.uk/), at the University of Oxford.
> FAIRsharing also operates as a joint [Force11/RDA working group](https://www.rd-alliance.org/group/fairsharing-registry-connecting-data-policies-standards-databases.html), reaching out to the broader community. 
6. Below this text, the names and photos of the following people should appear (other members of the team are on the Data Readiness page) in the same style as already exists.
- Susanna-Assunta Sansone Principal Investigator and Founder
- Philippe Rocca-Serra Co-Founder
- Milo Thurston Technical Coordinator
- Allyson Lister Content and Community Coordinator

**Comment by allysonlister** [comment]
An additional note about internal links in this page: it is really important that we maintain the URLs used for internal links as these are referenced in many documents we have made. For example:
- each of Activities, Adopters, and Governance have their own link, e.g. https://fairsharing.org/communities#adopters
- Each item in the Activities table has its own internal link we can reference, e.g. https://fairsharing.org/communities#activity_3 (note the singular "activity")

**Comment by hoseinmirian** [comment]
@allysonlister please also determine the title and subtitle in jumbetron. the figure below attached:
![image](https://user-images.githubusercontent.com/25683981/122941433-4ce67600-d36d-11eb-9f80-708195378adf.png)

**Comment by allysonlister** [comment]
Thanks!

The "tagline" mentioned in number 1 in my original comment has the string that can be used for what you've called the subtitle. We didn't have a title before, so I'll need to check first, and I'll get back to you.

**Comment by allysonlister** [comment]
Thanks Hossein!

As a result of your request, we've modified what we'd like for the title and subtitle please. I have listed them here and amended the subtitle/tagline in the original comment to ensure they're visible.

Title: "Community: adopters, activities and governance"
Subtitle: "FAIRsharing is a community-driven resource with a growing number of users and collaborators, all working to enable the FAIR Principles and to make standards, databases and policies FAIR."

(We now have a different idea for "Making standards, databases and policies count", but that will come as a separate ticket once we've properly defined it)

**Comment by allysonlister** [comment]
Thanks @hoseinmirian - Please note the outstanding changes originally provided in the list above please:

1. The title/subtitle you requested are a replacement for the original heading, therefore the following phrase that appears underneath the title/subtitle should be removed: "Making standards, databases and policies count, collaborators and activities, all working to enable the FAIR Principles and to make Standards, Knowledgebases, Repositories and Data Policies FAIR. "

Also items 2-6 from the original comment are yet to be implemented - perhaps you haven't started on that yet?

In addition to this, now that I've seen the styling of the new page, please can we also:

1. Increase the size of the text in columns 2 and 3 of the Adopters page so that it's consistent with the rest of the text outside the table.
2. Are the internal links for the Activities table active as described in the comment above and matching the URLs from the legacy system? I can't see the URLs when I hover over them...
3. "advisoryBoard" has odd Camel Casing, and the formatting (in a single column rather than the two columns of the legacy system) should match that of the legacy system.


Thank you very much! Let me know when this is updated and I can take a look.

**Comment by hoseinmirian** [comment]
>     2\. Activities table

thanks for the comments. 
1- ok I will do it
2- I have copied pasted what we had in the legacy website! so they should be there all. Would you please make an example or refer to a link?
3- I thought its more better looking but if you favor the legacy one I would change that. 


the rest points you made from the past and now are under development. Thanks

**Comment by allysonlister** [comment]
Hi all,

Thanks for pointing out the new version of the community page @hoseinmirian, and thanks for doing all the updates :-)

Here are my thoughts, which are just a few tweaks hopefully.

1. The URL should match the legacy site so that people with old links won't get broken. That means it should be https://fairsharing.org/communities instead of /community
2. Some hrefs in the document are absolute, and therefore point to what is currently the legacy site (e.g. "Create Recommendations by registering their data policy" - the "Recommendations" href is https://fairsharing.org/recommendations/), and others are relative, so they point to the rebuild (e.g. "Create a Collection by pulling together a list" - the "Collection" href is https://deploy-preview-1102--fairsharing.netlify.app/#/collections). These should be consistent, but I'm not sure which way you're coding it - perhaps Milo knows?
3. The internal links for the activity table don't seem to be working. The example I gave near the top of the ticket is https://fairsharing.org/communities#activity_3 - so https://deploy-preview-1102--fairsharing.netlify.app/#/community#activity_3 should also work, but it doesn't. There are 14 activities in that table, and each should have an internal link like this one.

Once these changes are complete, I'll check things with Susanna. Thanks again!

**Comment by hoseinmirian** [comment]
1- it will be done in the next commits.
2- for the second request about consistency in href, I should say they are consistent and later in a production version of the app, the link refers to the right place. For. eg, now link refers to localhost:8080/communities and later by hosting the site in the internet the URL will be like www.fairsharing.org/communities
in regard to the second point about collections, the way its been implemented at the very first day is that it redirects /collections to http://localhost:8080/#/search?fairsharingRegistry=Collection which is done a long time ago by Dom. I suspect we might need a new route for that if its too necessary but I am not sure to look at it more accurately. I suggest also run some thoughts with Dom in this regard as well. In regard to /recommendations, we do not have any route for that anymore and its just part of the filter panel so we can apply if its recommended or not. the route that I will redirect user in the new app would be 
http://localhost:8080/#/search?isRecommended=true

3- it will be done in the next commits.
@knirirr please check if something is needed to be considered. thanks all.

**Comment by hoseinmirian** [comment]
new feedback except routing in regard to /collections and /recommendations which are not within the discussion context, applied and the netlify build is done. 
https://app.netlify.com/sites/fairsharing/deploys/60ddcf217bb3790007fbe496
tnx

**Comment by allysonlister** [comment]
Thanks. In fact you have gone beyond what I had asked in point 2, but your suggestions for the routing for /collections and /recommendations are very good, thanks for following that up!

How do I look at the new build? Clicking on the link you provided just takes me to what look like build stats? Sorry, I don't know much about netlify!

**Comment by hoseinmirian** [comment]
Thanks! sorry the correct link is https://deploy-preview-1102--fairsharing.netlify.app/#/communities
