### ISSUE TITLE
"Citing publication" toggle does not work when adding a new DOI

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1096]
**Describe the bug**
When adding a new publication DOI to a record (try this one, but it will only work once! “10.3390/v12020217”), the toggle to allow it to be marked as the citing publication doesn’t get saved.

**To Reproduce**
1. Go to any record, e.g. https://dev--fairsharing.netlify.app/?#/FAIRsharing.d5vqn0
2. Actions -> Edit Record
3. Visit the "Publications" tab
4. Add a DOI that doesn't exist in FAIRsharing yet (I like to visit PubMed and choose a random keyword such as "rainbow", e.g. https://pubmed.ncbi.nlm.nih.gov/?term=rainbow).
5. When no publication is found, choose "import from DOI"
6. Set toggle to "on" for "Do you want to cite this record using this publication?"
7. Click "Edit or Add a New Publication"
8. Notice that the citation is not added as the citing publication, but remains grey.

**Expected behavior**
The citation added should have its toggle to "on", should display as green and should be set as the citing publication.

**Operating system and browser version**
Ubuntu, Firefox 89.0.1 (64-bit)

**Comment by knirirr** [comment]
Duplicates https://github.com/FAIRsharing/fairsharing.github.io/issues/1091 which I'll close in favour of this.

**Comment by knirirr** [comment]
I've dealt with this by removing the offending toggle; it's not needed any way as there's another functioning one available.
