### ISSUE TITLE
Additional Community Page Updates

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1124]
Please see some additional updates for the community page:

- [x] Table order should go back to what it was: Adopters, Activities, Governance (sorry!)
- [x] The three "title blocks" for Adopters, Activities, Governance should go at the very top of the page underneath the title/subtitle heading
- [x] The title/subtitle heading should be put back - I'm not sure why it was deleted? (See https://github.com/FAIRsharing/fairsharing.github.io/issues/1085#issuecomment-866634316)
- [x] Remove the "how to cite us" sentence.
- [x] Using the same style of grid (3-column, 5-column or what works best) as used for the official reports, we simplify the adopters table to just show logos only (no hyperlinks)
 - eLife
 - Elsevier
 - EMBO Press
 - F1000
 - GigaScience
 - PLoS
 - Taylor and Francis
 - Wellcome
 - Wiley
 - Springer Nature
 - PeerJ - not in the existing community page
 - Hindawi - not in the existing community page
 - Cambridge University Press - not in the existing community page
 - Oxford University Press - not in the existing community page
 - The Royal Society Publishing - not in the existing community page
- [x] In the "Adopters" section, there is this text which is no longer quite correct with respect to recommendations: "Create Recommendations by registering their data policy, and then link it to standards and/or databases recommended in the policy; and/or ". I suggest we change the text to "Recommend resources by registering their data policy..." etc  The link should be https://deploy-preview-1102--fairsharing.netlify.app/#/search?isRecommended=true&page=1
- [x] Remove the sentence "Learn more about the FAIRsharing community, and please do not hesitate to contact us if you are interested in working with us."
- [x] Replace "We cannot list all of our adopters, but we've listed here those publishers that use FAIRsharing to define and refine their data policy." with "We cannot list all of our adopters, but we've listed here some publishers that use FAIRsharing to define and refine their data policy."
- [x] Replace "Global Organizations" title with "Other Organisations". Then replace the table with a 4-column, 1-row table with the following hyperlinked logos 
  - RDA
  - GO FAIR
  - FORCE11
  - ELIXIR https://elixir-europe.org/
- [x] Modify the "Meet the Team" section. 4 people per row perhaps? Order:
First row
 a. Allyson - Content and Community Lead
 b. Milo - Technical Lead
 c. Susanna - Principal Investigator and Founder
 d. Philippe - Co-Founder
- [x] Second row (Titles tbc)
 e. Ramon
 f. Hossein
 g. Dom 
 h. Delphine 
- [x] Remove the link on the team member's names, and have the little house logo for everyone link to the same URL: https://datareadiness.eng.ox.ac.uk/#people 
- [x] Change URL in "Data Readiness Group" within the sentence "The operational team is based in the Data Readiness Group..."  to link to https://datareadiness.eng.ox.ac.uk
- [x] Remove this sentence: "FAIRsharing also operates as a joint Force11/RDA working group, reaching out to the broader community. "
- [x] Make the pictures of us slightly smaller 
- [x] All logos on the page, and also our photos, should be in black and white.
- [x] The stakeholder Advisors list should be replaced with the one at the google doc I sent to @knirirr offline.

**Comment by knirirr** [comment]
I think this is now as complete as it can be (until the next round).

**Comment by allysonlister** [comment]
Hi all,

I noticed that not all of the items were addressed, and we have a couple additional small changes, so I'm reopening to provide clarity on the unfinished items, and a couple of other points. Thank you!

- [x] **Job title update** (originally called "Second row" in the initial comment)
Please can you update the following people's job titles as indicated.
Ramon - Data Enrichment and Quality Manager
Hossein - Web Developer
Dom - Research Software Engineer
Delphine - Curation Manager
- [x] This item has not yet been completed: Remove the link on the team member's names (currently the link appears to be gone, but the mouse still changes from pointer to selector as if there were a link), and have the little house logo for everyone point to the same URL: https://datareadiness.eng.ox.ac.uk/#people
- [x] This item has not yet been completed:  Using the same style of grid (3-column, 5-column or what works best) as used for the "Other Organisations" (note the slight change here from my initial comment), we simplify the adopters table to just show logos only (no hyperlinks) for the adopters listed in the original comment above.
- [x] New item: Remove the title: "Community: adopters, activities and governance", and move the text from the subtitle into the "title" position.
- [x] **The Executive and Stakeholder Advisor information** We didn't provide information about the Executive Advisors last time, and also there were some changes to the stakeholder advisors list that weren't implemented. Also, we have a final few changes to the stakeholder's list. Therefore, apologies, but  please update the community page with the information we've provided at the google doc I sent to @knirirr offline.

Thanks!

**Comment by hoseinmirian** [comment]
@allysonlister 
in regard to have 4 items for each row about team members:
the items are sat next to each other using a flex technology which wraps the items and as soon the screen size shrink or grow it reacts accordingly. Due to the current left to right, full-width layout design we have, the container holding all items will order them based on the screen size. for e.g, the screenshot below shows that this is the desired result you want in a smaller screen but getting the same result in a larger screen although is possible with hacky ways but it also breaks the layout look due to everything is full-width and I have to distribute 4 items in a wide screen which ends up having big gaps between images and look them very strange. Besides, consider joining members and leaving members which imbalance the number of rows and items.  Overall, the answer is No unfortunately and I would recommend keeping the current structure due to its more reliable and flexible with various data number. 

![image](https://user-images.githubusercontent.com/25683981/126773247-bff3dc79-6e32-445c-9a72-7ea513df075a.png)

**Comment by hoseinmirian** [comment]
@allysonlister 
in regard to simplifying the adoptors table, do you want only the first column to be shown? how is the screenshot below, is it desired?

![image](https://user-images.githubusercontent.com/25683981/126775623-d0ed4283-f9a3-4656-b382-b2dd38fe721a.png)

**Comment by hoseinmirian** [comment]
@allysonlister 

in regard to swapping title and subtitle please confirm if it is correctly swapped as screen shot shows:
![image](https://user-images.githubusercontent.com/25683981/126776959-ba4cf91a-2959-495f-87ff-8ef5ca999996.png)

**Comment by hoseinmirian** [comment]
@allysonlister 

for the last item you sent to Milo as offline, Milo is in holiday so please share it with me or simply here list what you want which is more preferable

**Comment by hoseinmirian** [comment]
please check the latest changes in this branch:
https://deploy-preview-1174--fairsharing.netlify.app/#/communities

**Comment by allysonlister** [comment]
> @allysonlister
> in regard to have 4 items for each row about team members:
> [...]Overall, the answer is No unfortunately and I would recommend keeping the current structure due to its more reliable and flexible with various data number.
> 

Thank you @hoseinmirian I understand - please keep the current structure for the reasons you state!

**Comment by allysonlister** [comment]
> @allysonlister
> in regard to simplifying the adoptors table, do you want only the first column to be shown? how is the screenshot below, is it desired?
> 
Yes that is exactly correct. It's up to you if you think it is best with or without the borders around the cells. Thanks!

**Comment by allysonlister** [comment]
> @allysonlister
> 
> in regard to swapping title and subtitle please confirm if it is correctly swapped as screen shot shows:

Thanks! It is correct except that please can you completely remove the line that reads "Community: adopters, activities and governance" 

:)

**Comment by allysonlister** [comment]
> @allysonlister
> 
> for the last item you sent to Milo as offline, Milo is in holiday so please share it with me or simply here list what you want which is more preferable

As it's a google doc and this is a public forum, I'll send you the link off-ticket now. thanks!

**Comment by hoseinmirian** [comment]
@allysonlister could you please share the link here? tnx

**Comment by allysonlister** [comment]
I would prefer to not share it here, as it's public. I have shared it on Zulip :-)
