### ISSUE TITLE
Action Menu Items: Availability to Logged in / Logged Out Users 

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1132]
**Describe the bug**
The Actions menu items are enabled/disabled incorrectly when users are logged in/out.

**To Reproduce**
1. Go to any record, e.g. https://preview.fairsharing.org/#/FAIRsharing.wkggtx
2. Ensure you are logged out
3. Click on 'Actions' button
4. See error.

Then repeat these actions while logged in.

**Expected behavior**

_While logged out_
Enabled items: View Relation Graph, View Record History, Have a suggestion/question?

_While logged in as a standard user role **but not a maintainer of the record you're viewing**_
Enabled items: Request Ownership, Watch Record (if they're not already watching), View Relation Graph, View Record History, Have a suggestion/question?

_While logged in as a standard user role **and a maintainer of the record you're viewing**_
Enabled items: Edit Record, Request Ownership, Watch Record (if they're not already watching), View Relation Graph, View Record History, Have a suggestion/question?

_While logged in as any curator role_
Enabled items: Edit Record, Request Ownership, Watch Record (if they're not already watching), View Relation Graph, View Record History, Have a suggestion/question?

I realize that "Watch Record" is a bit different from the rest, and displays different text depending on whether or not the user is currently watching. This behaviour should be maintained.

**Screenshots**

While logged out (currently:
![actions](https://user-images.githubusercontent.com/143586/125067293-faff5900-e0ab-11eb-886f-95e067332ad5.png)

**Operating system and browser version**
Ubuntu Firefox 89.0.2 (64-bit)

**Additional context**
n/a

**Comment by hoseinmirian** [comment]
@allysonlister, when logged out now the behavior, is that we show all the menus to the user, in fact, they are active but when the user clicks on any of them(which needs a logged-in user), they will be redirected to the login/register page. is this the behavior you still insist to have or you want me to follow what you said in regard to a logged-out user anyway? (my opinion the way it is now is better due to we implicitly signaling users that they are able to do these actions but they need to be logged in first)

![image](https://user-images.githubusercontent.com/25683981/125311311-3bb8d580-e32b-11eb-9efd-28cdef14d955.png)

**Comment by allysonlister** [comment]
You make a really good point @hoseinmirian - the way it is now is more inclusive. I agree. Therefore I will re-write my rules below, taking that into account:

**Expected behavior**

_While logged out_
Items that work without logging in: View Relation Graph, View Record History, Have a suggestion/question?
All other items will redirect the user to a login. Once logged in, redirect their request according to the rules below:

_While logged in as a standard user role **but not a maintainer of the record you're viewing**_
Enabled items: Request Ownership, Watch Record (if they're not already watching), View Relation Graph, View Record History, Have a suggestion/question?
**Please note that the "Edit Record" option should be greyed out here.**

_While logged in as a standard user role **and a maintainer of the record you're viewing**_
Enabled items: Edit Record, Request Ownership, Watch Record (if they're not already watching), View Relation Graph, View Record History, Have a suggestion/question?

_While logged in as any curator role_
Enabled items: Edit Record, Request Ownership, Watch Record (if they're not already watching), View Relation Graph, View Record History, Have a suggestion/question?

I realize that "Watch Record" is a bit different from the rest, and displays different text depending on whether or not the user is currently watching. This behaviour should be maintained.


This is slightly more complex, but I agree with what you are saying. Please let me know if you have any questions! thanks :)

**Comment by allysonlister** [comment]
Hi all,

A quick update. Please let me know if this should go into a separate ticket. 

To prevent spam attacks as happened recently, until we determine a better long-term solution, please can the option "Have a suggestion/question?" send the email to contact@fairsharing.org *only*, and not to any record maintainers?

Thanks!

**Comment by knirirr** [comment]
> To prevent spam attacks as happened recently, until we determine a better long-term solution, please can the option "Have a suggestion/question?" send the email to [contact@fairsharing.org](mailto:contact@fairsharing.org) _only_, and not to any record maintainers?

That is then a `mailto:` link, which is easy enough to do.

**Comment by allysonlister** [comment]
As long as it pre-fills the subject line and/or the body text with the URL/name of the record in question, yes that would be cool. Otherwise we might need to consider the form so that we get the info we need.

thanks!


--

Dr. Allyson Lister

FAIRsharing Coordinator - Content & Community


Oxford e-Research Centre, University of Oxford

Data Readiness Group: https://datareadiness.eng.ox.ac.uk/


ORCiD: 0000-0002-7702-4495
@allysonlister

Please note that I work part time. If the matter is urgent, you may wish to email ***@***.******@***.***> instead.


For more on FAIRsharing, please see https://fairsharing.org

________________________________
