### ISSUE TITLE
associating of organisations with users

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#1154]
associating of organisations with users. allowing user to add new organisation and choose from the already existing organization. 

@allysonlister 

Good Afternoon Ally,

I need your thoughts about this subject:

How probable is that user wants to select multiple organisations and add or assign it to themselves? 
![image](https://user-images.githubusercontent.com/25683981/126158353-47ad3a38-6324-43a6-b745-9cb465a77865.png)

In my opinion single select is giving a better user experience

second: for deleting an organisation I am showing a dialog confirming it before doing it, so for assigning an organisation to a user do you need it to be confirmed or happen instantly?

**Comment by allysonlister** [comment]
Thanks @hoseinmirian !

1. There's two aspects to this answer. While I think that it is unlikely that a user would want to select more than one organisation from a single search (e.g. typing "NIH" and then choosing more than one from the resulting list), they *are* likely to need to be able to add multiple organisations, as sometimes people have more than one employer, e.g. contractors. I don't know how this would be implemented in the UI - that's your decision. But I'm happy to have no tickboxes in the search for "Available Organisations". It is enough for the user to be able to perform multiple searches, and then click on the row of the organisation they wish to add to their profile.
2. "deleting an organisation": you mean removing the association between a user and an organisation, right? You're not actually deleting an organisation object? But yes, no need to confirm when a user adds an organisation - just add it. The confirmation for removing a link to an organisation is sufficient.

Thanks!

**Comment by hoseinmirian** [comment]
I got all the answers I needed from your explanation. Thank you!

**Comment by hoseinmirian** [comment]
@allysonlister 

would you please clarify whether while creating a new organisation, defining its organisation types is necessary or not? I mean the field is required or not? thanks

![image](https://user-images.githubusercontent.com/25683981/126484791-6db0ce1c-5a36-4f6f-912a-82af620574ab.png)

**Comment by allysonlister** [comment]
Thanks! Yes people do need to define the organisation type.
