### ISSUE TITLE
Update Search Facet name from "Journals(s)" to "Publication venue(s)"

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1158]
Because some of the items in this field are not journals, but other ways to publish (e.g. pre-print services), we need to change the label. 

Existing label: "Journals(s)"[sic]
New label: "Publication venue(s)"

Thank you!
![image_2021_07_18T16_31_20_808Z](https://user-images.githubusercontent.com/143586/126286868-f5914209-741b-4dae-8f19-901ad49dac9b.png)

**Comment by hoseinmirian** [comment]
@knirirr I did push a commit regarding this branch into dev. so consider it as done. tnx
