### ISSUE TITLE
Small updates to Educational page

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1161]
Good evening!

There are two things that need to be checked/fixed as we have time on the educational static page please.

- [x] Are there internal links for each of the points within the FAQ section? I tried to view the page source but couldn't - it seems to be a load of javascript or similar. Please can you confirm that these are in place, and if so, how we find out what the URLs are for each FAQ item?
- [x] If it won't take too long, please can we make each FAQ item expandable? So, they would start out closed with only the question showing, and then each one could be expanded. If it would take a while, please wait and do it when you have the chance.

Thanks!

**Comment by hoseinmirian** [comment]
@allysonlister 

the first tick is done but the second part seems more complex and I ll create another ticket for that for later to deal with. 
In this ticket at the moment the anchor points are defined and are working as expected. second one is a big refactor for itself then I created another ticket for that... 

ticket: https://github.com/FAIRsharing/fairsharing.github.io/issues/1178
