### ISSUE TITLE
Front-end graph improvements

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1163]
After discussions with @knirirr and @terazus we are requesting some updates to the relationship graphs please.

- [ ] **Node update: please change node shapes to be smaller versions of the type icons.** In the past, @terazus thinks that there was a ticket concerning the replacement of the existing node shapes with small images for each record type (database, standard, policy, collection) based on the type icons. This may need @hoseinmirian to redraw these icons smaller. In particular, please can we ensure that each type icon is a different colour so that they stand out in both colour and design. You can look at the colours used in the legacy graphs by visiting any collection's graph page, e.g. https://fairsharing.org/graph/#/collection/bsg-c000090 (you may need to modify the colours slightly to fit with the rebuild's colour scheme).
- [x] **Colour for relationships**: If possible, colour relationships differently and move the names of the relationships to the legend.
- [ ] **Count number of nodes**, and if nodes are too high (e.g. >50) then start with level 1 rather than level 2 to help our users with slower machines :-)
- [x] **Type toggles**: be able to show/hide record types on the graph. 

Please let me know if you have any questions, and thanks!

**Comment by knirirr** [comment]
> In the past, @terazus thinks that there was a ticket concerning the replacement of the existing node shapes with small images for each record type (database, standard, policy, collection) based on the type icons.

https://github.com/FAIRsharing/fairsharing.github.io/issues/835

**Comment by allysonlister** [comment]
Apologies, there is one additional feature that would be nice to implement, given as that's what this ticket is about. I think it's a front-end feature, but happy to move it if required.

In the legacy system, the default view of the graph (see e.g. https://fairsharing.org/graph/#/collection/bsg-c000090) is similar, but not identical, to Level 1 in the rebuild. Similarly, legacy's "Outer" option is a bit like Level 2. 

What we don't have right now in the rebuild is a way to filter the displayed nodes by registry type. For example, play with https://fairsharing.org/graph/#/collection/bsg-c000001 and select/deselect standards/databases/policies in both the inner and outer levels. This allows a user to ask interesting questions of the graph such as "Show me all standards implemented by the resources in this collection".

It would be amazing to have this ability in the rebuild, too.

Thanks!

**Comment by terazus** [comment]
2, 3 and 4 done here https://github.com/FAIRsharing/fairsharing.github.io/pull/1190
Waiting for icons to do 1.

**Comment by knirirr** [comment]
I have added lower-case "registry" and "type" strings to each node in the graph so that @hoseinmirian can display the necessary icons without having to extrapolate from the marker shape. Later, I can remove the marker info.
Though there's already a PR for icons (https://github.com/FAIRsharing/fairsharing.github.io/pull/1196) this has every standard as the same icon, and so will need modifying. 

Edit: I would suggest leaving the functionality of the switch as it is at present (based on registry) even though icons will have to be displayed based on a Standard's type. The switch code will need modifying at a later date but there is insufficient time for this at present.

**Comment by knirirr** [comment]
There's a separate ticket for icons and a lot of this ticket can be superseded by a more detailed specification later, so I'll close it for now.
