### ISSUE TITLE
Various link / 404 errors in the new site

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1223]
In visiting beta.fairsharing.org, there are the following broken or incorrect links:

In the footer:
- [x] Weird behaviour: the links in the footer (see e.g. About us and Blog) that are present on this 404 page (https://beta.fairsharing.org/team) are **different** from those in the educational footer (e.g. https://beta.fairsharing.org/educational) and different again in the homepage footer (https://beta.fairsharing.org/).  I don't know why this is happening.
- [x] Blog - should go to https://blog.fairsharing.org/
- [x] Please remove / comment out the FAIRsharing facebook URL. It isn't correct (points to something else) and I'm not sure if it's used anymore.

Other locations
- [x] the two URLs at the bottom of https://beta.fairsharing.org/terms seem to be absolute - they are going to www.fairsharing.org rather than beta.fairsharing.org

Please let me know when these are resolved across all footers and on beta.fairsharing or one of your branches for me to review and double check.

Thanks very much!

**Comment by knirirr** [comment]
- [x] I just spotted a timeline link in the footer as well - IIRC the timeline has been removed, at least for the present.

**Comment by allysonlister** [comment]
Yes agreed - the timeline is not currently on the site. Thanks for spotting this!

**Comment by allysonlister** [comment]
Clicking on the "read more" in the attached screenshot from the homepage (any carousel item) also results in a 404. Please do let me know if it's just me :-)
![readmore](https://user-images.githubusercontent.com/143586/133498264-7f84f79e-086f-462c-a972-9b0123323ca7.png)

**Comment by knirirr** [comment]
> Clicking on the "read more" in the attached screenshot from the homepage (any carousel item) also results in a 404. Please do let me know if it's just me :-)

These links are placeholders (e.g. https://beta.fairsharing.org/alink/). Do you know where they are supposed to point?

**Comment by allysonlister** [comment]
Carousel items and their correct links: **all** of the following links go to various places within the https://beta.fairsharing.org/stakeholders page.

- [x] Researchers: Whatever the internal link is for the "Researchers in academia, industry and government" section of https://beta.fairsharing.org/stakeholders
- [x] Developers & Curators: Whatever the internal link is for the "Developers & Curators of resources" section of https://beta.fairsharing.org/stakeholders
- [x] Journal Publishers: Whatever the internal link is for the "Journal editors & Publishers " section of https://beta.fairsharing.org/stakeholders
- [x] Librarians and Trainers: Whatever the internal link is for the "Research data facilitators, librarians, trainers " section of https://beta.fairsharing.org/stakeholders
- [x] Societies and Alliances: Whatever the internal link is for the "Societies, unions and community alliances " section of https://beta.fairsharing.org/stakeholders
- [x] Funders: Whatever the internal link is for the "Funders and data policy makers " section of https://beta.fairsharing.org/stakeholders

**Comment by allysonlister** [comment]
Please note that I have updated the links in the previous comment, posting a new comment to trigger notifications.

**Comment by knirirr** [comment]
>   Weird behaviour: the links in the footer (see e.g. About us and Blog) that are present on this 404 page (https://beta.fairsharing.org/team) are **different** from those in the educational footer (e.g. https://beta.fairsharing.org/educational) and different again in the homepage footer (https://beta.fairsharing.org/).  I don't know why this is happening.

The only difference I could detect was that "About us" always pointed back to the same page (e.g. / on the homepage). Where should it be pointing?

**Comment by knirirr** [comment]
Confirmed in a call 27/09/21 - "about us" to be removed.
