### ISSUE TITLE
Password reset email uses "preview" in the generated URL

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1234]
**Describe the bug**
The URL created when resetting my password takes me to preview.fairsharing.org, not beta.fairsharing.org : http://preview.fairsharing.org/#/users/password/edit?reset_password_token=ZZZZZZZ replacing preview with "beta" does not result in a form that allows me to change my password.

**To Reproduce**
1. Go to https://beta.fairsharing.org/accounts/forgotPassword
2. submit email
3. click on resulting email with password reset token

**Expected behavior**
A working URL

**Comment by knirirr** [comment]
You should now be able to change your password. If you cannot then please contact me elsewhere with the username and/or email address of your account.

**Comment by allysonlister** [comment]
Thank you, the password reset has worked properly. I'll close the ticket, thanks!
