### ISSUE TITLE
Editing Organisations via the UI

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1240]
While the ability to edit organisations exists, it has not yet been implemented in the UI. When there is time to add this feature, having the ability to edit organisations records such as https://beta.fairsharing.org/organisations/1961 would be great.

Thanks very much!

**Comment by allysonlister** [comment]
Please note that this temporarily on hold while we have further discussions about organisations as a curation object. I will comment again when we're ready to move on this. Thanks!

**Comment by knirirr** [comment]
Before we proceed with this, we ought to determine who can edit organisations. Presumably, given that anyone can add themselves to one, it should be curators only?

**Comment by allysonlister** [comment]
yes please, let's do curators and higher - thanks! That way Champions can also edit them.
