### ISSUE TITLE
Newlines in display of curator notes

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1248]
We are now able to add newlines into our curator notes - yay, thank you! But although they are stored they are not displayed, e.g. https://beta.fairsharing.org/1380 . Please could you look into the feasibility of displaying such newlines?

Thank you!

**Comment by knirirr** [comment]
This has been done and will appear on beta soon. Please note that some curator notes might not have saved with line breaks and these may need to be re-added.
