### ISSUE TITLE
Add check for name/abbreviation/homepage already in FAIRsharing during record creation

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1249]
We had a really useful check in the legacy site that listed any records with similar name/abbreviation/homepages when a user was creating or updating a record and was editing those fields. It would be fantastic if a similar thing could be implemented in the new system, as we've already had someone create a new record, not realising that there already was one.

Thanks!

**Comment by knirirr** [comment]
Were any fields such as name, abbreviation URL identical in the duplicate that was created? Do you want to block the creation of duplicates or merely warn users that they might be about to create one? If they create one that might be a duplicate do you want to be warned of this, and, if so, how? Depending on the answer to these questions there may be more tickets (inc. server-side tickets) and more questions. 

If creation is not to be prevented then perhaps best is for the client to perform an Elasticsearch query based on the record name and to display an element on the edit form (perhaps under the name) with a warning that this might be a duplicate of the record. A link to the record would also be useful here. 

<img width="699" alt="Screenshot 2021-10-07 at 16 07 30" src="https://user-images.githubusercontent.com/3583375/136412562-cb9c27a4-2fde-4070-8c0c-d4444844667b.png">

N.B. records can now be created via the API directly without using the client, which is a major reason why the solution to this won't be quite the same as in the old system. Any constraints placed on the API (such as preventing the save of a record with an identical name to an existing one) will also apply to the client. 

Any thoughts on this, @terazus ?

**Comment by allysonlister** [comment]
1. The name was identical in this particular instance. However, in past, when editing on the legacy, I have discovered duplicates through all three of these methods.
2. Warn users they might be creating them, no need to block, thank you.
3. It would be useful, but not required (depending on the complexity of the task) to be warned in such cases. I believe an email was used in the past, but I have no strong opinion about how it might be done in this case. Would it be easier for you to automatically add a curator note when someone saves a record that might be a duplicate?
Thank you!

**Comment by knirirr** [comment]
Thanks. A curator note might well be a possibility if I can work around the permissions; I'll look into it.
