### ISSUE TITLE
Color scheme for relationship graphs

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1257]
Good afternoon!

Please could we update the relationship colours within the graph to match our FAIRsharing colour palette? Thank you! 

See https://beta.fairsharing.org/graph/1998 for an example, although this record does not contain all relationship types.. I'm not sure if there is a record that does? That would be interesting to find out... Note please that some existing colours are *very* close to each other (e.g. implemented by and collects) and we should ensure a reasonable colour distance.

Thank you!

**Comment by knirirr** [comment]
@hoseinmirian please keep this separate from https://github.com/FAIRsharing/fairsharing.github.io/pull/1227 in case we're not able to resolve the icon problem and don't merge that.
