### ISSUE TITLE
Organisations and their countries

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1262]
Organisations now have countries in the new data model. However, when I add an organisation in the edit interface, I am not given the option of adding a country. I realize this is likely due to a missing specification, and therefore here I am, asking for the ability to add the country value. I know that we have a controlled vocabulary for countries, so likely the user would have to choose from that list.

Thanks!

**Comment by knirirr** [comment]
To do this one it might first be of use to increase the visibility of the button which allows the adding of a new organisation. Currently it looks like this (to the right of 'select an organisation'):

<img width="1101" alt="Screenshot 2021-10-18 at 13 38 02" src="https://user-images.githubusercontent.com/3583375/137732220-aaf1ced8-dd9f-461e-8619-5b64c9192fb6.png">

Some text ("add new"?) might help. When clicked, this pops up:

<img width="1143" alt="Screenshot 2021-10-18 at 13 40 17" src="https://user-images.githubusercontent.com/3583375/137732436-5c1e6567-9212-4cc6-bf27-1feb80a77a01.png">

A field for adding the country needs to be added. A country field has already been added in general information and so could be used as the basis for a similar field here:



<img width="887" alt="Screenshot 2021-10-18 at 13 41 12" src="https://user-images.githubusercontent.com/3583375/137732601-94c4de7d-0d1b-491b-9858-452e2bda712a.png">
