### ISSUE TITLE
Add ability for curators to mark records as hidden

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1274]
Please can curator roles and above have the ability to mark/unmark a record as hidden? This ability in the legacy site was available from the Record Edit pages, but I'm happy to have the function wherever the developers feel it is best placed in the new system.

Thank you!

**Comment by knirirr** [comment]
This could be done by adding a checkbox to the record edit page, only visible to curators. I'd suggest putting this under the curator_notes text box as that's only visible to curators already.

This checkbox would, if checked set `hidden: true` in the record's data, or false if unchecked. The server should do the rest. 
Therefore:

```
{
  fairsharing_record: {
    ...
    hidden: true,
    ...
  }
}
```
