### ISSUE TITLE
Title in the browser tab doesn't update when no acronym available

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1295]
**Describe the bug**
When I leave a record from another record page, then search for a new record using the header that does not have an acronym to populate the browser tab's title bar, the tab title is populated with the name of the old record and isn't updated to reflect the new page the user is on.

**To Reproduce**
1. Go to https://beta.fairsharing.org/1380
2. search using the header for a record without an acronym, e.g. "FAIR chemical structure template"
3. The search page (https://beta.fairsharing.org/search?q=FAIR%20chemical%20structure%20template) shows "FAIRsharing | search" but then when I click on the new record page it shows "FAIRsharing | NBCA-R" still (https://beta.fairsharing.org/1539)
4. This behaviour does not happen when searching for a record with an acronym. From 1539, use the search bar in the header and search for "ddbj". 
5. Click on the DDBJ record (https://beta.fairsharing.org/2894) - you'll notice that that acronym in the browser tab title is updated.

**Expected behavior**
The browser tab title to reflect the page the user is on. If no acronym, I believe the current behaviour is to show only "FAIRsharing". I would be happy to carry on doing this, or just provide the first X characters from the  full name (where X is a number that you deem appropriate)

**Screenshots**
![1539](https://user-images.githubusercontent.com/143586/138238839-1c63921c-f977-40ef-bf57-bf7bb2f4b3c1.png)

**Operating system and browser version**
Ubuntu / Firefox

**Comment by knirirr** [comment]
I can't reproduce this behaviour at all. 
In any case, I have made a change to the relevant code in the hope that may fix it for you.
