### ISSUE TITLE
Bug on the curation dashboard

### ISSUE THREAD

**Issue by delphinedauga** [FAIRsharing/fairsharing.github.io#1301]
**Describe the bug**
The line on the "RECORDS/EDITS AWAITING APPROVAL" section from the curation panel disappear after processing notes edition and save.

**To Reproduce**
1. Go to 'https://beta.fairsharing.org/curator'
2. Click on 'Processing notes' corresponding to one record
3. Edit and Save your 'Processing notes' (e.g. Weird record, should be checked the affiliation before approval)
4. Go to another task (close the curation dashboard, navigate to other record, whatever)
5. Go back to the curation dashboard
4. See error : the line / record where you mention the processing notes has disappeared and has been automatically approved

**Expected behavior**
The record shouldn't be approved

**Screenshots**
![Oct-26-2021 17-40-51](https://user-images.githubusercontent.com/59688426/138913617-c704457f-58a4-4d03-82f4-e69a58d252b8.gif)

**Operating system and browser version**
mac OS Big Sur Version 11.0.1 - Chrome Version 94.0.4606.71 (Build officiel) (x86_64)

**Comment by knirirr** [comment]
Everything's correct on the server; the client explicitly requests that the record be marked as approved when a processing note is saved. 
It should be easy enough to change the request made by the client.

**Comment by knirirr** [comment]
The change has been deployed to beta.
