### ISSUE TITLE
Inconsistencies in carousel slides in home page

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#1306]
fonts and letters reported broken and abnormal. Please either simply write what you see or better to share your screenshots and report. Thanks. 
@allysonlister 
@terazus 
@ramGranell 
@knirirr

**Comment by knirirr** [comment]
When loading https://beta.fairsharing.org/assets/Home/Tabs/trainer.svg I see:

<img width="1315" alt="Screenshot 2021-11-01 at 11 18 41" src="https://user-images.githubusercontent.com/3583375/139663675-8f5f371f-158e-4a87-8d84-72cd2382509a.png">

**Comment by ramGranell** [comment]
When I open it in the Mac latop (both Firefox and Chrome) I saw exactly the same than Milo (i.e. "Stand rds"), however in my Linux machine (both Firefox and Chromium) it can be seen properly (see attached image) 
![Screenshot_20211101_112647](https://user-images.githubusercontent.com/39826987/139664822-aff540b6-367c-4aac-b496-717e0a2fb02d.png)

**Comment by allysonlister** [comment]
In my Ubuntu / Firefox combination, both fonts aren't correct:

![one](https://user-images.githubusercontent.com/143586/139699356-ccd96137-ae88-478c-8db3-952233b9fb1e.png)

**Comment by hoseinmirian** [comment]
ok thanks. I appreciate it if you also have told me about the local output appearance?

**Comment by allysonlister** [comment]
What do you mean  by "local output appearance" please?
