### ISSUE TITLE
No warning message "Are you sure you want to leave this page" when you "save & exit" the "additional information" section

### ISSUE THREAD

**Issue by delphinedauga** [FAIRsharing/fairsharing.github.io#1313]
**Describe the bug**
When I updated the homepage link of a record, it doesn't appear on the history log.

**To Reproduce**
1. Go on a record page (e.g. https://beta.fairsharing.org/FAIRsharing.xp1x9c)
2. Click on 'edit record'
3. Update the homepage link without saving the general information section
4. Go to the "additional information" section" (the problem appears only with that section)
5. Edit any of the fields
6. Click on 'save and exit'
7. Errors : no warning message « Are you sure you want to leave this page? You have 1 unsaved modifications. » and the edit on the information section has not been saved

**Expected behavior**
- warning message :  « Are you sure you want to leave this page? You have 1 unsaved modifications. » 

**Screenshots**
![Nov-02-2021 16-34-35](https://user-images.githubusercontent.com/59688426/139878940-dbbe26da-ad98-4098-aa60-82835064fd24.gif)

**Operating system and browser version**
macOS Big Sur version 11.0.1 - Chrome Version 95.0.4638.54 (Build officiel) (x86_64)

**Comment by knirirr** [comment]
There's something problematic in this function:

https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/views/CreateRecord/Editor.vue#L139-L148

If that's called when on the additionalInfo tab then getAllChanges() incorrectly reports that there are 0 changes in the generalInformation section. If called from any other tab then it provides the correct result.

Do you have any idea, @terazus ?

**Comment by terazus** [comment]
Will have a look next week after i'm done with my unit testing.

**Comment by terazus** [comment]
I'm currently investigating this issue.
