### ISSUE TITLE
"Records related to this organisation"  text alignment

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#1319]
On a large screen:

<img width="1172" alt="Screenshot 2021-11-03 at 16 22 32" src="https://user-images.githubusercontent.com/3583375/140102267-d8ee0440-a8ab-4656-a805-5c1de69b0a28.png">

On one that is too small:

<img width="680" alt="Screenshot-2021-11-03-at-16 16 02(1)" src="https://user-images.githubusercontent.com/3583375/140102381-77d52dc6-13a9-4625-b252-893ac9293be4.png">

These could do with being aligned to the left on smaller screens as well.

**Comment by ramGranell** [comment]
The error keeps happening as here https://beta.fairsharing.org/organisations/1576. Im using a 13" screen laptop. 
<img width="371" alt="Screenshot 2021-11-16 at 14 19 46" src="https://user-images.githubusercontent.com/39826987/142003809-6629e2ad-deb4-4f2d-9468-d3153d37b37c.png">
