### ISSUE TITLE
Problem with the syntax checker in the collection record / additional information section / reference url 

### ISSUE THREAD

**Issue by delphinedauga** [FAIRsharing/fairsharing.github.io#1320]
**Describe the bug**
We can enter a non-valid url in the reference url field. 

**To Reproduce**
1. Go to a collection record (e.g. https://beta.fairsharing.org/3517)
2. Click on 'edit record'
3. Go to the additional information section
4. Enter 2 url with a space between them in the url reference field (e.g : https://bioschemas.org/profiles/ 
https://bioschemas.org/liveDeploys/). 
5. Save and exit

**Expected behavior**
A warning message saying that you should enter a valid url. Note that if you enter any character string, the syntax checker detect the pb and send a warning message.

**Screenshots**
![Nov-04-2021 10-11-13](https://user-images.githubusercontent.com/59688426/140287583-92be89c2-a9c9-48b6-8bb8-b71dfd7a1875.gif)

**Operating system and browser version**
mac OS Big Sur Version 11.0.1 - Chrome Version 94.0.4606.71 (Build officiel) (x86_64)

**Comment by knirirr** [comment]
Unfortunately, though that produces a 404 it's still a valid URL, so there's not anything we can do to deal with this.
