### ISSUE TITLE
Enabling logos for records

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1332]
This is related to a Zulip discussion at https://pyroeis.oerc.ox.ac.uk/#narrow/stream/8-FAIRsharing-Rebuild/topic/UI.20Feedback/near/33557

Please can we begin work on enabling logos for all record types. From what was said in the Zuplip discussion, I believe the following things need to occur:

1. Creation of UI code to add/remove/update logos on a record.
2. Copying logos that are already present from the legacy (collections only) to their equivalent records on new site.
Thanks!

**Comment by knirirr** [comment]
At the time the current record page was designed logos were not wanted for records. Some thought must be given before starting work as to where to put them and how to deal with varying shapes, qualities etc.
Dealing with the edit form will be rather involved as well.

**Comment by allysonlister** [comment]
Thank you, this absolutely makes sense. I'll add a discussion of this at the next dev meeting, and also talk with SAS about her thoughts.

**Comment by allysonlister** [comment]
We have spoken about this with all parties concerned, and can now further summarise our request as follows with regards to display:

* When there is a logo, move the name to the right slightly and place the logo next to it.
* Allow two fixed sizes for logos: rectangle or square (please choose appropriate sizes for the records). Allow user to choose which shape works best for them, and to 1) drag and 2) zoom image to fit as per other common image uploaders, e.g. LinkedIn.

**Comment by knirirr** [comment]
For the uploader part, something like this might suffice, perhaps embedded into the general info. editing form: https://github.com/alessiomaffeis/vue-picture-input
But, as the edit form uses our REST API it will be necessary to encode the image before uploading. See this example:

https://github.com/FAIRsharing/FAIRsharing-API/blob/master/test/controllers/fairsharing_records_controller_test.rb#L159-L162

**Comment by hoseinmirian** [comment]
we also have the built-in component of vuetify to use:
https://vuetifyjs.com/en/components/file-inputs/

https://vuetifyjs.com/en/api/v-file-input/#props

**Comment by knirirr** [comment]
> we also have the built-in component of vuetify to use: https://vuetifyjs.com/en/components/file-inputs/
> 
> https://vuetifyjs.com/en/api/v-file-input/#props

Interesting, thanks. If it can encode the file as shown in the link above then this might do the trick.

**Comment by hoseinmirian** [comment]
also this library is very popular:
https://github.com/kartoteket/vue-image-upload-resize#readme

**Comment by hoseinmirian** [comment]
> 

one of the good thing about the none-vuetify library is that we can specify width and height o

**Comment by hoseinmirian** [comment]
> > we also have the built-in component of vuetify to use: https://vuetifyjs.com/en/components/file-inputs/
> > https://vuetifyjs.com/en/api/v-file-input/#props
> 
> Interesting, thanks. If it can encode the file as shown in the link above then this might do the trick.

it needs to be checked. one of the problem we might have with vuetify  is that it seems it does not have a built-in width and height definition functionality. So the good thing about 3rd party libs is that they have covered many of the use cases. 
<img width="881" alt="image" src="https://user-images.githubusercontent.com/25683981/144452064-86331367-016d-4ed5-9fdd-7c2c1d0dc8d0.png">
for example above it says you can put condition over the size of the image. ok fine but we need to check if we also can check value.width and value.height is equal so its a square. still its not obvious if it take it as a max-width or max-height. First I check with Vueitfy to not install extra lib. if not successful, then I go for 3rd parties.
