### ISSUE TITLE
Missing DOI link in publication in the record view

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1337]
**Describe the bug**
https://beta.fairsharing.org/3311 contains one publication, which has a DOI (10.1093/llc/fqv051). This DOI is present in our metadata, but isn't being displayed within the record view via the "View Publication" button that normally links a publication field to its DOI.

**To Reproduce**
1. Go to https://beta.fairsharing.org/3311
2. View publication.

**Expected behavior**
The presence of the "View publication" button

**Screenshots**
Publication in  https://beta.fairsharing.org/3311
![no-link](https://user-images.githubusercontent.com/143586/141272523-7da31e9f-cf25-4476-b277-8caa0a46f085.png)

Other example publication for reference, from GenBank https://beta.fairsharing.org/FAIRsharing.9kahy4
![view-publication](https://user-images.githubusercontent.com/143586/141272542-42eb66ca-cc94-485b-989c-6083d7fa9a50.png)

**Operating system and browser version**
Ubuntu / Firefox

**Comment by knirirr** [comment]
>  This DOI is present in our metadata,

That turns out not to be the case.
Here's the data for that record:

```
#<Publication id: 622, pubmed_id: nil, title: "DASCH: Data and Service Center for the Humanities", year: 2015, url: "https://doi.org/10.1093/llc/fqv051", authors: "Lukas Rosenthaler, Peter Fornaro, Claire Clivaz", journal: "Digital Scholarship in the Humanities", doi: nil, created_at: "2021-09-30 08:23:28.428242000 +0000", updated_at: "2021-09-30 08:23:28.428242000 +0000"> 
```

The DOI field is `nil`; whoever created that record instead supplied it as part of the value of the URL field. So, what I'll do is add an additional button for linking when URL is supplied, as there may well be other cases of links which don't involve a DOI or pubmed_id value being supplied.

**Comment by allysonlister** [comment]
Thank you very much, apologies for my mistake!

**Comment by knirirr** [comment]
No problem. Creating a PR now.
