### ISSUE TITLE
Update to Database summary/breakdown on homepage

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1338]
While I fully realize we recently updated this with #1288 , I've been asked to update the Databases "entry point" on the homepage again.
![databases](https://user-images.githubusercontent.com/143586/141274267-c9b5d5c6-6cbe-4c6e-bf83-48ddc896871d.png)

Please could you remove the current summary of database records across top-level subject areas, and instead do the same as is currently done for standards and policies? Specifically, the links for databases should be the three types of database records:

* Repositories
* Knowledgebases
* Knowledgebases and Repositories

Now that this information has been curated, it is good to show.

Thanks!

**Comment by knirirr** [comment]
#1288 involved quite a bit of work including adding a new API call on the server. This will have to be pulled out again.
