### ISSUE TITLE
Suppress "awaiting DOI" for collections 

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#1359]
From https://github.com/FAIRsharing/FAIRsharing-API/issues/374:

> Collections will never be assigned DOIs. As such, it could be confusing to users to see the "Awaiting DOI" message for collection records. Please can we hide/remove this field for collections...

**Comment by hoseinmirian** [comment]
@knirirr do you want to also remove the icon in these cases? I think it makes sense to not show it all if you agree
<img width="147" alt="image" src="https://user-images.githubusercontent.com/25683981/142230051-6fec4c5b-05b7-4967-8548-fee4c36aebca.png">

**Comment by knirirr** [comment]
Yes, I'd guess that removing that as well would be appropriate.
