### ISSUE TITLE
User defined tag search "pill" doesn't say "User Defined Tag"

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1365]
**Describe the bug**
The pill that shows which search facets are currently in play does not show the facet for "User Defined Tag". Apologies, I don't know the correct vocabulary for this so I will put the screenshot right at the top. Is an issue for all user-defined tags, but this example is with Bathymetry
![Bathymetry](https://user-images.githubusercontent.com/143586/142270619-2bc1da86-bc8b-40d6-8228-dfd9daa2b2cf.png)

**To Reproduce**
1. Go to 'https://fairsharing.org/...'](https://beta.fairsharing.org/search?userDefinedTags=Bathymetry)
2. See error

**Expected behavior**
should say "user defined tag: Bathymetry" or some such phrase.

**Operating system and browser version**
Ubuntu / Firefox

**Comment by knirirr** [comment]
I think that the cause was this change:

https://github.com/FAIRsharing/fairsharing.github.io/issues/1270

I can work around it (see forthcoming PR) though I still think it's better to have the search facet for these tags.

**Comment by allysonlister** [comment]
Thank you!

If you would prefer to put user-defined tags back in as a search facet, I am happy with that. I realize it looks like you've already implemented the workaround, so I'll leave it to you to decide how you'd like to proceed.

**Comment by knirirr** [comment]
I'll leave things as they are until such time as someone notices they're missing and complains, I think.
