### ISSUE TITLE
Static page update: Stakeholder page

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1379]
https://beta.fairsharing.org/stakeholders

## General Note

Some of the URLs within this page that point to FAIRsharing are absolute and not relative. Please can you check that all FAIRsharing URLs are composed as they should be?

## Modification 1

In "Developers & Curators of resources"
1. edit the header of this section (note the lower case) => to => "Developers & curators of resources and tools"

2. Edit the last sentence in that section, moving it closer to the paragraph right before it, from "If your resource is recommended in a data policy from a journal, funder or other organisation, it will be given a ‘recommended’ ribbon, which is present on the record itself and clearly visible when the resource appears in search results" => to => "If your resource is recommended in a data policy from a journal, funder or other organisation, it will also be searchable under a dedicated Recommendations (https://beta.fairsharing.org/search?isRecommended=true&page=1&searchAnd=false&fairsharingRegistry=database,standard) page."

3. At the end of this section add a new paragraph: "If you are the developer of a tool that requires access to the descriptions we provide on standards, databases, policies, as well as our collections, you can use the FAIRsharing API to power your system with our information. See our Licence (https://beta.fairsharing.org/licence) and API (https://beta.fairsharing.org/API_doc) pages for details."

In "Journal editors & Publishers"
1. edit the header of this section (note the lower case) => to => "Journal publishers and organizations with data policies"

1. Edit the following sentence from ".....recommend to users or their community (see examples of recommendations created by eight main publishers and journals: https://fairsharing.org/recommendations, including some generalist and many domain-specific databases and repositories)." => to => "".....recommend to users or their community; see examples of our recommended resources (https://beta.fairsharing.org/search?isRecommended=true&page=1&searchAnd=false&fairsharingRegistry=database,standard)."

**Comment by knirirr** [comment]
For the links, either "/link" or `getHostname()` + "/link" should do the trick.

**Comment by allysonlister** [comment]
Thank you, however we don't usually put the links "in the raw" in parentheses like that. I apologies for not being explicit, but please can you make hyperlinks rather than visible URLs?

For example, in the item below, that URL should be the link for "Recommendations". Please ensure the link is also a relative and not absolute link.

> 2\. Edit the last sentence in that section, moving it closer to the paragraph right before it, from "If your resource is recommended in a data policy from a journal, funder or other organisation, it will be given a ‘recommended’ ribbon, which is present on the record itself and clearly visible when the resource appears in search results" => to => "If your resource is recommended in a data policy from a journal, funder or other organisation, it will also be searchable under a dedicated Recommendations (https://beta.fairsharing.org/search?isRecommended=true&page=1&searchAnd=false&fairsharingRegistry=database,standard) page."


In the item below, that URLs should be the link for "Licence" and "API". Please ensure the links are also relative and not absolute.

> 3\. See our Licence (https://beta.fairsharing.org/licence) and API (https://beta.fairsharing.org/API_doc) pages for details."


In the item below, that URLs should be the link for "Recommended Resources". Please ensure the link is relative and not absolute.

> 2\. recommend to users or their community; see examples of our recommended resources (https://beta.fairsharing.org/search?isRecommended=true&page=1&searchAnd=false&fairsharingRegistry=database,standard)."


And there are also other instances of this. I've put some here, but please make sure that I haven't missed any

https://doi.org/10.25504/FAIRsharing.y0df7m -> ICPSR archive
https://doi.org/10.25504/FAIRsharing.EZCpPd -> replace "DDI standard" with "DDI Codebook"

> ICPSR archive of behavioural and social science research data that uses the DDI standard: https://doi.org/10.25504/FAIRsharing.y0df7m

Thanks!

**Comment by knirirr** [comment]
> Thank you, however we don't usually put the links "in the raw" in parentheses like that. I apologies for not being explicit, but please can you make hyperlinks rather than visible URLs?

If you'd like to make this sort of thing more explicit in future I'd suggest using a format such as this:

[Text To Display|http://url-to-which-to-link.com]

This should make it clear as to what's needed. I'd have interpreted what's in the ticket the same way @hoseinmirian did (and so approved it).

**Comment by allysonlister** [comment]
Thank you, both of you. I will ensure I provide that format for future cases of this. :-)

**Comment by hoseinmirian** [comment]
the link cannot be relative due to data is read from a json file and when its printed in the page, it will not recognize getHostName to update the current host name. So now its hardcoded as beta.fairsharing.org but when or better before it is transferred to the actual domain fairsharing.org, these absolute links from the json needs to be updated.

**Comment by hoseinmirian** [comment]
@allysonlister I appreciate if you approve the way links are wrapped within paranteces. I just replaced the links by words. I did not touch the parentheses position. thanks
<img width="2068" alt="image" src="https://user-images.githubusercontent.com/25683981/144426775-ae206ad7-3b31-4d24-97d5-748f19e24184.png">

**Comment by hoseinmirian** [comment]
@allysonlister 
what about these ones? please clarify if you need them to be replaced by a word:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/25683981/144427982-c7666241-b098-451b-af2e-bd698700d6ac.png">

<img width="720" alt="image" src="https://user-images.githubusercontent.com/25683981/144428053-46347179-710c-4927-a491-3036e647806f.png">

**Comment by allysonlister** [comment]
Please remove the parentheses, they should read like standard sentences. And also update the other examples you've given in the same way.

**Comment by hoseinmirian** [comment]
@allysonlister thanks for responding to the questions I had but still I did not get my answer to my last question? what word do you suggest explicitly instead of those 2 links I provided that you did not define me the text for them to be shown? thanks

**Comment by allysonlister** [comment]
I'll add my comments to the other PR. Please note that, as you know, I don't work Fridays and you only asked me yesterday to comment - sometimes I cannot reply straightaway, and any Friday comments are bonuses :)
