### ISSUE TITLE
Add additional confirmation option to curator dashboard for approvals of hidden records

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1385]
Whenever a record with hidden = true is approved by a curator, update the confirmation dialog from this:

![](https://user-images.githubusercontent.com/143586/143215633-2cca7d53-afb0-4ae1-913b-8c2965ce0a2d.png)

to a slightly modified version with an identical dialog, but with one additional clickable option: "CANCEL / OK / OK AND KEEP HIDDEN"

* CANCEL - cancel approval operation (same behaviour as now)
* OK - approve record and set hidden = false
* OK AND KEEP HIDDEN - approve record and retain the hidden = true (same behaviour as the OK button now)

Thanks!

**Comment by knirirr** [comment]
This is awaiting review.
