### ISSUE TITLE
Country order bias?

### ISSUE THREAD

**Issue by sveinugu** [FAIRsharing/fairsharing.github.io#1386]
**Describe the bug**
While adding a new record for FAIRsharing, I attempted to add the countries: "Norway, Spain and United Kingdom", in that order. However, in the resulting stored record, the order of the countries was rearranged to "United Kingdom", "Norway", "Spain". I have been unable to correct the order. This makes no sense, as there order of entry is also by coincidence the lexicographically correct order. 

There is no reason to belive there is a UK bias in the FAIRsharing software, however I have trouble understanding which logic this bug might be following. Switching "United Kingdom" with "United Stated" (which I did by mistake) creates the following order: Norway, United States, Spain even though "United States" was added last.

**To Reproduce**
1. Edit the "FAIRtracks" record at [beta.fairsharing.org](https://beta.fairsharing.org/3640)
2. Remove all countries. 
3. Click: Save and Exit
4. Action: Edit record again
5. Add the countries: Norway, Spain, United Kingdom (in that order)
6. Click: Save and Exit

**Expected behavior**
The countries should be shown in the order they were entered.

**Comment by knirirr** [comment]
In this case we'd meant to sort countries alphabetically but this was overlooked, so it's now been fixed.
We don't have any plans to support changing the order other than that.
Were you thinking of representing which country was the more important contributor? That should be possible by setting a "lead organisation", and countries can be applied to organisations.

**Comment by sveinugu** [comment]
I don't have an opinion on whether the list should be sorted or not. But since the list was apparently not shown in sorted order, I wanted the order to at least not mislead. I see now (looking at the edit history of the record) that the list was sorted by country id, which makes sense on the backend, but not for the user. 

Btw: I believe the lists of the various types of tags are also not sorted by human readable label, if that is the intended behaviour.

**Comment by knirirr** [comment]
The countries were sorted by whatever order the database chose to return them, which I have now changed.
There's some difference of opinion on sorting of the other tags and we intend to leave them as they are for now.
