### ISSUE TITLE
Issue storing relations to other records

### ISSUE THREAD

**Issue by sveinugu** [FAIRsharing/fairsharing.github.io#1387]
**Describe the bug**
While creating the 'FAIRsharing' record, I added a set of relations to other records. However, I was unable to save these relations. After clicking 'save and continue', a spinning wheel appeared on the save buttons and nothing happened for a long time. Clicking "Exit Editing" produced a dialog box warning that I would loose 1 unsaved modification. Clicking OK works. However, trying to add the same relation again gives an error.

**To Reproduce**
1. Go to 'https://beta.fairsharing.org/3640'
2. Actions->Edit record. Select tab "Relation to other record"
3. Add a relation
4. Click "Save and continue" -> a spinning wheel should start
5. Click "Exit editing" and "Accept"
6. Actions->Edit record. Select tab "Relation to other record"
7. Add a relation
8. Click "Save and continue"

**Expected behavior**
Addition of the defined relations to the record

**Screenshots**

![CleanShot 2021-11-24 at 14 48 51](https://user-images.githubusercontent.com/3090622/143250536-fa184e09-c56e-410e-b4e3-dbfe9f77ff8e.png)

**Operating system and browser version**
Mac OS Big Sur 11.2.3 - Brave 1.31.91

**Comment by knirirr** [comment]
Thanks for reporting this. 
I've tracked down the issue; missing headers on one of the queries sent to the API. 
All appears to be working as expected now.
