### ISSUE TITLE
add maintainer info to "records relating to this organisation" table in the organisation pages

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1397]
When looking here: https://beta.fairsharing.org/organisations/1991 I felt it would be really useful to have two things:

1. A link from this table to the search page that would retrieve these same records, thus allowing the user access to the facets for this subset of records.
2. A method of knowing at a glance within the table if each record is maintained. Perhaps a dot in the same way as the record status, or even color the row a different color? If point (1) is easier, please do that and ignore this one, as one can filter on maintainer in the main search pages.

Thanks!

**Comment by knirirr** [comment]
I've done (1) and this has been deployed.
