### ISSUE TITLE
Removing relationships - errors

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1416]
**Describe the bug**
Deleting relationships when "policies" was deselected resulted in 
1. silent deletion of policies even though they were deselected and therefore not visible, and
2. the list of relationships wasn't updated (clicking on the trash can icon resulted in the count of relationships decreasing but no apparent change to the relationship list)

**To Reproduce**
1. Go to the preview site, as this change has already happened in the beta site. Visit https://preview.fairsharing.org/3350
2. Try to delete just databases and standards by deselecting "policies" and start deleting
3. Notice the errors mentioned above.

**Expected behavior**
only remove those relationships that you choose, and update the list of relationships accordingly as you remove them.

**Screenshots**
After performing the update shown in this gif, **all** relationships to policies had disappeared, as well as a few of the standards/databases!
![removing-relationships](https://user-images.githubusercontent.com/143586/145412491-235d8a5f-579e-4ebd-a95f-4a5d4a8595af.gif)

**Operating system and browser version**
Ubuntu / Firefox

**Additional context**
Please ping me if you have any questions, as I understand this is a complex issue. Thanks!

**Comment by knirirr** [comment]
I'd guess that toggling those switches is hiding elements from the user but the hidden elements are being deleted when visible ones are being clicked upon. Perhaps it's somewhere here: https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/components/Editor/EditRelationships.vue#L567-L573

Do you have any thoughts on this @terazus  ?

**Comment by delphinedauga** [comment]
Good afternoon !

We notice the same bug this morning with the search option :
![Jan-11-2022 14-31-05](https://user-images.githubusercontent.com/59688426/148952045-eda3ab2c-a152-42ef-80be-6bdf4e0d0b99.gif)

**Comment by knirirr** [comment]
@delphinedauga where are you seeing this? If it's on preview then that system is out of date; please compare with a more recent build.

**Comment by allysonlister** [comment]
We were definitely editing in the beta - not preview. Delphine may remember exactly which record, but the behaviour can be seen in any record, e.g. https://beta.fairsharing.org/FAIRsharing.q4ahrn

**Comment by knirirr** [comment]
I have already fixed it by my fix has been reverted (inadvertently, of course). I've added an agenda item to discuss dealing with this sort of thing in our next Monday meeting.
Meanwhile, I'll close the ticket and the fix can be re-applied once you've checked the new PR.
