### ISSUE TITLE
Retrieval of NAR publication via DOI missing journal name and PubMed ID

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1419]
**Describe the bug**
When the information about any NAR publication is retrieved via DOI, there is no journal name or PubMed ID filled in, although this information does seem to be available.

**To Reproduce**
1. Edit any record - go to Publications tab
2. Choose a publication from https://academic.oup.com/nar/ (I used 10.1093/nar/gks1217 but this is now loaded into beta - you'll need to use this DOI in preview if you want to see the exact behaviour)
3. Tell FAIRsharing to import from doi

**Expected behavior**
All available fields to be filled in.

**Screenshots**
![no-journal](https://user-images.githubusercontent.com/143586/145555146-8d13d7b6-7e74-40f2-9f40-987814bac29e.png)

**Operating system and browser version**
Ubuntu / Firefox

**Additional context**
Marked as low priority because we can still fill these values in manually. Thanks!

**Comment by knirirr** [comment]
As far as I can tell this is not a problem with our application. Here's the data that's returned and I cannot find any reference to the journal in it:

[journal.json.txt](https://github.com/FAIRsharing/fairsharing.github.io/files/7727250/journal.json.txt)

Strangely, the journal is supplied in the list of references returned.

**Comment by allysonlister** [comment]
This happens with all NAR records - so it might be worth contacting NAR and finding out if there is a bug in the data they are providing for the json format?

**Comment by allysonlister** [comment]
This also happens with 10.1093/bib/bbab350  - which is the journal Briefings in Bioinformatics from Oxford Academic.

**Comment by knirirr** [comment]
Another look at this shows that the journal title was being looked for as `container-title-short`, which is not always present. `container-title` is another option. 

10.1093/bib/bbab350 comes up as a 404 when it's looked up.
