### ISSUE TITLE
Static Page Update: Community page

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1422]
We have some new information for our Advisory Boards; primarily ORCID links but also ensuring that each person has their affiliation only (and not title as well), as there were inconsistencies in the page.

I will send the link to the relevant googledoc via Zulip.

thanks! Allyson

**Comment by hoseinmirian** [comment]
@allysonlister please send the link in my zulip. there are a a lot of posts sent in zulip. tnx

**Comment by allysonlister** [comment]
All you have to do is search "community page" in zulip, and the relevant post appears.

I have also forwarded it directly to you.

Thanks!
