### ISSUE TITLE
Icons / graphical summary to highlight certain record metadata, to be shown in badges and in general information

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1435]
This relates to #1119 as the icons I'm requesting should be present both in the badges and in an appropriate location in the General Information section. There are two parts to this: the icons themselves, which can be worked on separate to part 2, the integration in the site and in the record badges.

For now, please could we have some mockups of the images themselves, rather than a full implementation in FAIRsharing. Then we can refine the design before we start integrating within FAIRsharing.

Full specifications available on the internal GitBook page at https://app.gitbook.com/o/-MchtBAOWXh2gO--zz7m/s/-MkSKpWh9NA-iywIqhP_/please-can-we/record-indicators

**Comment by allysonlister** [comment]
Please note I have updated both the Gitbook page, and made a corresponding mock-up, linked both in the gitbook page and here (accessible internally only). It's in my usual style (which means it has absolutely zero style or panache!!), but hopefully will give an idea of what the next mockup should contain: https://docs.google.com/presentation/d/12VLt9rOzqywjymQ9uyLx6jXHAnIqEAa3TlPcdyFTroA/edit?usp=sharing

Thanks!

**Comment by knirirr** [comment]
This (and https://github.com/FAIRsharing/fairsharing.github.io/issues/1119) are describing a couple of different uses.
Based on discussions and initial mockups Google docs and Gitbook pages elsewhere, I suspect that one of these uses is not really an image file at all but a javascript widget (which will itself load various images). 

Further discussion is needed to clarify this, after which I'd suggest closing this ticket and #1119 and opening new ones for relevant tasks (e.g. server-side widget controller, widget javascript code, images, if my guess is correct).
