### ISSUE TITLE
organisations linked to a record using "Associated with" are not visible in the record display

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1440]
**Describe the bug**
The new relationship from organisation -> record, "associated with", is not visible in the record display

**To Reproduce**
1. Go to https://beta.fairsharing.org/2507
2. Note that the ELIXIR organisation is not visible
3. Edit this record
4. Note that the organisation is saved, with the "associated with" relationship

**Expected behavior**
The organisation to be visible

**Operating system and browser version**
Ubuntu / Firefox

**Additional context**
Relates to #1429

**Comment by allysonlister** [comment]
It also appears that any edit to a record that results in either

1. a new organisation linked with "associated with", or
2. an existing organisation switched from any other relationship to "associated with" 

...results in the edit being performed - and present in the log history - but NOT being sent to the approval queue for checking. You can use the same URL as above to discover this.

**Comment by knirirr** [comment]
> It also appears that any edit to a record that results in either
> 
>     1. a new organisation linked with "associated with", or
> 
>     2. an existing organisation switched from any other relationship to "associated with"
> 
> 
> ...results in the edit being performed - and present in the log history - but NOT being sent to the approval queue for checking. You can use the same URL as above to discover this.

This is unrelated to the visibility of the record and requires a new feature on the server: https://github.com/FAIRsharing/FAIRsharing-API/issues/411
