### ISSUE TITLE
Relation Graph not showing life cycle status color for records

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1443]
**Describe the bug**
A collection's graph is just showing the default blue icons rather than the status-based colors, even though the legend for those statuses is visible

**To Reproduce**
1. Go to https://beta.fairsharing.org/graph/3513
2. See that no statuses are being shown

**Expected behavior**
Nodes should be colored by life cycle status for all FAIRsharing records

**Operating system and browser version**
Ubuntu / Firefox

**Comment by knirirr** [comment]
This has been resolved by re-generating graphs so the new field required by the client was added.
