### ISSUE TITLE
Curation dashboard: approval of maintainer also approves any outstanding edits

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1453]
**Describe the bug**
If we approve a new owner for a record, the curator dashboard automatically approves any outstanding edits to the record at the same time, silently. I think these should be separate actions. 

**To Reproduce**
1. Use the preview site or similar
2. Visit a record and make an edit
3. Go back to that record and claim ownership
4. Go to the curation dashboard and see both the edit and the approval request in the queue
5. Approve the new maintainer
6. See that the record edits are now approved and have been removed from the approval queue.

**Expected behavior**
These two actions are independent, and approving in the maintainer request queue should not affect the edit queue.

**Operating system and browser version**
Firefox / Ubuntu

**Comment by knirirr** [comment]
I am unable to reproduce this; in step 6 I find that the record has not been approved.
There is no mechanism in the code that I can see which would produce the symptoms described.
