### ISSUE TITLE
Maintained collections display persistent "maintenance request approved" message

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1457]
**Describe the bug**
In the particular build produced by #1449, whenever I view a collection record that I am maintainer of, I get the "maintaining request approved" banner, even though I claimed the record weeks ago

**To Reproduce**
1. Log on as allysonlister
2. visit https://deploy-preview-1449--fairsharing.netlify.app/3519
3. See error

**Expected behavior**
Banner should only be there for a predefined time after approval.

**Screenshots**
![maintain](https://user-images.githubusercontent.com/143586/148775814-9fce74e5-0012-4f17-8140-7a89f25e05fa.png)

**Operating system and browser version**
Ubuntu / Firefox

**Additional context**
Does not happen on production site.

**Comment by allysonlister** [comment]
Weirdly, this is now also happening for beta.fairsharing org. I'm sure that wasn't the case before... Anyway, https://beta.fairsharing.org/3519 also shows the same issue.

It happens for any record I am the maintainer of.

**Comment by knirirr** [comment]
This is related to https://github.com/FAIRsharing/fairsharing.github.io/issues/1425.

**Comment by hoseinmirian** [comment]
@allysonlister what time length is good for the banner to stay do you think? I recommend 2 days max.

**Comment by allysonlister** [comment]
Yes, 48 hours / 2 days maximum sounds great, thanks.

**Comment by hoseinmirian** [comment]
@allysonlister also I can make the red banner disappear at the same time if you like?
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/25683981/148986431-6eec1879-5294-4097-a835-8268ad94c7e3.png">

should I ?

**Comment by allysonlister** [comment]
Yes please, that has also appeared suddenly... Thanks!
