### ISSUE TITLE
Legacy 404 (etc.) images

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#1458]
@SusannaSansone has requested that 404, 500 etc. messages from the old system be used in the new one as well. I've copied these images to the graphics repo: https://github.com/FAIRsharing/FAIRsharingGraphics/commit/264b5d3d4bf45b72634b7592f442c223cbda2ea8

**Comment by hoseinmirian** [comment]
@knirirr for 404 we have a route and for maintenance I put 500 image which is the same as 503. sounds ok?
401 is unauthorized which we already have addressed it by redirecting users to Login.

**Comment by knirirr** [comment]
That reminds me that I am not entirely happy with the system showing that there is maintenance in progress when there is in fact a failure of the API. If it fails then a 500 is appropriate (and no mention should be made of maintenance), but if it legitimately returns maintenance headers then a 500 should not be shown.
