### ISSUE TITLE
Add fairshairing record's logo 

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#1470]
if fairsharing record has a logo, it should be shown in the record display next to name.

**Comment by hoseinmirian** [comment]
@allysonlister please let me know which is the best place to show it. tnx

**Comment by knirirr** [comment]
> @allysonlister please let me know which is the best place to show it. tnx

The answer is here:

https://github.com/FAIRsharing/fairsharing.github.io/issues/1332#issuecomment-970306290

> When there is a logo, move the name to the right slightly and place the logo next to it.
