### ISSUE TITLE
Header search box adds to existing search results rather than clearing them

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1475]
**Describe the bug**
While the search box that is at the top of the search facets in the left-hand menu of https://beta.fairsharing.org/search should add the user's term to the existing set search terms, this is not true for the search box in the header. This box should always clear any existing searches and start afresh with whatever the user typed into it.

**To Reproduce**
1. Go to https://beta.fairsharing.org/search
2. Add any search term or facet (I used "recommended")
3. type a different search term into the search box in the header
4. Search term is appended instead of replacing existing ones. 

**Expected behavior**
The header search box should always start a new search.

**Screenshots**
![additive](https://user-images.githubusercontent.com/143586/149949833-1f753d5b-7c4a-447e-87f5-105b4ac38fd6.gif)

**Operating system and browser version**
Ubuntu / Firefox

**Comment by knirirr** [comment]
Previous PRs/tickets indicate that the search boxes are the same component. There's a modification to it at https://github.com/FAIRsharing/fairsharing.github.io/pull/1343/files relating to a previous request for behaviour change at https://github.com/FAIRsharing/fairsharing.github.io/issues/1237.

This probably means passing a prop to the component depending on where it is used.
