### ISSUE TITLE
General Information edit system returning empty fields for abbreviation to the server

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/fairsharing.github.io#1478]
When editing a record the PUT command sent by the GeneralInformation section returns empty strings ""  for the field Abbreviation if there is not a value (it is possible that it also happens in other fields but not sure). It should be nil or not returning anything in the field as it is not mandatory.

**Comment by knirirr** [comment]
I've dealt with this server side as, after looking at it, I thought that a simpler solution.
