### ISSUE TITLE
Updates to Record Reviews

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1483]
* A new, additional "OK & Reviewed" option when the green tick is clicked in the approval queue on the dashboard, making the full option list Cancel, OK, OK & keep hidden, OK & Reviewed. [The curator dashboard's approval button should no longer transmit create_review when approving a record unless the last option is selected].
   * All records should display a last curation review date to curators in whatever way the devs would like.

This relates to https://github.com/FAIRsharing/FAIRsharing-API/issues/423

**Comment by knirirr** [comment]
@allysonlister please would you specify what you would like to be done with creating reviews in relation to hidden records. Should "OK & Review" reveal hidden records or leave them hidden?

**Comment by allysonlister** [comment]
How did I miss this? You are right, I should check the ones that are both in the Awaiting response and assigned to me regularly. My apologies! Thank you for flagging it for me.

Yes this is becoming slightly clunky, quite a few options now. Is it possible to have a toggle in the confirmation dialog? If so, we could just have:

Cancel, OK, OK & Reviewed

and on a separate line, a toggle that defaults to a "make public" value, with the other value being "keep hidden"?

Can you think of a more elegant solution? Open to ideas! Thanks!

**Comment by knirirr** [comment]
> Can you think of a more elegant solution? 

Not at this stage, I'm afraid. ;-)
