### ISSUE TITLE
Password reset form resets on Enter key

### ISSUE THREAD

**Issue by stain** [FAIRsharing/fairsharing.github.io#1485]
**Describe the bug**
On https://beta.fairsharing.org/accounts/forgotPassword clicking Enter resets the form rather than requesting a password reset.

**To Reproduce**
1. In https://beta.fairsharing.org/accounts/forgotPassword?
2. Fill in email address
3. From the email field, Push the Enter button rather than click the button
4. The page refreshes without any notification if the password was reset or not.

**Expected behavior**
Enter should work the same as clicking the "Request New Password" button.

**Operating system and browser version**
Win 11 - Firefox 96.0.2 (64bits)

**Comment by terazus** [comment]
This issue should be fixed after review of https://github.com/FAIRsharing/fairsharing.github.io/pull/1496
