### ISSUE TITLE
Logging in with ORCID goes back to login page

### ISSUE THREAD

**Issue by stain** [FAIRsharing/fairsharing.github.io#1486]
**Describe the bug**

**To Reproduce**

1. Clicking Log in with ORCID, from front page or https://beta.fairsharing.org/accounts/login 
2. After signing in with ORCID 0000-0001-9842-9718 it redirects correctly (?) back to https://beta.fairsharing.org/loginSuccess?1239812398
3. Thge The browser is redirected back to https://beta.fairsharing.org/accounts/login asking to log in again
4. No error message shown.

**Expected behavior**

Either to be logged in or asked to register if the account didn't have ORCID.

My account, when logged in with email/password, already have orcid 0000-0001-9842-9718 noted.

**Operating system and browser version**
Win 11 - Firefox 96

**Comment by knirirr** [comment]
Unfortunately I'm not able to reproduce this; all ORCID logins in production development are without issue. 

Are you sure that 

https://beta.fairsharing.org/loginSuccess?1239812398 

is the URL that was called when you attempted to login? It should look like this one: 

https://beta.fairsharing.org/login_success?jwt=long_number_here&expiry=shorter_number

To investigate further I have added more logging code to the server. Please would you logging in with ORCID again and email us (contact@fairsharing.org) with the results - thanks.

**Comment by stain** [comment]
Confirmed this works now after moving to https://fairsharing.org/
