### ISSUE TITLE
Import publication from DOI spins forever

### ISSUE THREAD

**Issue by stain** [FAIRsharing/fairsharing.github.io#1487]
**Describe the bug**
When clicjing Import DOI the button never stops spinning

**To Reproduce**
1. Edit a record like https://beta.fairsharing.org/1442/edit
2. Under Publications, click "Import from DOI" button.
3. The button - and for some reason the two next to it - just spins forever.

**Expected behavior**

Some kind of pop-up or form to supply DOI.

**Screenshots**
![image](https://user-images.githubusercontent.com/253413/151341684-3a25ed5e-5ec0-40a9-8d11-6e8fecf95e81.png)

**Operating system and browser version**
Win 11 - Firefox 96.0.2

**Comment by stain** [comment]
If I try again after ctrl-shift-R reload, then this time the DOI button responds, but says the DOI is not found.  I have not been presented any form field of where to fill in the DOI, though..

![image](https://user-images.githubusercontent.com/253413/151346145-c1894c87-9e2a-45a8-a226-e5d20e217f86.png)

**Comment by knirirr** [comment]
If I trigger the DOI import with an empty search field, I get the DOI not found after a moment. This, plus your result after refreshing the page, suggests that the hang you experienced was a transient issue i.e. the connection to the server performing the search was hanging.
If you paste DOI into the search box then the record will be imported:
<img width="786" alt="Screenshot 2022-01-27 at 14 07 24" src="https://user-images.githubusercontent.com/3583375/151374776-0188a5de-4e18-44b4-8e8c-3118eb8a7d92.png">

**Comment by stain** [comment]
I am still not understanding where to put in a DOI.

![image](https://user-images.githubusercontent.com/253413/152327537-b3e7d8be-e54c-4b8e-98af-30e3f00717eb.png)

**Comment by knirirr** [comment]
It should go where you see the words "search existing publications", as per my example above.
