### ISSUE TITLE
Creating new funding organization, spins forever

### ISSUE THREAD

**Issue by stain** [FAIRsharing/fairsharing.github.io#1488]
**Describe the bug**

Adding new funding organization does not complete.

**To Reproduce**
1. Edit the funding relations of an entry
2. Click to add a new organization, e.g. "European Commission Horizon Europe" <https://ec.europa.eu/info/research-and-innovation/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe_en> (Government Body)
3. Leave "Countries" blank (I am not going to select all 27 EU countries + third-party countries)
3. Click Save
4. The green button just spins forever without completing.

**Expected behavior**
Either adding the organization or error message of why it could not be added.

**Screenshots**
![image](https://user-images.githubusercontent.com/253413/151347394-0a909749-0c1c-4079-a85a-72bccfd2cbdf.png)

**Operating system and browser version**
Windows 11 - Firefox 96

**Comment by stain** [comment]
Weirder still is if I click Cancel and then re-enter the New Organization dialogue, the green button is spinning before I even have filled in anything.

**Comment by knirirr** [comment]
I was able to create this organisation successfully on our test systems, using the same code that's running in production.
Therefore, as with #1487, I suspect network issues on your side.

Please note also that we have supplied "European Union" in the list of available countries to avoid the need to enter them all separately.

**Comment by stain** [comment]
Now I am able to create Horizon Europe as organization, but not the corresponding grant.

![image](https://user-images.githubusercontent.com/253413/152328966-81a9158e-8587-408b-a3ca-03ad053688c8.png)

**Comment by knirirr** [comment]
I've made some changes to permissions. Please would you try again and let us know if there's still a problem.
