### ISSUE TITLE
Publication for Citation has been truncated

### ISSUE THREAD

**Issue by stain** [FAIRsharing/fairsharing.github.io#1489]
**Describe the bug**
The "Publication for citation" box of an entry is truncated. It also seem to somewhat duplicate the publication listing further down.

**To Reproduce**
1. https://beta.fairsharing.org/1442
2. Scroll down to "Publication for citation" next to "How to cite this record"
3. Publication text is truncated within author list, and does not show title, journal nor DOI.

**Expected behavior**
The publication should be shown in full. If the author list is long, perhaps it can be shortened, but the title, doi and journal should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/253413/151348829-c51d742a-ed2c-4bff-a4d2-840d44e1b396.png)

**Operating system and browser version**
Win 11 - Firefox 96

**Additional context**

**Comment by knirirr** [comment]
We'll have a think on the specification for this one.

**Comment by allysonlister** [comment]
Thank you Stian! Just a note that there is deliberate duplication between "Publication for Citation" and all of the publications listed at the bottom of the record. Records may have multiple publications, and then one of these publications is marked as the one to cite. That one is then also "promoted" up the page to display prominently in the General Information card as well as in the full publication list.

As for the display of the publication when in the "publication for citation" area of the General Information card I agree that there is space for more to be shown, and therefore we should show more.

@knirirr as @stain suggested please could we always show the full title, year and DOI? Then please could we show the authors up until a length that is sensible for the box size? Please note that the DOI is not currently included within this box and will therefore need to be an addition.

If no DOI exists, show PubMed ID link. If no PubMed link, show the manual link. If no links, show nothing.
