### ISSUE TITLE
List of organisations in collections should link to organisation page

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1503]
This wasn't provided in the original gitbook spec, but has been added now, my apologies.

Example: https://beta.fairsharing.org/3513

The organisation list in collections should link in the same way such organisations work in all other record types; namely, they should link to the FAIRsharing organisation page. Right now they are linking to the organisation's homepage.

Thanks!

**Comment by knirirr** [comment]
This will appear in production next time there's a merge to master.
