### ISSUE TITLE
beta url visible in citation for FAIRsharing records

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1507]
**Describe the bug**
Should not have beta in the URL for citation

**To Reproduce**
1. Go to any record e.g. https://fairsharing.org/3521
2. See error

**Expected behavior**
The URL displayed should be for the main fairsharing.org site.

**Screenshots**
https://fairsharing.org/3521
![beta](https://user-images.githubusercontent.com/143586/152200376-ca60d0b3-f88f-45a9-a661-fd6aa90fa253.png)

**Operating system and browser version**
Ubuntu / Firefox

**Comment by knirirr** [comment]
This particular URL is controlled by an environmental variable on the server, which I have changed. I've changed some other hard-coded URLs as well, which will eventually appear on the site.
