### ISSUE TITLE
Please add a "back to record" link/button from the graph pages

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1519]
From a user (thanks!):

Please could we have a “back to record” link or button from a relation graph? This would be helpful when navigating from one record to another through the graph.

This "back to record" link would go to the record that corresponds to the graph, and not e.g. to the record that the user started navigating from if they have since clicked through several graph nodes.

Of course, you can work around it by deleting  «/graph» from the URL (e.g., https://fairsharing.org/graph/2110 > https://fairsharing.org/2110). But there’s no connection between that syntax and the record’s DOI or site URL (in the example above: https://doi.org/10.25504/FAIRsharing.cnwx8c and https://fairsharing.org/FAIRsharing.cnwx8c).

**Comment by hoseinmirian** [comment]
@allysonlister as far as I know its been implemented in the dev branch now cz I accidentally bumped into it and seemed to be done. please correct me if I am wrong.

**Comment by knirirr** [comment]
Clicking the central node of the graph returns to the record. If anything further than that is still needed then it would be an easy task for @hoseinmirian.
