### ISSUE TITLE
Two records with multiple relationships don't have any connection in the graph displayed

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1524]
**Describe the bug**
Although the relationships are correctly shown in the record views (see screenshot below of the record view), they are NOT being displayed in the graph (see screenshot of OBIS graph). We have had some issues with overlaid relationships when two resources have multiple relationship types, and it might be that this issue is cropping up again in a slightly different way. 

Is this an issue that is simply to do with how long it takes for the graph to be redrawn? Is it nightly? If this is true, then the rest of the ticket may be invalid.

**To Reproduce**

GO TO PREVIEW SO AS NOT TO DISRUPT CURATION PLEASE :)

1. Both of these workthroughs are using the equivalent records on preview (https://preview.fairsharing.org/2294 and https://preview.fairsharing.org/2163) 
2. examine graphs as required.

**Expected behavior**
All relationships should be displayed. I know in the past, multiple relationships between two resources are just overlaid, and if that must happen until we re-implement the graph library, please tell me so. Perhaps @terazus might know if there is a way in the current graph library to allow >1 relationship to be displayed between two resources.

**Screenshots**
Proof of me adding two relationships to the GBIF record on preview:
![obis](https://user-images.githubusercontent.com/143586/153447418-8e399559-0c54-4712-bd29-003314e665ff.gif)

Proof that both relationships are properly saved:
![obis2](https://user-images.githubusercontent.com/143586/153447402-fbb94372-2ab3-494d-94b4-d75e80cee4fa.png)

Proof that no relationship between OBIS and GBIF is present in the OBIS graph:
![no-gbif](https://user-images.githubusercontent.com/143586/153447395-36573a9d-b9b2-4068-922d-76b76a980d6f.png)

Proof that no relationship between OBIS and GBIF is present in the GBIF graph:
![gbif-graph](https://user-images.githubusercontent.com/143586/153447751-bac9c4c8-74d6-413e-b84a-b9dce370795a.png)

**Operating system and browser version**
Ubuntu / Firefox

**Comment by knirirr** [comment]
> Is this an issue that is simply to do with how long it takes for the graph to be redrawn? 

Yes.

> Is it nightly?

No, it is supposed to be within minutes of making the change. 

I can see a relationship between OBIS and GBIF on https://fairsharing.org/graph/2163 but not the reverse relationship on https://fairsharing.org/graph/2294. Which of these records did you edit, and did you only edit relationships or something else? 

Meanwhile, I can manually trigger a recalculation of the graph, if required.

**Comment by allysonlister** [comment]
_The situation in preview_

Remember that I'm working in preview - what was done on the production server was performed by one of our curators, and I can't control exactly what is shown there. 

On preview, I added related_to and shares_data_with to GBIF; both from GBIF to OBIS.

Thanks for letting me know about the frequency of graph updates. On preview, the link between the two records is visible in both graphs, but only the **related to** link, and not **shares_data_with**. I suspect this is going to be an issue until we update the graphs, as at the moment they can only show one of the relationships, correct?

_the situation in production_

Our user currently has one **related_to** relation in the GBIF (2163) record pointing to OBIS (2294). I concur with your assessment - I can see the relationship in the GBIF record, but not in the OBIS record - I should be able to see both.

**Comment by knirirr** [comment]
I am aware of the difference between preview and production here.
What has happened is that the background job to re-draw the graph has failed. Looking at the production system suggests that an invalid record association has been saved; the presence of this invalid association blocks saving of the record and thereby prevents graph regeneration. This association is:

"Ocean Biodiversity Information System"  (2294) implements  "World Register of Marine Species" (1120) => "This type of association is not allowed between these records"

How this came about is unknown; I'd guess at modification of the data by a script (e.g. during data migration) but can't be sure. 
Anyway, I've changed this to "related_to" which will fix everything again.
