### ISSUE TITLE
Searching for relationships in a record view only returns one of them, not all

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1525]
**Describe the bug**
our relationship search within our record view, shown at the end of the animation, only displays one of the two relationships that were added. However, if you manually scroll (see screenshot below), both relationships are present.

**To Reproduce**
1. Go to https://preview.fairsharing.org/2163 and https://preview.fairsharing.org/2294
2. note error when searching database relationships

**Expected behavior**
using the search box to filter database relationships (and other relationships too!) should return all relationships between the two resources and not just one of them

**Screenshots**
both relationships are present in both records (to each other)
![obis2](https://user-images.githubusercontent.com/143586/153449623-5c76cd2e-6e5b-4877-8743-5b9210f21fe1.png)

but only 1 is shown in the search
![only1](https://user-images.githubusercontent.com/143586/153449786-b510a9c0-3764-4c13-bf4b-0c951f929b14.png)

**Operating system and browser version**
Firefox / ubuntu

**Comment by knirirr** [comment]
In your example, on record 2294, the search for "Global Biodiversity Information Facility" brings up one hit. But, there's only one link to that record to find. So, I am not sure what is going on 
If you mean instead to search for "ocean biodiversity" and have both records whose names contain that string show up then that won't happen; though both can be found, the drop-down is an autocomplete and will only ever show one result when that is selected.

**Comment by allysonlister** [comment]
Apologies for my lack of clarity - I see I chose screenshots from two different records, making it hard for others to understand what I meant. Here's a gif showing the GBIF record. It has two relationships to OBIS (different relation types) but only one appears when you search the database relationships:
![obis-in-gbif](https://user-images.githubusercontent.com/143586/153947133-4602fb28-44ec-4035-a51a-2620d97af460.gif)
Does this make more sense? Thanks!
