### ISSUE TITLE
Cannot delete a "related_to" relationship

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1530]
**Describe the bug**
I try to delete "related_to", seems to work, but then does not delete

**To Reproduce**
1. Go to https://fairsharing.org/3803
2. Edit record, go to Relations and other records
3. delete the "related_to" relationship and "save and exit"
4. See error - the related_to relationship is still there

**Expected behavior**
Relations I delete should be deleted.

**Screenshots**
![does-not-delete](https://user-images.githubusercontent.com/143586/153835602-06d945a3-305a-44bd-8b60-ced28fd2d070.gif)

**Operating system and browser version**
Ubuntu / Firefox

**Comment by knirirr** [comment]
As far as I'm aware this problem has been dealt with. The ticket can be re-opened if this specific issue recurs.
