### ISSUE TITLE
Enhancement: Add Content page (Delph suggestions)

### ISSUE THREAD

**Issue by delphinedauga** [FAIRsharing/fairsharing.github.io#1545]
This ticket is about new suggestions for the "add content" page : https://fairsharing.org/new

Thanks a lot Hossein for the new page, what you have done is much clearer :)

I have a few suggestions to make it perfect. This page is very important for us because we lose a lot of time rejecting submissions that are datasets and explaining to the users why we reject their submission:

- **Header** 
Why not put the same header as all the other pages to make the website more consistent? 
<img width="1367" alt="Capture d’écran 2022-02-17 à 17 41 13" src="https://user-images.githubusercontent.com/59688426/154528525-7ff4f903-ff4d-4a7a-9315-fe2aab9014b1.png">

- **Columns** 
I saw that on the home page, you used this formalism for columns, with a nice effect when you move the mouse over it. Maybe we can use it again? 
<img width="1235" alt="Capture d’écran 2022-02-17 à 17 44 19" src="https://user-images.githubusercontent.com/59688426/154529158-cdefb871-a019-404a-a210-e9b0adb65184.png">

Is it possible to arrange the columns differently? 
Here are 3 suggestions, tell me what you think, I prefer the 1st proposal.
* 4 columns on 1 line
<img width="1335" alt="Capture d’écran 2022-02-17 à 17 46 49" src="https://user-images.githubusercontent.com/59688426/154529633-56c66bc8-074a-471a-9fd7-96f7fd0f0cff.png">

* 3 columns on 1 line / 1 column on another line (central)
<img width="655" alt="Capture d’écran 2022-02-17 à 17 47 20" src="https://user-images.githubusercontent.com/59688426/154534599-e719b4fa-bce0-4c59-a3e2-80d1ef4ecff9.png">

* 2 columns on 1 line / 2 column on another line 
<img width="605" alt="Capture d’écran 2022-02-17 à 17 48 06" src="https://user-images.githubusercontent.com/59688426/154529884-7cb2e17a-7f37-44d9-8e76-e131e4606de5.png">

Is it possible to remove the "justify" for the text under standard, database, collection and policy ? maybe center will be better ? 

**- Size of the titles**
It seems that the titles "What to add" ; "No datasets, please" ; "Get Started!" have not the same size (+ 1 is in bold). I think that those titles should use the same css (h2?).

**- Colours** 
This one is difficult... I'm sorry, I gave you the wrong colour for the "please no dataset" box when I gave you my drawing, I did it quickly on ppt, I didn't have the graphic palette available. I think that this box should take a colour from the graphic palette. Maybe the red or the orange? I'll let you choose, you're the expert! 
Same for the blue box, it's a little bit aggressive, I would put a light grey. You can try to make a band, 
Not sure it's necessary to highlight some text in blue. Maybe just in bold, or the color used for the links in the css is sufficient.

It might look something like this :
<img width="341" alt="Capture d’écran 2022-02-17 à 18 05 30" src="https://user-images.githubusercontent.com/59688426/154533289-f9ee55dd-aac2-4580-aeba-a12f2a5f6f2e.png">

What do you think of it ?

**Comment by hoseinmirian** [comment]
@delphinedauga thanks for sending the updates. Please always make sure if there is a long text, copy past it here as the banner headline and subtitle whilst I have only an image. thanks. 

in regard to card order it is by default as your first proposal when the screen is wide enough but when the screen gets narrower it becomes gradually like your 3rd option, so there is nothing I can do here cz there are technical fact and limit in a web browser screens.
