### ISSUE TITLE
Avast antivirus false positive for FAIRsharing.org

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1567]
There appears to be some kind of setup of our production server that means people using AVAST are getting this message when they try to visit us:
![Screen Shot 2022-03-02 at 9 21 39 AM](https://user-images.githubusercontent.com/143586/156390724-1db26883-5037-4298-8986-4d4f618dc620.png)

That's all the information I have at present, but the user is happy to answer any follow up questions. 

Thanks!

**Comment by knirirr** [comment]
A false positive report has been submitted to Avast. 

Please note: https://sitecheck.sucuri.net/results/fairsharing.org/new

**Comment by knirirr** [comment]
I'll close this now as Avast claim to have dealt with the problem and I'm not expecting any further communication from users.
