### ISSUE TITLE
Page hangs when creating an organisation without a country

### ISSUE THREAD

**Issue by delphinedauga** [FAIRsharing/fairsharing.github.io#1571]
**Describe the bug**
When creating a new organisation without entering a country, the page hangs. 

**To Reproduce**
1. Go to a record edit page
2. Go to the 'Edit Organisations & Grants' section
3. Click on 'Add a new relationship'
4. Click on the "new add" button
5. Enter 'Organisation Name' ; 'Organisation Homepage' 
6. Select the 'Organisation type'
7. Click on the 'Save new organisation' button
8. See error
9. When you cancel, and click again to the "new add" button, the error is still there.

**Expected behavior**
As the country is mandatory, I expect an error message saying "Country field is mandatory"

**Screenshots**
![Mar-04-2022 12-59-39](https://user-images.githubusercontent.com/59688426/156759930-92acb8bc-c974-463d-98b0-86d838f235ac.gif)

**Operating system and browser version**
MacOS Big Sur V11.0.1 - Chrome Version 98.0.4758.109 (Build officiel) (x86_64)

**Comment by knirirr** [comment]
The country field isn't currently mandatory. In this case I'll deal directly with the organisation submission bug and will save any modification of the validation rules for #1572.
