### ISSUE TITLE
Relationships to Collections should only be displayed IN COLLECTIONS section

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1579]
**Describe the bug**
 I just noted that https://fairsharing.org/FAIRsharing.w4bthd has the Chemistry collection in both "OTHER RELATED RECORD(S)" and "IN COLLECTIONS". 

**To Reproduce**
1. Go to https://fairsharing.org/FAIRsharing.w4bthd
2. See presence of "chemistry" in both sections (as screenshot). 

**Expected behavior**
All collects relationships should only be present in IN COLLECTIONS

**Screenshots**
![collections-and-others](https://user-images.githubusercontent.com/143586/157240643-5fe7d723-961d-4748-9ef6-c5ec087fd987.png)

**Operating system and browser version**
Firefox / Ubuntu

**Comment by knirirr** [comment]
This one appears to be a side-effect of https://github.com/FAIRsharing/fairsharing.github.io/issues/1525.
