### ISSUE TITLE
relationships to policies should only be displayed in the IN POLICIES section

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1580]
**Describe the bug**
Policies that are "in" other policies are currently displayed within OTHER RELATED RECORDS, when they should be shown in IN POLICIES.

**To Reproduce**
1. Go to https://fairsharing.org/FAIRsharing.w4bthd
2. See screenshot for example of policies found in related records section.

**Expected behavior**

Let's take as examples the following:
1. PeptideAtlas https://fairsharing.org/1927
2. Springer Nature - Research Data Policies https://fairsharing.org/3350
3. Springer Nature Research Data Policy Type 3 - https://fairsharing.org/3426

IN POLICIES should contain:
* **only for database and standards records**: any "recommends" relationships that record is a part of (e.g. "Springer Nature - Research Data Policies" recommends PeptideAtlas") - this is already happening, and is correct. I've included it here for completeness.
* **only for policy records**: any "extends" relationships that policy is a part of, e.g. _Springer Nature Research Data Policy Type 3_ extends _Springer Nature - Research Data Policies_ should be visible within the  _Springer Nature - Research Data Policies_ IN POLICIES section.

Please note that this ticket does not relate to the "related to" relationship that exists between all record types including policies (you can see "related to" between two policies if you look at this example https://fairsharing.org/FAIRsharing.tsp58); no changes need to be made to this relationship type.

**Screenshots**
![collections-and-others](https://user-images.githubusercontent.com/143586/157243986-352714b6-013b-4aba-92a9-da9f992356c3.png)

**Operating system and browser version**
Firefox / Ubuntu

**Comment by knirirr** [comment]
This is not strictly a specification change (AFAICT there isn't a specification ;-) but it is a change in the previous behaviour, unlike https://github.com/FAIRsharing/fairsharing.github.io/issues/1579 which is in fact a bug caused as a side effect of changing something else (https://github.com/FAIRsharing/fairsharing.github.io/issues/1525).

I can attempt to make the change requested above and will include this in one PR with https://github.com/FAIRsharing/fairsharing.github.io/issues/1579. This will not be a trivial change as it incorporates special behaviour for some registries compared with others. 

It would be useful if curators, when they have time, were to write down on Gitbook exactly what they expect to see where in these two display elements for future reference; this ticket might be overlooked in future, as might the various others involved in the development of this part of the application.

**Comment by knirirr** [comment]
This is now obsolete as further discussions will take place to re-design the relations display, so I'll close it.
