### ISSUE TITLE
Updates to IN POLICIES section of record view

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1584]
As a result of #1583, I've now realised that the display of relationships involving policies is split between IN POLICIES and OTHER RELATED RECORDS. To resolve this, we should update how such relations are shown as follows:

1. Change the label of IN POLICIES to POLICY RELATIONS
2. All relationships to policies will go here. Explicitly listing them, that would mean:
   * policy _extends_ policy
   * policy _recommends_ database/standard
   * policy _deprecates_ policy
   * policy _extends_ policy
   * policy _related to_ policy
4. OTHER RELATED RECORDS might now be unnecessary - please can you confirm if any relations would be displayed there now?

@delphinedauga do you have any comments on this?

**Comment by knirirr** [comment]
This is not impossible but is a little involved.
As this will mean the labels for the Collections and RelatedContent components (which perhaps ought to be re-named as a consequence) will no longer be correct, how do you want to change those?

<img width="394" alt="Screenshot 2022-03-09 at 16 10 55" src="https://user-images.githubusercontent.com/3583375/157481837-628064df-21cf-4f2c-8494-50578b6f6139.png"> 

...now contains things that are not collections related via relations that are not recommendations, and will contain even more if this change is implemented. 

<img width="394" alt="Screenshot 2022-03-09 at 16 12 21" src="https://user-images.githubusercontent.com/3583375/157482443-4f970413-55c6-4e87-b1a6-c10a35d4ccf8.png">

...contains only some of the related content. 

> please can you confirm if any relations would be displayed there now?

I cannot, though I don't think they will be, unless the RelatedContent component is re-enabled on Record pages when displaying collections.

**Comment by allysonlister** [comment]
OK - I'll look at this tomorrow, and get back to you. Thanks for pointing this out!

**Comment by delphinedauga** [comment]
A comment for "policy recommends database/standard" relation: 
e.g. "Springer Nature - Research Data Policies recommends Peptida Atlas"
- On the "Springer Nature - Research Data Policies" record: the relation should appear on the "related database" section
- On the "Peptide Atlas" record: the relation should appear on "related database" section on the "in policies" section

That's what you were thinking ?

**Comment by allysonlister** [comment]
That's not quite it... I think you and I might need a chat at some point today - I'll message you Delphine. Thanks!

**Comment by allysonlister** [comment]
OK, @knirirr I have spoken both with Delphine and Susanna. What has come from this discussion is that the specification I have written above, due to your comments and Delphine's, has now become a second choice for how to proceed. Would you like me to write up Susanna's preferred option here, talk about it with you in a call, or in a new ticket perhaps? 

Thanks!

**Comment by knirirr** [comment]
What I'd really like here is to clear out all current tickets relating to relationship display, then for you write up a specification based on your discussion with Susanna (Gitbook would be suitable, or a Google doc if you prefer) which can be used for future reference and the basis of a ticket to re-write the feature.

**Comment by allysonlister** [comment]
OK I think I can do this. I think it might be best to write it up here: https://fairsharing.gitbook.io/fairsharing/associated-records

I know its public facing, but I can write it in a manner that makes sense for users, too, and then I only need to keep it maintained in one location. Does that sound feasible to you? Then I can make a new ticket that references the gitbook pages.

**Comment by knirirr** [comment]
Yes, sounds fine, thanks. 

It would, in any case, be useful for users to have a clear explanation of what they should find there.

**Comment by allysonlister** [comment]
Please see all of the new "Display locations" columns in the relations tables starting from https://fairsharing.gitbook.io/fairsharing/associated-records/from-standards-records

Let me know if any information is unclear or incomplete (both @knirirr and @delphinedauga). Thank you!

**Comment by allysonlister** [comment]
The result of the information presented in gitbook means that the two relations tables will have two tabs each, which will look nicely symmetric... These tabs will be as follows:

RELATED POLICIES tab should be shown in the same place as the current IN POLICIES tab. This means that for policy records, the IN POLICIES tab is not present, while in all other record types the RELATED POLICIES tab is not present.

I believe this also means that OTHER RELATED RECORDS can disappear, as no relations would be in that section.

Thanks!
