### ISSUE TITLE
Set up Google search console

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/fairsharing.github.io#160]
if possible, may need SSR

**Comment by terazus** [comment]
Also setup google analytics.
=> https://github.com/MatteoGabriele/vue-gtag

**Comment by terazus** [comment]
another useful link: https://medium.com/js-dojo/how-to-use-google-analytics-in-your-vue-app-with-vue-analytics-9cdb913301d1

**Comment by knirirr** [comment]
Google analytics appears to be working for the Beta URL.
I've enabled it for the main https://fairsharing.org URL now.
Prerender.io is working so we'll have cached, pre-rendered HTML for Google's crawlers.

**Comment by knirirr** [comment]
I've added search console verification to the DNS records so I can set up the search console for the fairsharing@fairsharing.org paid Google account. Once verification is complete (Easily's settings will take a while to propagate) I'll close this.

Perhaps it will assist in diagnosing https://github.com/FAIRsharing/fairsharing.github.io/issues/1608

**Comment by knirirr** [comment]
Done! 
Now available at https://search.google.com/search-console?resource_id=sc-domain%3Afairsharing.org if logged in as fairsharing@fairsharing.org.
