### ISSUE TITLE
Google search ranking oddities

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1608]
I searched for "fairsharing dryad" in both google and in ecosia. Google has a very poor response - is this related to our prerendering service? 
![fsdryad](https://user-images.githubusercontent.com/143586/159752405-28acc7f1-65a0-4674-8aa2-ab35b08a8246.png)

Ecosia seems to deal with the search exactly as I would expect, however @knirirr points out that it seems to have information from our previous version of the website, so that might also have room for improvement:
![fsdryad-ecosia](https://user-images.githubusercontent.com/143586/159752424-60b27fac-6f56-45d5-92ff-d9c8e5f614b5.png)

**Comment by knirirr** [comment]
I think that Google's search index has finally caught up:
<img width="865" alt="Screenshot 2022-07-13 at 13 31 20" src="https://user-images.githubusercontent.com/3583375/178734091-8cbe2ece-7cbe-4423-89fb-b1405fd019df.png">
