### ISSUE TITLE
Additional switch for user profile editing

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#1611]
See this document for context: 

https://app.gitbook.com/o/-MchtBAOWXh2gO--zz7m/s/-MkSKpWh9NA-iywIqhP_/please-can-we/pushing-attribution-to-orcid#specification-in-fairsharing

> When editing a profile: Toggle to be added (default yes if the user has provided their ORCID ID, and automatically flips to yes if an ORCID ID is added at a later date) called "allow the crediting of my FAIRsharing curation to my ORCID profile".

**Comment by prakhyatox** [comment]
Already completed
