### ISSUE TITLE
Cannot approve a specific record

### ISSUE THREAD

**Issue by delphinedauga** [FAIRsharing/fairsharing.github.io#1621]
**Describe the bug**
I get an error message when I want to approve the 'NERC Vocabulary Server' record from the curation dashboard.

**To Reproduce**
1. Go to 'https://fairsharing.org/curator'
2. Search for the 'NERC Vocabulary Server' record
3. Click on approve

**Expected behavior**
Record approval

**Screenshots**
![Mar-30-2022 16-30-15](https://user-images.githubusercontent.com/59688426/160859444-899e4262-0bf8-416f-957f-d0e1d9c8208f.gif)

<img width="1253" alt="Capture d’écran 2022-03-30 à 16 30 32" src="https://user-images.githubusercontent.com/59688426/160859968-a9184dec-053c-4d2d-b883-3e924dbd6775.png">

**Operating system and browser version**
macOS BigSur Version 11.0.1 - Chrome Version 99.0.4844.74 (Build officiel) (x86_64)

**Comment by knirirr** [comment]
Interesting. This is not a bug with the curation dashboard or the API; failing to save a record with an invalid association is what is supposed to happen. Here's the investigation:

```
2.7.5 :006 > r.record_associations.collect {|x| [x.id, x.valid?]}
 => [[7175, true], [7176, true], [7177, false], [7178, true], [7179, true], [7180, true], [7181, true], [7182, true]] 
2.7.5 :007 > a = RecordAssociation.find(7177)
 => #<RecordAssociation id: 7177, fairsharing_record_id: 2862, linked_record_id: 1120, created_at: "2021-09-30 09:19:24.366849000 +0000", updated_at: "2021-09-30 09:19:24.36684... 
2.7.5 :008 > a.inspect
 => "#<RecordAssociation id: 7177, fairsharing_record_id: 2862, linked_record_id: 1120, created_at: \"2021-09-30 09:19:24.366849000 +0000\", updated_at: \"2021-09-30 09:19:24.366849000 +0000\", record_assoc_label_id: 1>" 
2.7.5 :009 > a.validate
 => false 
2.7.5 :010 > a.errors.messages
 => {:relation=>["This type of association is not allowed between these records"]} 
2.7.5 :011 > label = RecordAssocLabel.find(1)
 => #<RecordAssocLabel id: 1, name: "implements", parent_id: nil, created_at: "2021-09-30 08:44:18.055749000 +0000", updated_at: "2021-09-30 08:44:18.055749000 +0000", descript... 
2.7.5 :012 > FairsharingRecord.find(2862).name
 => "NERC Vocabulary Server" 
2.7.5 :013 > FairsharingRecord.find(2862).registry
 => "Database" 
2.7.5 :014 > FairsharingRecord.find(1120).name
 => "World Register of Marine Species" 
2.7.5 :015 > FairsharingRecord.find(1120).registry
 => "Database" 
```

So, we have a database implementing another database, which is not permitted as implements can only apply from a database to a standard.

I cannot provide any explanation as to why this relation is present but would guess that it's from an earlier (and presumably then buggy) version of the editor, or the migration.

Meanwhile, please let me know if you would prefer me to delete this relation or change the label (I'd guess to "related_to").

**Comment by delphinedauga** [comment]
Well seen, thank you! I removed and re-created the good relation, so I closed this ticket :)
