### ISSUE TITLE
Zenodo DOI call

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#1639]
There's a ticket in the server repo. describing a request for the edit interface to also check Zenodo for publications, using a DOI provided by the user. 

https://github.com/FAIRsharing/FAIRsharing-API/issues/473

That's all handled client-side in the application. Specifically, here:

https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/lib/Client/ExternalClients.js

This file could be modified to trigger both queries. It may well be necessary to modify this part as well:

https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/components/Editor/EditPublications.vue#L428-L458

...in order to handle the returned values.

**Comment by ramGranell** [comment]
I think there are two possibilities to check:
1) looking directly for the DOI of the publication (performing a query to the DB over the DOI field) e.g. https://zenodo.org/search?page=1&size=20&q=doi:%20%2210.4122%5C%2Fdtu:229%22 
2) retrieving  the record using the Zenodo URL https://zenodo.org/record/3537300  

I suppose that we are looking for the first.

**Comment by knirirr** [comment]
Yes, it's the first of these.
