### ISSUE TITLE
Transform facets into autocomplete

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/fairsharing.github.io#165]
Tryed using facets but it's very hard. Transforming them into an autocomplete that displays both the name and number of item available (named aligned left, number of items aligned right).
Optional though.

**Comment by Drosophilic** [comment]
This is a low priority and may not be actioned at all. Users search via autocomplete, but browse via facets. We therefore may be better to work on the UX of the facets (e.g. limiting the number of entries that can be shown), rather than essentially removing the facet feature.
