### ISSUE TITLE
Display changes for access points/data processes

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#1653]
Please see https://github.com/FAIRsharing/FAIRsharing-API/issues/484 for details.

The editor doesn't appear to be affected by these schema changes so there will only be changes to the record page. Specifically, the following changes will be required:

- [ ] AdditionalInfo.view will need to exclude data_processes_and_conditions so they are no longer displayed there. Any exclusions for data_processes or access_points can be removed.
- [ ] Record.vue contains various components for displaying parts of the data; a new one is required for "data processes and conditions"

Details of the schema can be found at https://github.com/FAIRsharing/FAIRsharing-API/tree/master/lib/record_schemas - the data_processes_and_conditions fragment is the one of interest (it should be referenced only by databases).

**Comment by allysonlister** [comment]
Please see the additional specification I have written in relation to this after discussions with @prakhyatox at https://app.gitbook.com/o/-MchtBAOWXh2gO--zz7m/s/-MkSKpWh9NA-iywIqhP_/please-can-we/record-specific-specifications/update-additional-information-fields#display-in-record-view

**Comment by prakhyatox** [comment]
1) View of License and other data processes. Please confirm if this is appropriate

2) No icons are present currently for other data processes, like Licences

![image](https://user-images.githubusercontent.com/109139583/181043637-d020072e-c5f8-4e42-8831-c204088db411.png)

**Comment by allysonlister** [comment]
Thanks @prakhyatox - 

Just remember that I'm happy to have just two white cards in this below the grid, as it says in gitbook. There are two main sections to this new tab "Data Processes and Conditions":
1. A Grid of checkboxes to show whether each process is read, write, or read/write.
2. A List of all other information that is not related to a read/write data process. This list should be grouped into two white "cards": one for licences and certification, and one for everything else.

Therefore, in the mockup above, there should be one card with the current Licence icon that shows both Licences and Certification and Community Badges, and then everything else (that is marked in gitbook as "Card 2" in the Display section column) should be in the second white card. Right now however, data curation, data access and data preservation are each in their own white card. 

As for the icon, I am happy to have something that could signify something like a "list of conditions" or a "list of attributes" - so perhaps something that looks like a list? If it's hard to create such icons right now, please just re-use the licence icon for now.

And please note that, other than Licences, the display of these different conditions shown in the screenshot above is not yet correct. The display style and any notes on that style are shown in columns 3 and 4 on the gitbook page.

You also mentioned you weren't sure about Certification and Community Badges; I appreciate that most records don't have that information yet. If you want some **test data for your local system**, a good example of how it would be used would be to use the following values:

Name: Core Trust Seal
URL: https://www.coretrustseal.org/wp-content/uploads/2022/07/20220712-Kasetsart-University-Knowledge-Repository_final.pdf

Thanks!

**Comment by prakhyatox** [comment]
Did a change for combining the cards. Let me know if thats okay

![image](https://user-images.githubusercontent.com/109139583/181055589-3a2b664d-db0d-46af-aa78-30c297db0924.png)

**Comment by allysonlister** [comment]
This is looking good! That's a great start. I haven't seen how the Certification and Community Badges part would look, and you haven't incorporated the style requests in columns 3 and 4 on the gitbook page yet, but this is definitely correct in terms of the white "cards".

Thanks!

**Comment by prakhyatox** [comment]
Is this view okay?

<img width="772" alt="image" src="https://user-images.githubusercontent.com/109139583/181273244-9722b970-3011-4553-8635-85b84ca168e5.png">

**Comment by allysonlister** [comment]
This looks great! Now that we have some padding between the type (e.g. "Manual") and the notes (e.g. "Test Value"), I think we can drop the parentheses. I'll update gitbook accordingly. Thanks!

**Comment by allysonlister** [comment]
Oh, please can you show me how it would look if there was a 

* notes+ url combination (no "type")
* just one of the two or three options 
Thanks!

**Comment by prakhyatox** [comment]
Like we discussed, we are not showing url. And if its just notes then:

<img width="721" alt="image" src="https://user-images.githubusercontent.com/109139583/181276840-6ebd4bf7-43a4-476b-adef-791a0f59e461.png">

**Comment by allysonlister** [comment]
Thanks, just notes looks great.

We do need to show the URL if it is the only thing filled in. It's not likely that a user will only provide a URL and not notes or type/steps, but we do need to have the code in place to deal with it if that happens. Does that make sense?

**Comment by prakhyatox** [comment]
Then, I think it is better to show all four items with couple of options

1) In a single row including URLs, and if any of the 3 items(i.e name/type, URL, notes) is not in response then that field is not shown.
We should go with first comment https://github.com/FAIRsharing/fairsharing.github.io/issues/1653#issuecomment-1195679323
with less padding and spacing.


2) 
<img width="686" alt="image" src="https://user-images.githubusercontent.com/109139583/181296742-30093bcc-8368-4eac-b788-2dfb965c13d2.png">

**Comment by allysonlister** [comment]
Thanks @prakhyatox - I know we're iterating a bit here, but I think we're nearly there!

The URLs really should not be shown unless absolutely necessary. Therefore I have updated the gitbook documentation.

I think we need a single row, as you say, but with 3 columns, not 4. 
![dc](https://user-images.githubusercontent.com/143586/181458356-43c628d4-627d-4000-b848-89735d158abd.png)
Above is taken from gitbook

Because it will be very rare that the URL is present and not the type, I think this should be the best solution.

What do you think?

**Comment by prakhyatox** [comment]
> Thanks, just notes looks great.
> 
> We do need to show the URL if it is the only thing filled in. It's not likely that a user will only provide a URL and not notes or type/steps, but we do need to have the code in place to deal with it if that happens. Does that make sense?


1. As per the edit form this case where only URL is present cannot happen because when I tried save the field with just URL 

<img width="692" alt="image" src="https://user-images.githubusercontent.com/109139583/181474654-56a3767e-2f07-4b0a-990e-ca4845e1bc85.png">


It displays an error
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/109139583/181474755-fc4f3063-989a-4111-9587-8fcb0e32a940.png">

So I think we can rule out this scenario


2. It seems type is also mandatory field, since it is a dropdown
![image](https://user-images.githubusercontent.com/109139583/181476661-80e95162-85ae-4a63-b4c6-f82d3183c60d.png)

**Comment by allysonlister** [comment]
Thanks wrt the name/url fields. 

The pulldowns are mandatory but only once you choose an item; when you first load the page, there is no value selected and this can be saved.

Thanks!

**Comment by prakhyatox** [comment]
I get it.

Is there a way I can replicate this step, so that I can verify if the code is working for only url?

Thanks!

**Comment by prakhyatox** [comment]
View for read/write records.
Please let me know if any changes has to be done

![image](https://user-images.githubusercontent.com/109139583/184651794-6450f64b-a1e7-4a97-b010-76917ed287cd.png)

**Comment by allysonlister** [comment]
Just an update as per our meeting earlier today: I'm happy with the overall look, thank you. I was hoping for something as compact as possible. To do this, see how it is described [in gitbook](https://app.gitbook.com/o/-MchtBAOWXh2gO--zz7m/s/-MkSKpWh9NA-iywIqhP_/please-can-we/record-specific-specifications/update-additional-information-fields#display-in-record-view), everything with a URL should have that URL incorporated as a hyperlink into one of the other fields, e.g. "Name" in the example above. All details are provided on the gitbook page.

Thanks!
