### ISSUE TITLE
build login

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/fairsharing.github.io#167]
User can:

- [x] Register a new account
- [x] Validate a new account (need testing)
- [x] Login
- [x] Logout
- [x] Autologin (needs refactoring to prevent storing password on the client side)
- [x] Request a new password
- [x] Edit their profile

**Comment by terazus** [comment]
@Drosophilic Please check the list of subtasks for this activity so I don't miss anything regarding users.
Editing records is another milestone.

**Comment by Drosophilic** [comment]
Hi @terazus - do you want to also test for interactions in FAIRsharing, e.g.:
- Users can link their account to their ORCID or Google profile
- Users can watch a record
- Users can claim and edit a record
- Users can add a comment to a record
- Users can add publications (or pull them in via ORCID)
- Users can link out to social media accounts and websites

**Comment by terazus** [comment]
We are only testing the login/authentication system ATM.
These tasks are much more complex and will be dealt with in milestone 4

**Comment by Drosophilic** [comment]
Indeed, but they are here for context so you can see how the user information relates to other parts of the application.
