### ISSUE TITLE
Display of multiple "cite resource with" publications

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1679]
DisProt (https://fairsharing.org/FAIRsharing.dt9z89) states that in order to properly cite them, you need to cite three publications (https://www.disprot.org/about). I thought multiple "cite with" toggles were allowed (as you can select more than one publication as the publication to cite the resource with) in the edit interface, but upon saving, only one of the enabled toggles is retained.

I have added a server-side ticket that relates to this (https://github.com/FAIRsharing/FAIRsharing-API/issues/526), but as part of this ticket, please can we have multiple "cite resource with" publications displayed properly in the "Publication for Citation" card? You may need to figure out how to handle things if there are a few publications labelled in such a way, as it could make that card look rather large.

Thanks!

**Comment by knirirr** [comment]
I'm completely unable to reproduce this issue. I've tried it locally and also added a second reference to https://fairsharing.org/FAIRsharing.dt9z89. Please would you try adding another and letting me know what happens?

**Comment by allysonlister** [comment]
OK I have tried this too - most odd, but it is now working for me. Please could you close both tickets if satisfied - if it happens again I can reference them... Thank you for investigating!
