### ISSUE TITLE
Making record edits public on the curator user profiles

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1693]
One way to show the work curators do is to make our table on user profiles visible to all. I've attached what I can currently see, as a super curator, for Lindsey's profile - the Record Edits table that shows the work they've been doing.
Making the Record Edits table visible would be a good solution for showing microattribution. That means if curators need to document their efforts with us in any way, they can just point people to their user profile page, which not only would have your general information, but also your "awards" (status as community curator) and record edits.

![bottom-of-user-profile](https://user-images.githubusercontent.com/143586/172647940-a64fe820-63f1-4fea-aab0-10b75c51fdcc.png)

Please can this currently only apply to those with "curator" roles. We may extend it to all users in future, but we would do so after giving the broader maintainer community a chance to provide their thoughts. Our community curators have already expressed an interest in this. Thanks!

**Comment by knirirr** [comment]
A small change to the server so that it always returns data if the user is a curator is all that was needed: https://fairsharing.org/users/5015
