### ISSUE TITLE
Add Malin Sandström as Community Curator

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1706]
Please could you add Malin Sandström (https://fairsharing.org/users/464) as a Community Curator for the domain of Neuroscience to https://fairsharing.org/community_curation ? 

Thank you for already giving her the "award" on her user profile.

I will wait a week or so to ask about pushing to her ORCID profile, as we will shortly be advertising the programme more widely, and it might make sense to do a few ORCID updates at a single time.

Thanks!

**Comment by knirirr** [comment]
I've already completed the push to ORCID as part of https://github.com/FAIRsharing/FAIRsharing-API/issues/536.

**Comment by allysonlister** [comment]
Woo-hoo - thank you! I just didn't immediately see it on her profile, but I see it now -  thank you!

:)
