### ISSUE TITLE
Update Advisory Board

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1722]
Please can you replace Marina Soares E Silva on the advisory board with Lorenzo Feri, also of Elsevier?

Thank you!

**Comment by knirirr** [comment]
Do you have an ORCID ID for him? I have not been able to find one.

**Comment by allysonlister** [comment]
I will email him and let you know what I find out :)

**Comment by allysonlister** [comment]
Here is his ORCID profile, though currently empty - I've asked him to check his permissions in his profile: https://orcid.org/0000-0003-4407-2180

Thanks!
