### ISSUE TITLE
Organisations - simple search

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1731]
Please could we have a very simple organisation search in the style of the user list search that curators can do? Initially I thought of opening this to curator and above, but it might make more sense to allow all users access to it, so that they can e.g. easily see what records an organisation is linked to. 

If it were just curators and above, I would be happy to have a link to this search page visible via our user profile burger menu. However, if we were to open it generally, that would then lend itself to the question of where to link this organisation search on the website. Perhaps via a "looking for an organisation instead?" question on the default search pages that would link out to the organisation search?

Your thoughts are most welcome. Thanks!

**Comment by ramGranell** [comment]
This search system can use the code of the organisation search in the record edit system->"Organisations & Grants"->"Add a new relationship" that it looks into names and alternative names.

**Comment by knirirr** [comment]
After discussion, this could have the following components:

- [ ] An link to "organisations" somewhere.
- [ ] An organisation search page similar to the all_users page which is currently accessible through the hamburger menu on a user's profile page (curators only). This would be in src/views/organisations/OrganisationsList.vue. 
- [ ] A new query to get a list of organisations from the server (similar to the allUsers query). 

@allysonlister my suggestion for the organisations link is to put it at the top of the main page, to the left of "add content" and right of "collections". If you're not happy with this please comment here with any preferred alternative. I agree that this would be best if accessible to all users and so I don't think the user profile hamburger menu is the right place for it. 

https://github.com/FAIRsharing/FAIRsharing-API/issues/561 has been created to provide the organisation data, as I think we'd benefit from having a much faster search as we do with users (the current search might be a bit slow).

**Comment by allysonlister** [comment]
I am happy with everything you suggest, though I think we'll need to be careful that an extra button in the top right might cause display issues on small windows, but I think that's already under control as I play with the site now.

Thank you!

**Comment by prakhyatox** [comment]
Preview in standard screen size (here it is MacBook Pro)

Current
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/109139583/179000989-e66187aa-562e-48fc-a62e-813ee183d2fc.png">


Adding Organisation Button in header

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/109139583/179000806-43b431a8-49f1-4962-ae31-f4118acfca8d.png">
Need to reduce the left and right paddings of the buttons in order to adjust in one line. 

When padding is reduced
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/109139583/179002621-37926943-30ba-4392-b9eb-573215f641d7.png">


Kindly suggest
@allysonlister @knirirr

**Comment by knirirr** [comment]
I'd be happy with reduced padding or even reduced button size.

**Comment by allysonlister** [comment]
Thanks very much @prakhyatox!

In theory, I'd be happier with the reduced padding and/or reduced button/font size to ensure it takes up the same space, however the broader issue, now that I've seen it, is that it looks a little busy up at the top! 

Please could you try two things and show us the screenshots?

1. @knirirr's suggestion of reducing the button/font size as appropriate so that all buttons take approx the same space as before.
2. a two-row approach, e.g. 

![BAD-EX](https://user-images.githubusercontent.com/143586/179013225-f3e63bb2-3cbc-46a8-a71c-310f1a344054.png)

(Please excuse the very bad example, as I have no visual skills whatsoever, just trying to get my point across!)

If you have an idea for a better organisation of these buttons, do please let us know!

thank you :)

**Comment by terazus** [comment]
I recommend finding an alternative to a double rows as it's something i've never seen anywhere else for a header (i think it because it makes it even more confusing ?)

**Comment by prakhyatox** [comment]
1. When button spacing is reduced in smaller screens
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/109139583/179018350-ee62c74a-30bf-434a-8a98-e40690273fbb.png">

2. I would say two-row approach is probably not a better way.
3. Instead we can reduce the size of login button by removing the name and changing its colour to green when user is logged in. Something like this or similar in this line.
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/109139583/179019124-09efa29d-4281-4cc4-872b-c842d09978eb.png">
Because there is no menu on this button it is just showing name.

**Comment by allysonlister** [comment]
Number 3 sounds like a great idea, thanks!

**Comment by prakhyatox** [comment]
1. Button sizes are not compromised.
2. Without login
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/109139583/179028296-30773e30-7d6f-4e55-be43-46fb2f9e9e97.png">

3. When logged in
<img width="726" alt="image" src="https://user-images.githubusercontent.com/109139583/179028775-49899df7-7b12-4433-b7b0-3b4870f6357b.png">

Let me know if that works so that I can push for review

**Comment by allysonlister** [comment]
That works for me, thank you! :)

**Comment by ramGranell** [comment]
As a personal comment, I consider that it is not good idea to have "Organisation" button constantly in the top. The two reasons for this are: 

1. You are putting Organisations at the same level than databases, standards, policies and collections that it is confusing. These Fairsharing registries of the records are the main content of our database that user can create and look for them. However, organisations are not the main database content (they are the main content for the ROR database, https://ror.org/ ) but you are putting them at the same level, relevance or importance giving them the same weight. In fact, the "Add content" button sends you to create a record of registry: databases, standards, policies and collections, but not to create and organisation instead that all the buttons are now at the same level there. From the conceptual point of view is confusing.

2. With organisation button in the header, there are many buttons there getting quite complex (remember that the header is constantly present in all the pages). Discussing with @prakhyatox we have thought that an alternative possibility can be creating a common button called "registry search" that has a menu for searching databases, standards, policies and collections that makes the same that the current buttons.

**Comment by allysonlister** [comment]
Those are some great points, @ramGranell thanks.

So, I agree that we should ensure that our three registries (standards, databases, policies) + collections are given primary importance. As such, I can't see how your point 2 would work as that would remove the prominence of these registries.

Perhaps the best solution is to move the organisations search out of the header altogether, and, for now, add it into the main body of the homepage somewhere. I'm ok if it isn't accessible from *every* page, just as long as it is available generally.

**Comment by allysonlister** [comment]
We had a chat about this in the meeting today, and we agreed to investigate a double-height bar for a possible solution, with @prakhyatox creating a mock up. Thanks!

**Comment by prakhyatox** [comment]
Couple of options for the menu

1.  
![image](https://user-images.githubusercontent.com/109139583/179756841-ffc7b035-e141-4c0b-bad3-a508d36550eb.png)

2.
![image](https://user-images.githubusercontent.com/109139583/179756875-65999d6a-b4ff-4c63-bb37-3e8676885787.png)


I would prefer option 1

**Comment by terazus** [comment]
agreed, 1. is nice.
You will need to reposition the particule overlay vertically as its now overflowing inside the header (it's supposed to be overlayed on top of the "hero block" aka the blue area)

**Comment by prakhyatox** [comment]
> agreed, 1. is nice. You will need to reposition the particule overlay vertically as its now overflowing inside the header (it's supposed to be overlayed on top of the "hero block" aka the blue area)

Yes, It is a canvas. I have to adjust its position top.

**Comment by allysonlister** [comment]
I also agree with the image 1. Thanks @prakhyatox this is really helpful!

Now that we have more buttons, it is important to have our "primary" registries buttons (Standards, Databases and Policies) stand out in some way. Please could you choose a couple of different ways of highlighting these three buttons? Maybe inverting the color or just making a grey background or some kind of shading?

I leave it to your artistic talents to come up with maybe your 2 favorite solutions using our existing color scheme, and then we'll choose?

Thanks!

**Comment by prakhyatox** [comment]
Does this theme for 3 primary buttons looks okay?
Border for first three are in different shades from rest and if that page is active its different highlighted page

<img width="726" alt="image" src="https://user-images.githubusercontent.com/109139583/179962234-79d9e96a-89ef-498a-925c-0a925e6f7599.png">


![image](https://user-images.githubusercontent.com/109139583/179963216-33938269-c76b-43af-9e9d-410120e6c01e.png)

![image](https://user-images.githubusercontent.com/109139583/179963332-78d9d0fa-b8f0-4879-ab62-f2527541efa1.png)

**Comment by allysonlister** [comment]
This looks great! I like the border in the maroon, and the highlighting in maroon when you click on it.

Could the blue text for the three maroon buttons be changed to maroon, to match the outline? I think that's the only comment I have - so please go ahead once you've done that. Thanks!

**Comment by ramGranell** [comment]
I'm having this issue in Chrome Version 103.0.5060.114 (Official Build) (arm64) running in 13-inch screen of a MacBook Pro M1 (2020). The browser was maximum size of the screen.

<img width="1393" alt="Screenshot 2022-07-20 at 16 47 55" src="https://user-images.githubusercontent.com/39826987/180161733-01c10b29-9657-469e-90e3-6010feb854fd.png">

**Comment by allysonlister** [comment]
I just noticed two additional small things as well.

1. The burger menu that appears when the browser shrinks still has all of the buttons in the original blue.
2. The Add Content and Stats used to have a grey border and they've gone blue now - please could we re-introduce the grey?

Thanks!
![burger](https://user-images.githubusercontent.com/143586/180203028-e5ed8346-25b4-4bce-be78-f823ce26ca09.png)

**Comment by prakhyatox** [comment]
> I just noticed two additional small things as well.
> 
> 1. The burger menu that appears when the browser shrinks still has all of the buttons in the original blue.
> 2. The Add Content and Stats used to have a grey border and they've gone blue now - please could we re-introduce the grey?
> 
> Thanks! ![burger](https://user-images.githubusercontent.com/143586/180203028-e5ed8346-25b4-4bce-be78-f823ce26ca09.png)

1. For the Point 1, I will check and update for mobile.
2. For point 2, there will be three different shades in a menu maroon, blue and black (as earlier) in one level of navigation which seems a bit odd. 
Please confirm if still we have introduce the black border again.

**Comment by allysonlister** [comment]
Susanna and I had a bit of a conversation about this, @prakhyatox . Like you, we don't want too many colours within the menu. I think that Susanna was concerned that our "Add Content" wouldn't stand out as much as she'd like.

I'm relatively agnostic here. What do @ramGranell and @knirirr think? Would it be better just to have maroon and blue, or re-introduce the grey border for "Add Content" and "Stats"?

**Comment by knirirr** [comment]
I don't mind either way.

**Comment by ramGranell** [comment]
Not opinion about that as I will remove most of the buttons from the top.

**Comment by knirirr** [comment]
I'll close this now there's a new ticket for further colour changes and the feature requested in this ticket has been completed.

**Comment by allysonlister** [comment]
For general reference - I am happy to keep the Add Content and Stats blue, and not add back in the grey. This makes that bar's buttons in maroon and blue.

Thanks!
