### ISSUE TITLE
Save buttons in General Information greyed out

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1732]
**Describe the bug**
 "General Information" tab in https://fairsharing.org/1567/edit has odd behaviour in the save buttons. When I load it, the "Save and Continue" as well as "Save and Exit" buttons are greyed out, though the other tabs' buttons look OK

**To Reproduce**
1. Go to https://fairsharing.org/1567/edit
2. scroll down to save buttons
3. Buttons are greyed out. 

**Expected behavior**
Save buttons should be green.

**Comment by knirirr** [comment]
The buttons turn out to be behaving correctly. But, the portion of the form which is invalid and preventing submission (presumably created by bypassing the form) does not have validation triggered until the user clicks on it.
There's a workaround discussed here, to trigger validation of form elements on page load:
https://github.com/vuetifyjs/vuetify/issues/12768
