### ISSUE TITLE
Summary spreadsheet download button

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1734]
A number of users have made requests to us recently where they would like to have a look at search results from FAIRsharing via a spreadsheet. While this can be done internally on a case-by-case basis, it is time consuming for our team. While we would like our users to retrieve most of the record metadata by calling the API or browsing the record, a simple spreadsheet for this purpose would help users. However, we would like to only allow logged-in users to do this, to discourage spamming of such a button.

 I suggest the button should go in two places:

1. In collections (allowing them to download a summary of collection members)
2. In search result pages

How about for search results we put it as another icon as part of the pair in the top right that allows you to change between cards and list of search results? Could go in the same place for collections.
![example](https://user-images.githubusercontent.com/143586/176130347-3926e4fc-f817-4005-890e-abcc8984ccd1.png)

The fields of the spreadsheet should be minimal, e.g.

FAIRsharing URL | FAIRsharing DOI (where present) | Record Name | Record homepage URL

**Comment by knirirr** [comment]
The code the the branch I've just pushed doesn't have full test coverage; there's no point in testing it all as I'll need to re-write a lot of it once I've completed work for https://github.com/FAIRsharing/FAIRsharing-API/issues/547.
