### ISSUE TITLE
Update message text in deletion popup

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1736]
Please could you update the message text for the "Delete this record" popup created originally in #1477?

Here is how it looks now:
![popup](https://user-images.githubusercontent.com/143586/176185893-7014f9bb-bfd1-454f-862b-dfb2cea6d6bb.png)

Instead, could it say:

"Are you sure you want to delete (without DOI) or tombstone (with DOI) this record (Record name)?"

Thanks!

**Comment by ramGranell** [comment]
"Are you sure you want to delete (without DOI) or tombstone (with DOI) this record (Record name)?"
Do you want anything in red or uppercase?

**Comment by allysonlister** [comment]
Good point - please would you keep the word DELETE in red and in uppercase? Thanks for checking!
