### ISSUE TITLE
Add artificial data

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/fairsharing.github.io#174]
When using the graphQL user query, the following fieds are empty:
- maintenanceRequest
- recordInCuration
I would need you to create artificial relationships to tests the front end display of these items.

**Comment by ramGranell** [comment]
I will start with a new migration with the last version of the DB. In this new version I will add fake relationships (maintenanceRequest). About recordInCuration, I cannot find it in the model. I will ask Milo, about it

**Comment by knirirr** [comment]
If recordsInCuration is a field on the GraphQL UserType then I don't think it's been migrated. It will be found on the old system via a roundabout means - there will be a "sparse_data" field on each record which should contain the username of the current curator as "current_curator", IIRC. To migrate this field it would be necesary to find the user by username (`User.where(username: current_curator).first`) and assign the record to them (`user.records_in_curation << record`).

**Comment by ramGranell** [comment]
About recordsInCuration, do you think we need to migrate it or the curators should stop to finish all the curation tasks/records for a time before performing the migration? Therefore this field as maintanceRequest are not going to be migrated. This is the easiest solution and maybe I need to open a ticket about it in the proper place.

Another thing is that I can fake data to have examples to test both backend and frontend, that it was @terazus was asking us to do. In the migration branch, I'm creating a task to perform this

**Comment by knirirr** [comment]
My preference would be to resolve all those issues before the final migration if possible, so the fields do not have to be migrated. As to whether this is feasible or not I'd have to leave the answer to @Drosophilic and @allysonlister. But, if you are having to fake the data in an earlier migration it might well be worth migrating it.

**Comment by Drosophilic** [comment]
This may not be feasible, but we can try.

**Comment by ramGranell** [comment]
I created a new DB with all the current tables from the migration but faking the fields:
maintenanceRequest
recordInCuration
The faking task is in the db)migration branch of https://github.com/FAIRsharing/FAIRsharing-API: rake migration:faking_some_fields
