### ISSUE TITLE
Add Summary Counts graphic to homepage

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1753]
Please can we have a set of summary "boxes" on the FAIRsharing homepage to showcase some basic statistics about FAIRsharing? Underneath the boxes could be a link to our statistics page (e.g. with the text "full statistics" or similar). 

## Location
This should go in the dark blue section of the page, in between the general search and the subject browser. I'm not 100% convinced it will fit there, so if you have different ideas I'd be happy to hear them. To help it fit, please could you put the "Browse by Subject" button below the subject browser logo, and perhaps the size of the white search box could be slightly shrunk. If it really doesn't seem to fit there, then try it in its own area directly above the dark blue section please.

## What Summaries should be included?
| Box text | how to get the value for NNN | comments|
|--------|----------|-------|
|NNN Community contributors| number of users with "curator" role + number of users who maintain at least one record of any record status|needs separate ticket for REST endpoint. |
|NNN Resources described| number of standards + databases + policies| Note that collections are not included in this count, but all record statuses should be included.
|NNN Views since 2011|from google analytics |The "since 2011" should be in smaller footnote text below the main box text. Unknown if https://developers.google.com/analytics/devguides/reporting will provide this. Additional comments on this item in the next section below.|

## Notes on "Views" stats

The questions I have regarding the Views stats are shown here. Mostly, I'm looking for the best way to make a few choices, bearing in mind our current audience overview on google analytics has the way the page visits are counted changed since we implemented the new site? We've gone from 4000+ users in a month to much less, and I'm sure that's not right... If necessary, please make another ticket to investigate this.

Please can I have developers' opinions on 

1. unique vs non-unique counts of site visits? 
2. ideally, this would be over all time, since biosharing.org started. I realize it may or may not be possible to get this info from the biosharing google analytics page, but once we have the number it can just be permanently added to the running total we get from google analytics for fairsharing.org. If only the fairsharing.org stats can be used, then we need to update the box text to "Views since 2018"
3. What is the right terminology here? I've called the box text "NNN views since 2011", but should we use views, or another word such as visits/users/something else?

**Comment by knirirr** [comment]
The stats are now available at https://api.fairsharing.org/homepage_stats, though the values won't be correct until Elasticsearch has been reindexed.

**Comment by allysonlister** [comment]
I'm not sure if my input is required at this stage, but the stats look good to me, thanks!
