### ISSUE TITLE
Clipped button edges

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#1759]
Here's a screenshot taken using the 'laptop with MDPI screen' (1280x800) setting of Firefox's responsive design mode:

<img width="1318" alt="Screenshot 2022-07-22 at 08 52 03" src="https://user-images.githubusercontent.com/3583375/180392116-eb6fceb2-4ab9-4bdc-b099-a48c3ddeaaa1.png">

The edges of the buttons in the second row of the header have been clipped by the edge of the screen.

**Comment by prakhyatox** [comment]
1280 x 800
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/109139583/180405029-4df4aa4f-b964-4b6a-b607-c6adf1404524.png">


MacBook Pro 13'inch
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/109139583/180405168-f7e2511d-2861-47c8-bcae-ef33d2959ce7.png">

Please confirm if this is okay

**Comment by knirirr** [comment]
What browser are you using for those screenshots?

**Comment by prakhyatox** [comment]
Firefox
