### ISSUE TITLE
Add ROR icon to organisation in a record that have a ROR id

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1762]
To better highlight our mapping to ROR, please can we add a very small ROR icon that links straight to the relevant record in ROR for that organisation?

Here's what we do in a very similar way for ORCIDs, and it could be done in a similar style:
<img width="150" alt="image_2022_07_22T13_09_10_996Z" src="https://user-images.githubusercontent.com/143586/180447370-82f2af92-220f-46df-a971-a302138d5a67.png">

And we could add a similar small icon to each organisation within a record that maps to ROR, e.g. in https://doi.org/10.25504/FAIRsharing.wy4egf 3 out of 4 organisations would have the icon (OpenAIRE is not an organisation that is in ROR).
![zenodo](https://user-images.githubusercontent.com/143586/180743355-fee618a4-deba-464d-872e-fbc9620168c5.png)

For this ticket, you may need to review the ROR guidelines and downloadable logos, as it seems they have already made a small one available. Please also note that the logos seem to be CC BY-ND 4 so this will need to be taken into consideration and attribution added at an appropriate location on our site.

https://ror.org/display-guidelines/ - permissions and how to use
https://doi.org/10.5281/zenodo.4701801 - logos
https://ror.readme.io/docs/outreach-resources-logos

**Comment by allysonlister** [comment]
Apologies, I have updated the image and the text above it.

**Comment by knirirr** [comment]
Currently, organisations shown on our record pages link back to the organisation's page on our own site. ROR's guidlines request the use of a link to them next to any text with an ROR icon. 
We could change the link to be directly to them if an ROR ID is present, leaving other organisation links pointing back at FAIRsharing. Or, we could omit the ROR icon from the place shown above and add it instead in front of the ROR URL shown on our record pages, and link everything back to our own record page (see https://fairsharing.org/organisations/1960 for an example).
I would much prefer this latter option as it would maintain links to our own pages as well as providing exactly what ROR request. Is there any objection to this?

**Comment by allysonlister** [comment]
To ensure I have it correct, your preferred solution is to add the ROR icon to the organisation pages (where applicable). This ROR icon would link the user directly to the ROR entry. Then we wouldn't need to make any changes to the standards/policies/databases/collections records linking to the organisations. Is this correct?

If so, I am happy to have this alternative, as it is the best place for the icon. Susanna may also wish to have the icon on the record **as well**, so if I am correct let me know and I will run it past her.

**Comment by knirirr** [comment]
Yes, that's what I have in mind. The ROR document suggests that having the icon on our record pages _without the record name being a link to ROR_ does not meet their requirements, though. So, if that's what's requested you'll have to decide whether to go against what they request, or change our links.

**Comment by allysonlister** [comment]
Thanks - I'll check and get back to you :)

**Comment by knirirr** [comment]
There's an example in the draft PR at https://github.com/FAIRsharing/fairsharing.github.io/pull/1765.

**Comment by allysonlister** [comment]
Thank you - have just spoken with Susanna, let's go forward as you suggest, with just the modification to the organisation page. The example in the draft PR looks great. 

Thanks!

**Comment by knirirr** [comment]
This is done for the organisation page and will appear on the site next time dev is merged to master.
