### ISSUE TITLE
Search ROR when creating organisations

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#1764]
https://github.com/FAIRsharing/FAIRsharing-API/issues/568 discusses a means of making organisations from ROR available to use in FAIRsharing. This can be done by adding a "search ROR" button on the organisation creation form which will query the ROR API an populate the form fields. 

From that ticket:

A can to ROR API be using their Elasticsearch engine. The call is in the style: "curl https://api.ror.org/organizations?query=TEXT_TO_QUERY", e.g. curl https://api.ror.org/organizations?query=bath . It returns the 20 closest organisations based on the search. More information about ROP API here: https://ror.readme.io/docs/rest-api .

Using this API call, we can provide something similar as we have for the article search using DOI and Zenodo.

N.B. this may return multiple organisations so the implementation will have to differ, to allow users to select the response to use (similar to a postcode search when completing one's address on an order form, perhaps). 

The API calls used to get information about publications are here:

https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/components/Editor/EditPublications.vue#L428-L533

A similar call (but using the ROR API as mentioned above) will need to be written and added to the organisations editing component, probably the LinkOverlay:

https://github.com/FAIRsharing/fairsharing.github.io/tree/master/src/components/Editor/Organisations

**Comment by ramGranell** [comment]
The ROR data structure of the .json data returned by the API is here: https://ror.readme.io/docs/ror-data-structure 

We need to do a mapping between the organisation types that appear in ROR and our organisation types. A suggestion to do this can be found here (under subsection "Using ROR API calls to create new organisations":
https://app.gitbook.com/o/-MchtBAOWXh2gO--zz7m/s/-MkSKpWh9NA-iywIqhP_/please-can-we/organisations/map-to-ror-fundref

Please, @allysonlister can you check if you agree with the mapping?

**Comment by knirirr** [comment]
This has now been deployed.
