### ISSUE TITLE
Conditional validation in additional information

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#1777]
An error message is shown here:

https://github.com/FAIRsharing/fairsharing.github.io/issues/1653#issuecomment-1197908694

This has happened because the schema requires that a name is also provided if a URL is provided. The code which generates the additional info. edit forms on the fly doesn't have any means to handle this general validation case, i.e. one field is required only if another is present; it only handles whether a particular field is required or not, or what format (e.g. URL) it ought to be.

This will involve parsing the JSON schema and looking for dependencies, e.g.

https://github.com/FAIRsharing/FAIRsharing-API/blob/master/lib/record_schemas/database_schema.json#L25-L27

Then, a validation rule to apply to the affected fields will need to be written and applied.

**Comment by allysonlister** [comment]
To be explicit with all of these types, here would be my preference for requirements:

|field|optionality|
|----|------------------|
|data curation / data access condition / data deposition condition| This entire field is optional, so initially none of notes/type/url is filled out. If *anything* at all is filled out, then **type** must be also filled out. This is the only requirement.|
|resource sustainability / data preservation|Keep this as already within the code, which is that if one is present, both should be present.|

Please let me know if anything else is needed.

**Comment by knirirr** [comment]
It looks like this was dealt with by the above PR so I'll close it.
