### ISSUE TITLE
Additional attribution for community curators for September

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1781]
I'd like to showcase our new community curators on our site from September, when we have our first intake (other than our beta curators, of course!) I won't be announcing the successful applicants until the very end of August, and we need to give them time to confirm they wish to take part, but I'd like to start getting the pages ready for them. To do this, I see the following updates please.

## Community Curators 2022 Intake Static Page

While keeping the table in /community_curation as it is (and always show our currently-active community curators), we would like to add new static pages for each intake, beginning with our first official group of community curators, the "class of 2022" so to speak.  

Each intake would have its own static page that we'd link to from /community_curation, e.g. "Community Curators 2022", and these would contain image cards. We could make a different page for each year, so people would have a page to use as a reference that they were active with us, even as the table in /community_curation would only show currently-active curators.

There are lots of ways of doing such image cards, but [here's](https://microbiomedata.org/ambassadors/) a good example that we can get some ideas from. 
![image](https://user-images.githubusercontent.com/143586/182240851-594aa6b9-2a58-4bb2-8591-3144c68b3339.png)

Each card would have a photo (or a choice of either their organisation logo or a FAIRsharing logo if the curator didn't wish to provide a photo). 

* Overlaid on that photo: "Name (affiliation) Domain" 
* In the stripe at the bottom we can have a clickable ORCID link. The "plus sign" or some other indicator of "more information" can go to the user page for that curator.

I've checked with our beta community curators, who like this idea.

## Linking to these new static pages

Under the **Our Community Curators** heading in /community_curation please change the text from

> Our user community is diverse in breadth and scope, with a number of [stakeholder groups](https://fairsharing.org/stakeholders)  across all areas of research and research support. In early 2022, we began with a few Early Adopters, who have contributed greatly to the initial success of the programme

to 

> Our user community is diverse in breadth and scope, with a number of [stakeholder groups](https://fairsharing.org/stakeholders)  across all areas of research and research support. In early 2022 we began with a few Early Adopters, who have contributed greatly to the initial success of the programme. In September 2022 they were joined by the _**first cohort**_ of Community Curators. All currently-active community curators are listed in the table below.

Then **_first cohort_** can be hyperlinked to the new page. Perhaps something like /community_curators_2022 ?

Thanks!

**Comment by knirirr** [comment]
I'd guess that the easiest way to do that is to create a single display page and also a single JSON file with the data for each year. Then, the page could be accessed via a URL such as /community_curators/2022, and the appropriate data loaded based on the year in the path. E.g.

```
{
  "2022": [
    {
       "name": "...",
       "affiliation": "...",
       "domain": "...",
       "logo_file": "...",
    },
   ...
  ],
  "2023" : [
    ...
  ]
}
```

**Comment by knirirr** [comment]
I have created a draft PR with the files in place, though the page's appearance is unfinished.

**Comment by allysonlister** [comment]
To be more explicit, here is how the json for each record looks now:

```json
{
    "name": "Kyle Copas",
    "id": 5832,
    "organisation": "GBIF",
    "id_organisation": 1166,
    "scope": "Biodiversity",
    "orcid": "0000-0002-6590-599X",
    "logo": ""
  },
```

We need to add fields to the json to include a 

* photo (is this the "logo" that is shown above?)
* whether or not to include them in outreach materials (e.g. fieldname "use_in_outreach" true or false). This field should be included in the json but not visible on the web pages. It just lets the curators know if we should link them in tweets, blogs etc. I'm still in talks with the people that have requested to not be included in outreach if they would like their photo included, or just name and organisation on the static pages themselves.
* 0...* social media name-url pairs (e.g. "Twitter", "https://twitter.com/allysonlister"; "LinkedIn", "https://www.linkedin.com/in/allysonlister").

Thanks!

**Comment by knirirr** [comment]
> whether or not to include them in outreach materials (e.g. fieldname "use_in_outreach" true or false). ... It just lets the curators know if we should link them in tweets, blogs etc.

The only place that this will be defined is in a JSON file within the client application (src/data/communityCurationCohorts.json). Is that something you want to read and the location of which you would be able to note somewhere for your future reference? If not then some other means of storing this information ought perhaps to be used. Or, if you want it to be stored in that file but to easily reference it, then the contents of this field should be displayed to curators who are viewing the page.

**Comment by allysonlister** [comment]
If I'm following you correctly, then yes I think having it only in the json file is sufficient; I wish to be able to read this info, but it doesn't need to go e.g. in the user profile information. Is that what you're asking?

I like your idea of this value being displayed when super curators are logged in; we are the only official FAIRsharing curators, and therefore are the only ones who would be performing FAIRsharing outreach.

Thanks!
