### ISSUE TITLE
Updating new fields in the DB when importing an organisation from ROR

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/fairsharing.github.io#1803]
Currently, when an organisation imports the data from ROR, it does not import some of the available fields that exist in ROR but we have them in our DB. The fields that need to be updated in our DB (they do not require to be displayed in the form of creating of a new organisation) are:
-ror_link
-Alternative names

For example in this query  https://api.ror.org/organizations?query=MIT in the second organisation, the first ROR ID (field id) is https://ror.org/04mtcj695 and there are three alternative names (two acronyms that can be found in the field "Acronyms" ("USM" and "MIT" and one in the field "aliases" ("Mindanao Institute of Technology"). I do not want to use the field "labels" as they have the foreign name of the place, e.g. "Unibersidad ng Katimugang Mindanao" or see Japanese characters in the query https://api.ror.org/organizations?query=tokyo

@allysonlister  do you agree with obtaining these fields automatically from ROR?

Note, that an error may happen when saving an organisation that has a ror_link that already exists.

**Comment by allysonlister** [comment]
I'm happy for you to pull the aliases and acronyms from ROR to use as alternative names. 

When you mention "ror_link" in your comment, do you mean that "ror_link" is the other field that we update in our database, but isn't shown to the user when they are using the new organisation creation form?

Thanks!

**Comment by ramGranell** [comment]
Yes, the ror_link and alternative namers are not shown in the creation form (there is only name, homepage, type and country), however the fields are available and we can use to  add them in the DB. Later, they appear in the organisation page, eg https://fairsharing.org/organisations/2310

**Comment by allysonlister** [comment]
Perfect thanks - happy for you to proceed!
