### ISSUE TITLE
Redirections for old URLs

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1865]
Hi all!

There seem to be a few convenience URLs that used to be used on the old site that aren't redirecting to their equivalents. Please could you create these redirections?

old URL | Redirects to
---|---
https://fairsharing.org/standards/reporting_guidelines|https://fairsharing.org/search?fairsharingRegistry=Standard&recordType=reporting_guideline&page=1
https://fairsharing.org/standards/reporting_guideline|https://fairsharing.org/search?fairsharingRegistry=Standard&recordType=reporting_guideline&page=1
As the two rows above, but for every record type across standards, databases and data policies| "
https://fairsharing.org/recommendations|https://fairsharing.org/search?isRecommended=true&page=1&searchAnd=false&fairsharingRegistry=database,standard
https://fairsharing.org/license|https://fairsharing.org/licence
https://fairsharing.org/communities/activities|https://fairsharing.org/communities#activities
https://fairsharing.org/HUPOPSI|https://fairsharing.org/3514

These were taken from various publications (RDA outputs, FAIRsharing publication etc) and checked and are currently 404.

Thanks!

**Comment by knirirr** [comment]
Re. that last one, this is available: https://fairsharing.org/HUPO%20Proteomics%20Standards%20Initiative
As is: https://fairsharing.org/HUPO-PSI

Where is the offending link?

**Comment by allysonlister** [comment]
In one of the manuscripts the URL doesn't have a dash between HUPO and PSI and that gives a 404... I don't want to change the record to accommodate this as HUPO-PSI is correct, so having the redirect would be useful :) thanks!
