### ISSUE TITLE
Github actions Node version update

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#1880]
The details can be found in this post: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by terazus** [comment]
If i remember correctly the site builds of both 16 and 18.
I suggest you try out nvm (https://github.com/nvm-sh/nvm) to handle mutliple node install.

**Comment by knirirr** [comment]
I wasn't able to update all actions to 16, but I updated the docs action from 10 to 14; apparently, warnings are being shown for 12 and below so this should keep us going for a while.
