### ISSUE TITLE
Please add new curator Kay Burrows

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1901]
Hi all, 

please could you add Kay Burrows as a new community curator at our_curators?

Her user account is: https://fairsharing.org/users/8056 where you can find organisation and orcid info. Her scope will be "Policies; Chemistry"

**Comment by knirirr** [comment]
Do you also want her to receive a 2022 award?

**Comment by allysonlister** [comment]
Thank you, sorry I didn't mention that. Yes she will be active this year so let's start her with a 2022 award. Thanks!
