### ISSUE TITLE
Link Community Curator tiles to their user accounts

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1908]
Please could our community curators' names in their tiles on https://fairsharing.org/community_curation/our_curators be linked to their user account public profile pages?

Thanks!

**Comment by ramGranell** [comment]
@allysonlister I am not sure but think that it linked below the picture. For each curator, if you press over the "Meet NAME CURATOR" it goes to the user public profile page.

**Comment by allysonlister** [comment]
Oh my goodness - how did I miss the giant button?!! Thank you!
