### ISSUE TITLE
Additional info. field toggle fails to detect current value of field

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#1911]
This was originally moved from a comment on https://github.com/FAIRsharing/FAIRsharing-API/issues/626.

Using the example of  https://fairsharing.org/4507/edit, the licences for outputs value is set to "yes" but the toggle is showing as off. Toggling it shows the correct behaviour, so it is presumably not being set correctly on page load.

**Comment by allysonlister** [comment]
Please note, relating to your previous question, that I do not suggest that we change all "value" to "required" - I was just talking about this particular example.
