### ISSUE TITLE
Form and updated communities page to show tools that are making use of FAIRsharing

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1927]
# General request
ROR has a lovely [page](https://ror.readme.io/docs/ror-integrations) that showcases those resources that are using their API or using the FAIRsharing metadata in some other way (e.g. including our IDs/links in their resource). 

We've been thinking for some time of a way in which we can also showcase those who integrate our metadata with their projects, and would like to implement something similar to this. Without getting into any technical detail, this is how we would like it to work:

1. User visits our [communities](https://fairsharing.org/communities) page and sees the list of existing tools under "Adopters" and wants to showcase their tool and how it uses the FAIRsharing API.
2. User finds a link on the page that says "Let us know how you're using FAIRsharing" (or some variant thereof), clicks on it (see below for text)
3. This takes them to a google form that they provide the details of their usage of FAIRsharing
4. The technical team are notified when the form is submitted, and they check it for completeness and that it is in scope
5. "magic" happens and the page on our static site is updated with the new card. 

Note that we've recently implemented cards for our community curation page (https://fairsharing.org/community_curation/our_curators) and that perhaps some of this code could be repurposed for this task?

# Placement
The Adopters section (that is reached via its Adopters "tile") in https://fairsharing.org/communities should now be structured as follows:

A broad range of [stakeholders](https://fairsharing.org/stakeholders) come to FAIRsharing from across all research domains. However, adopters use FAIRsharing specifically to do one or more of the following:

 i Educate their users/community on the variety of existing standards, repositories and policies that exist in FAIRsharing and actively encourage them to submit/claim records, where relevant;
 ii Recommend resources by registering their data policy, and then link it to standards and/or databases [recommended](https://fairsharing.org/search?page=1&isRecommended=true) in the policy;
 iii Create a [Collection ](https://fairsharing.org/collections) that pulls together a list of standards and/or databases around a given domain of interest relevant to them. 

Adopters are generally representatives of institutions, libraries, journal publishers, infrastructure programmes, societies and other organisations or projects that in turn serve and guide individual researchers or other stakeholders on research data management matters. Adopters display a FAIRsharing logo on their websites with a link from their website to our homepage. 

In general, our adopters fall into the following broad categories. If you don't see your project on the list of adopters, please get in touch.

Funders (section link that jumps to what is currently the first table in this section)
Publishers (section link that jumps to what is currently the second table)
Organisations (section link that jumps to what is currently the third table)
Tools (a new table that looks a bit like our our_curators page  but where each tile is a tool submitted using the form below and vetted by the @knirirr and the Technical team.

# updated introduction for Funders
A selection of official reports from funders and other organisations that recommend the use of FAIRsharing as a key asset for all stakeholders to enable FAIR data: 
# updated introduction for publishers
A selection of the publishers that use FAIRsharing to define and refine their data policies. 
# updated introduction for organisations
A selection of the organisations working closely with FAIRsharing.
# Introduction for tools section
Tools that make use of FAIRsharing content. If you would like your tool included in this list, please use this form to let us know how you're using FAIRsharing.

# Information for form

Many tools make use of FAIRsharing, for example in the areas of FAIR evaluation/assessment and data management planning. If your tool utilises FAIRsharing, please tell us, and in return we will link back to you via our [communities](https://fairsharing.org/communities) page. All information entered below will be visible to the public, unless otherwise stated.

field name | mandatory? | field type | comments
---|----|----|---
The names and URLs of the organisations that are directly involved with the development of your tool. | x | text | Curators will link them to our FAIRsharing organisations, as I think it would be too difficult to link this to a FAIRsharing organisations search
Let us know the name of the tool or service that is utilising FAIRsharing. | x | text | 
Type of Tool|x|multiple select tickboxes from this list: FAIR evaluation/assessment, Cross references, Data Management Plan (DMP) development/lifecycle, (Meta)data retrieval/integration, Other . If "Other", a text box should be provided that they need to provide their own answer for.||
Logo|x|image| to allow the developers to showcase their tool with a logo
The status of your tool.|x|Choose only one of: Planned, In progress, Completed|
Please give a short description of how your tool and how it uses FAIRsharing |x| free text|
Please provide a link to the homepage for your tool|x|url|
An image (preferably square) showing your tool and its use of FAIRsharing. This is not required, but is highly recommended.||image upload|
Name of official contact for this tool. This information will not be made public.|x|text|
Email address for official contact for this tool. This information will not be made public.|x|email address|
Do you have anything you'd like to add? This information will not be made public.||text|

**Comment by knirirr** [comment]
A form is now available at https://docs.google.com/forms/u/0/.

**Comment by allysonlister** [comment]
Thanks - that link didn't work for me but going directly to our google forms did, I'm looking now :)

**Comment by knirirr** [comment]
Will there be any tools to add on the initial deployment of this page, or will we be waiting for some forms to be submitted first?

**Comment by allysonlister** [comment]
That's a great point - I wonder if we should invite a select few tool developers to fill out the form ahead of time. I'll have a think and get back to you

**Comment by allysonlister** [comment]
We have now invited a few tool developers to respond, and have so far had two responses. This should be enough to start testing how the tiles would look with real data. Let me know if their form responses are not quite right, or if you think we should modify the form as a result.

**Comment by allysonlister** [comment]
Two of our recent form submissions have provided screenshots of how FAIRsharing is used in their tools. @knirirr has this been added to the tile code yet? How do you suggest incorporating these screenshots? Perhaps if you click on a link in the white section of the tile (or in the logo area) that will display the screenshot?

**Comment by knirirr** [comment]
I've not done that yet and don't currently have any plans or ideas. I will get back to it later when I have time.
