### ISSUE TITLE
Add Linkedin links and images to curator page

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1940]
There are two parts to this ticket:

1. the addition of LinkedIn links to many of the curators (I will attempt to create a branch and make these changes myself - wish me luck!)
2. The addition of a number of photos for the various curators. Would you like me to email these offline? Any other thoughts?

Thanks!

**Comment by knirirr** [comment]
I would suggest sharing the photos via Oxfile - I can supply information on this via Zulip if necesary.
Please go ahead with the branch - the Netlify build should show up any issues with the JSON before merging.

**Comment by allysonlister** [comment]
I've shared on oxfile, and you can see the commit above that I made in a branch and asked for a review of the changes for the linkedin usernames. Thanks!

**Comment by knirirr** [comment]
> I've shared on oxfile, and you can see the commit above that I made in a branch and asked for a review of the changes for the linkedin usernames. Thanks!

I couldn't find a PR for review so I have created one. It has a lot of additional merge commits shown which are strange; I wonder if this is related to the means by which the branch was created.
Anyway, it has a Netlify build and so can be viewed.
Image quality is dependent upon the image originally supplied by the curator.

**Comment by allysonlister** [comment]
I must have done it wrong then - sorry! (I did this, please scrap the branch if necessary and I can do it again, if you remind me how)

1. in the github website UInavigated to the json file within the master branch
2. opened it and edited it directly in the browser
3. clicked that I wanted to make a branch rather than commit directly to master, and added an appropriate message
4. said that I wanted you and @prakhyatox to review the changes

I'll look at the build now
