### ISSUE TITLE
JSON not valid from API

### ISSUE THREAD

**Issue by stuchalk** [FAIRsharing/fairsharing.github.io#1961]
**Describe the bug**
When downloading data from the FAIRSharing API (JSON output), some fields that are not JSON compatible.

**To Reproduce**
1. Login to FAIRSharing in Python (in code)
2. Run search via 'https://api.fairsharing.org//search/fairsharing_records?q={searchterm}'

**Expected behavior**
Valid JSON output.

**Screenshots**
![Screen Shot 2022-12-13 at 11 34 27 AM](https://user-images.githubusercontent.com/540150/207391934-e2f2208b-a0f0-43bd-8a88-0166e025dd2e.jpg)

**Operating system and browser version**
Mac)S 12.6.1, Firefox v107.0.1

**Additional context**
The search I tried was for "chemistry"

**Comment by knirirr** [comment]
@stuchalk what was the source of the screenshot above? Did it come from your Python code?
According to https://www.rfc-editor.org/rfc/rfc4627.html (see 2.1) then `null`, `false` and `true` are correct. In the raw JSON I received when trying a similar query I got:

```
"url_for_logo": null,
"exhaustive_licences": false
```

...which looks correct.

**Comment by knirirr** [comment]
I'll close this as I don't think we need to change anything.
