### ISSUE TITLE
Inconsistent data submission to authenticate to the API in Python

### ISSUE THREAD

**Issue by stuchalk** [FAIRsharing/fairsharing.github.io#1962]
**Describe the bug**
When calling the API to authenticate, the addition of data to the call is inconsistent.  Header information is submitted as a Python dictionary, whereas data for authentication is presented as JSON.

**To Reproduce**
1. Include Python command '`response = requests.request("POST", url, headers=loghdrs, data=json.dumps(login))`'

**Expected behavior**
Developers in Python would expect to submit both sets of data as Python dictionaries, so the code should be updated to convert the authentication data from a Python dictionary to JSON internally.

**Screenshots**
NA

**Operating system and browser version**
MacOS 12.6.1, Python 3.10.9

**Additional context**
NA

**Comment by knirirr** [comment]
I'm afraid that we'll need to accept JSON only on the API. 
The text at https://realpython.com/api-integration-in-python/#post appears to suggest that it should be easy enough to handle.

**Comment by stuchalk** [comment]
OK, that I understand.  However, above the header information is a Python dictionary not JSON, so that needs to be updated...

**Comment by knirirr** [comment]
With luck https://github.com/FAIRsharing/fairsharing.github.io/commit/76f84be6c310b37f5a705c909714fed3f91d5a0d will do the trick.
