### ISSUE TITLE
Community Curators page update for 2023

### ISSUE THREAD

**Issue by prakhyatox** [FAIRsharing/fairsharing.github.io#1977]
**Describe the bug**
The community curators page needs an update to show the curators for year 2023(if required). Currently, all the curators are of year 2022 which have become the alumni curators(default behavior).

**Expected behavior**
Community curators page needs to updated for year 2023 (if required).

**Actual behavior**
Community curators page contains the curators for year 2022 (converted to alumni curators)

**Screenshots**
Current

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/109139583/210339251-3ac0184e-cfcc-4016-a724-2886168e9302.png">

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/109139583/210339346-f99b44dd-0686-4c43-b6f9-13431bcd8be0.png">

**Comment by allysonlister** [comment]
Thank you. Please can you add the 2023 year to all curators except for Annie and Joe. If it turns out they need to be in 2023, we can change that later.

Thanks!

**Comment by allysonlister** [comment]
Please could you also make a ticket about pushing ORCID attribution for 2023? We don't actually want to do that yet as I need to confirm with everyone that they are definitely staying on this year, but the ticket could be created, and just say on it that you will only push to orcid once I've confirmed. Thanks!

**Comment by prakhyatox** [comment]
> ORCID attribution for 2023

Ticket created : https://github.com/FAIRsharing/fairsharing.github.io/issues/1982

**Comment by prakhyatox** [comment]
> Please could you also make a ticket about pushing ORCID attribution for 2023? We don't actually want to do that yet as I need to confirm with everyone that they are definitely staying on this year, but the ticket could be created, and just say on it that you will only push to orcid once I've confirmed. Thanks!

Ticket created : https://github.com/FAIRsharing/fairsharing.github.io/issues/1982
