### ISSUE TITLE
Missing curator from our current our_curators

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2000]
Hi all!

Please could you add back in Debora Drucker for 2022 (https://fairsharing.org/users/7877) ? She hasn't yet confirmed with us if she's continuing in 2023, but it appears as though she's been dropped from the list. Perhaps I have not correctly asked for her to be assigned the "curator" role?

Please could you investigate? It's OK to add her just for 2022, and I will confirm in the next week with her if she is continuing for 2023. So it might be changes to the db need doing (if her role isn't correct) or it may just be updates to the front end.

**Comment by ramGranell** [comment]
She is not in the current list of community curators https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/data/communityCurationCohorts.json Then, we can assume that she has never been added or she was removed at some point. You or I (if you tell me what fields add to her) can modify the .json file. You can ask her for a photography as well. About her role in the DB she is already a curator.

**Comment by allysonlister** [comment]
Thanks! Here's a pic from her LinkedIn page, and a LinkedIn URL: https://www.linkedin.com/in/debora-drucker/
orcid: https://orcid.org/0000-0003-4177-1322
![drucker](https://user-images.githubusercontent.com/143586/215745224-b4f82659-78d4-40cb-96b8-d656a3731756.jpeg)

Could you also add https://ror.org/0482b5b22 as her organisation? It will need to be added to FAIRsharing. Sorry, I won't have time to do it at the moment.

Is there anything else you need? She should show as active for 2022 and 2023.

Thanks!

**Comment by ramGranell** [comment]
Which scope I need to put to this curator: "Agricultural research"?

**Comment by allysonlister** [comment]
Sorry about that! She has self-described as "Ecology, Biodiversity, Agriculture, Environmental Science" - to try to make this more succinct, let's say "Ecology, Agriculture" as this encompasses the others. She can ask for modifications as required.

Please could you also add her ORCID service for 2022? You don't need to 2023 yet as we'll do those as one big group in a week or so.

Thanks!

**Comment by ramGranell** [comment]
About the ORCID attribution for 2022 it will updated in ORCID when we do the general attribution that it is waiting to be performed in #1982 . The current task goes for all the years and curators that have bee not already attributed and perform the attribution.

**Comment by ramGranell** [comment]
@allysonlister , there are three tickets related to Champions attributions:
1. This one
2. https://github.com/FAIRsharing/fairsharing.github.io/issues/1982
3. https://github.com/FAIRsharing/FAIRsharing-API/issues/632

When do you think we can run the script to give the attributions to the Champions?
Greetings,
Ramon

**Comment by allysonlister** [comment]
Thank you - apologies this had slipped from my radar.

Please could you push the attribution as discussed in this ticket, ensuring that Yu He (#2019) also gets the orcid attribution for 2023?

Thanks!

**Comment by ramGranell** [comment]
Awards were correctly uploaded in our system e.g. https://fairsharing.org/users/8448 or https://fairsharing.org/users/464 however there is an issue when pushing them to ORCID https://github.com/FAIRsharing/FAIRsharing-API/issues/693 . The issue affected for the users that have already pushed an award in ORCID such as the one described in the ticket.

**Comment by ramGranell** [comment]
This is done and 

> Thank you - apologies this had slipped from my radar.
> 
> Please could you push the attribution as discussed in this ticket, ensuring that Yu He (#2019) also gets the orcid attribution for 2023?
> 
> Thanks!

This is done and ORCID attribution is there https://orcid.org/0000-0002-0574-2041. The problem of other attributions is dealt here: https://github.com/FAIRsharing/FAIRsharing-API/issues/693 and #1982
