### ISSUE TITLE
Banner library needs update

### ISSUE THREAD

**Issue by prakhyatox** [FAIRsharing/fairsharing.github.io#2004]
**Describe the bug**
The banner which is created using particles library as the current version is deprecated. 
Due to which it is not behaving as expected in safari browser

**Expected behaviour**
![Screenshot 2023-01-31 at 11 06 45](https://user-images.githubusercontent.com/109139583/215743867-b685312e-d5ab-4792-984f-c9f23b40710f.png)

**Actual behaviour**
In Safari browser
![Screenshot 2023-01-31 at 11 02 39](https://user-images.githubusercontent.com/109139583/215743993-7aba33ec-efb1-4e3b-94c1-09c9d8d119bd.png)

**Comment by knirirr** [comment]
This appears OK in Safari now.
