### ISSUE TITLE
Update to FAQ

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2014]
Please update the text in https://fairsharing.org/educational#faq2-1 as follows (the text shown **in bold** is the text that has been changed):

_TEXT START_

Standards for data and their associated contextual/experimental metadata (essentially, data about the data) are also known as data standards, metadata standards or content standards. FAIRsharing currently focuses **on 4** standard subtypes:
   * Reporting guidelines or checklists outline the minimum information that should be reported alongside a experiment or dataset in order to place it into context. These vary from general guidance to itemised prescriptions of the information that should be provided, both in terms of data and associated metadata.
 * Models/formats or syntax - define the representation of information from a conceptual model or schema, and the transmission format, such as XML, CSV or RDF, which facilitate information exchange.
*  Terminology artefacts encompass controlled vocabularies, taxonomies, thesauri or ontologies and add an interpretive/translational layer (beyond any that might be provided by the syntax), and enable complex hierarchical grouping and querying of the data.
* ~~Metrics are criteria to assesses some aspect of a digital resource, for example - but not limited to - its discoverability. For example, the FAIR Metrics are a set of machine-actionable criteria that allow the assessment of the level of FAIRness of a resource.~~
* Identifier schemata are formal systems for resources and other digital objects that allow their unique and unambiguous identification.
Across the wider research community there are many different ways to categorise and name data/metadata standards, and even to define what constitutes a standard. Nevertheless, in FAIRsharing we will progressively add more types and subtypes as required by the community to ensure wider coverage. For example, one possibility is the addition of Common Data Elements (CDEs). These are particularly used in biomedicine as there are often data elements that are common to multiple data sets across different studies.

_TEXT END_

_(Note that while metrics are currently part of the standards registry, they are not strictly a standard in the true sense, so should not be included here)_

**Comment by knirirr** [comment]
I can't make out the bold text in this - is it simply that metrics have been removed, or should there be something else happening?

Here's the location of the text in the master branch, BTW, in case it is of use:

https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/data/EducationData.json#L31-L36

**Comment by allysonlister** [comment]
Sorry, the two changes are:

1. "one 5" --> "on 4"
2. the removal of the metrics item in the list
