### ISSUE TITLE
Please remove Chris Graf as an Executive Board member

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2022]
Please can you remove Chris Graf as an executive board member on our governance section at https://fairsharing.org/communities#governance

thanks!

**Comment by knirirr** [comment]
As this is a trivial change (removing one line from a data file) which probably won't trigger a Netlify rebuild on its own I have included it in this PR: https://github.com/FAIRsharing/fairsharing.github.io/pull/2023 .
