### ISSUE TITLE
Update to /educational to incorporate new infographics

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2024]
/educational is going to change as the new infographics come into place ahead of the RDA plenary in the second half of March. To this end, please can we add a grouped set of tiles, one per infographic, right at the very top of the page, before everything else that currently exists on that page.

We will have 16 infographics in the first set, and we're aiming to have at least 6 completed before March. However, we would like you to generate the tiles for all 16, and some will just have "Coming Soon..." text rather than a hyperlink. As we are still generating the infographics, please could you use "Coming Soon..." on all of the tiles for now.

Please base this work on the tiles that you've recently added for our tools section of our adopters page, but these infographics tiles will be much simpler.

I have the tile images as PNG files in 4:3 aspect ratio - should I attach them all here, or would you like an alternative delivery message? 

The tile itself will not need a gradient and title overlay as you  have done with the tools, but rather we will provide some text in the white/grey section underneath each tile image. For now, stacked vertically, each tile should have:

1. the image for that infographic
2. a white/grey area underneath that just says "Coming Soon". Later on, this will progressively be replaced by some explanatory text and a link out to a zenodo document. There will also likely be a "Read more..." link that will take the user to a gitbook page with more details about that topic.
Thanks!
Allyson

**Comment by allysonlister** [comment]
The link on OneDrive, accessible to @knirirr and @prakhyatox , is [here](https://unioxfordnexus-my.sharepoint.com/:f:/r/personal/oerc0086_ox_ac_uk/Documents/FAIRsharing%20Infographics?csf=1&web=1&e=3pTEEX) Please let me know if anyone else needs access. Thanks!

**Comment by allysonlister** [comment]
Please can this be completed by Tuesday the 14th? We will have a set of initial infographics for you by then with Zenodo DOIs, and all others will just say "Coming Soon"

**Comment by allysonlister** [comment]
BTW we may update a few of the tiles on onedrive this morning - I'll let you know when that's done, but that shouldn't stop you from getting started ;-)

**Comment by knirirr** [comment]
> Please can this be completed by Tuesday the 14th? 

Possibly, if Prakhyat looks at it (the assistant will, of course, have to be put on hold for the duration).

**Comment by allysonlister** [comment]
Some additional detail after this morning's discussion:

![image](https://user-images.githubusercontent.com/143586/224075533-5c8fd183-39e4-4c88-aeb5-6ebd27f12b40.png)


This screenshot shows the order in which the tiles should be placed. The maximum & ideal tile grid should be 5 tiles wide, though we agree that of course resizing of windows etc will reduce the width accordingly.

All tiles are uploaded to the same OneDrive link.

Here is a mockup of the two different types of tiles + white box. First, a tile for an infographic that we will upload by next week; note the DOI and the doi id and the "copy" icon:
![Example tile and white box and doi](https://user-images.githubusercontent.com/143586/224072663-d11bc808-5eb9-421f-abb0-d46d2e2f6ee9.png)


Here is a mockup of the infographic that is planned but will not be uploaded by next week; note the "Coming soon" and the grey version of the infographic.
![example tile white box and coming soon](https://user-images.githubusercontent.com/143586/224072682-6d430600-aa14-40db-9583-16bb66b28c1a.png)

**Comment by prakhyatox** [comment]
Please provide similar images i.e with blue and grey backgrounds respectively. Currently, all images have blue background.

**Comment by allysonlister** [comment]
They've already been updated in OneDrive, at the time I made the comment :-)

**Comment by prakhyatox** [comment]
Alignment on large screen as per the latest images.

![screencapture-localhost-8080-educational-2023-03-09-16_58_57](https://user-images.githubusercontent.com/109139583/224100650-f500b482-961d-4f89-8516-4396bc39f769.png)

Please let me know your feedback so that I can proceed accordingly.

**Comment by allysonlister** [comment]
Thank you!

**Comment by allysonlister** [comment]
1. as mentioned, it needs to expand to no more than 5, if this is possible - let me know if it's not practical 
2. "Coming Soon" needs to be one of our dark greys rather than black, and perhaps just slightly smaller, thanks!
3. Re-check the order of tiles compared with the screenshot I gave you above, as some of them are out of order.
4. Please re-download all tile content - what you have in the screenshot are old versions, I can tell because the icons within the tiles are smaller than they should be, some are missing their icons, and the text of the tiles had been updated. 

I'm asking Susanna her opinion on adding a title and a brief introduction at the top of the page before the tiles, I'll get back to you on that.

Thanks - looking good so far!

**Comment by allysonlister** [comment]
An additional note about our taglines please:

## on the "Educational" tile on our homepage
![image](https://user-images.githubusercontent.com/143586/224341603-f66a044f-de10-4690-b6d3-50c7957e87bd.png)
Please change the text to: "Infographics and factsheets covering content and functionalities for all stakeholders"

## underneath the "Educational" title in /educational
![image](https://user-images.githubusercontent.com/143586/224341681-d2744bc6-8801-4d84-bed3-19a505bd31d3.png)

Please change the subtitle to "Infographics and factsheets by the FAIRsharing Team and our Community Champions, covering content and functionalities for all stakeholders"


And finally, please remove this "Educational" title within the main text, as it looks odd now that the tiles have been added:

![image](https://user-images.githubusercontent.com/143586/224341906-972a6f3e-946a-4a24-8a7c-8d07224d8cd2.png)


Thank you!

**Comment by allysonlister** [comment]
Good morning! After the following updates, please can we make this public?

1. Please replace the "FAIRsharing content: policies overview" with the grey version and a "Coming Soon"? This one isn't quite ready for next week. Here's the grey version, and also pushed to the onedrive location:
![FAIRsharing content_ policies](https://user-images.githubusercontent.com/143586/225555632-37fff48e-f807-4f79-b6a1-d3eadef71739.png)
2. Here are the DOIs for the 6 infographics we have completed. Please add them as suggested in the comments above, and let me know if you have any questions. Please also note that this table below is just a list of DOIs and not a representation of the order of the tiles - you already have the tiles correctly ordered :-)

which tile?|Visible text (with the DOI icon to the left and the copy icon to the right)|DOI for hyperlink|
--|----|---------|
FAIRsharing in a nutshell|10.5281/zenodo.7737366| https://doi.org/10.5281/zenodo.7737366|
FAIRsharing content: standards overview|10.5281/zenodo.7737795|https://doi.org/10.5281/zenodo.7737795|
FAIRsharing content: databases overview|10.5281/zenodo.7737841|https://doi.org/10.5281/zenodo.7737841|
FAIRsharing for you: researchers|10.5281/zenodo.7733025|https://doi.org/10.5281/zenodo.7733025|
FAIRsharing for you: funders|10.5281/zenodo.7737551|https://doi.org/10.5281/zenodo.7737551|
FAIRsharing for you: journal publishers|10.5281/zenodo.7737417|https://doi.org/10.5281/zenodo.7737417|

**Comment by allysonlister** [comment]
Actually, Susanna has another suggestion; this one is optional, depending on 
1. whether or not it's possible, and
2. whether or not it makes sense.

I realise @prakhyatox is away on a course today, but if he could sort out this ticket as soon as he's back (i.e. by Friday/tomorrow), so that everything is all ready for the conference next week, that would be super, thank you!!

So, here's the extra functionality we'd like to see, if it's possible/makes sense to do.... Are there ways to code web pages such that, provided with appropriate anchor text (e.g. "/educational#nutshell"), the relevant infographic would 'light up' in the grid (e.g. gets a stronger border or similar), even if just for a few seconds? That way we could create individual URLs for each of the tiles and still have the grid.

If that is possible, here are the 6 anchor texts we could use. I've added them to the table that I used in my previous comment, so everything would be in one place.


which tile? | Visible text (with the DOI icon to the left and the copy icon to the right) | DOI for hyperlink| anchor text (would come after "/educational", e.g. "https://fairsharing.org/educational#nutshell")
-- | -- | --|--
FAIRsharing in a nutshell | 10.5281/zenodo.7737366 | https://doi.org/10.5281/zenodo.7737366|#nutshell
FAIRsharing content: standards overview | 10.5281/zenodo.7737795 | https://doi.org/10.5281/zenodo.7737795|#standards
FAIRsharing content: databases overview | 10.5281/zenodo.7737841 | https://doi.org/10.5281/zenodo.7737841|#databases
FAIRsharing for you: researchers | 10.5281/zenodo.7733025 | https://doi.org/10.5281/zenodo.7733025|#researchers
FAIRsharing for you: funders | 10.5281/zenodo.7737551 | https://doi.org/10.5281/zenodo.7737551|#funders
FAIRsharing for you: journal publishers | 10.5281/zenodo.7737417 | https://doi.org/10.5281/zenodo.7737417|#publishers

Please just double check none of these anchors are already in use ;-)

If you think this is a bad idea for any reason, do please let me know!
