### ISSUE TITLE
Additional info field descriptions

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#2026]
The component dealt with in https://github.com/FAIRsharing/fairsharing.github.io/issues/2021 appears only to be returning the description for the overall field (e.g. cross references) and not the descriptions for the parts thereof (e.g. URL, name, portal). This ought to be investigated. It may be that the client is not processing this information correctly, or it could be the fault of the server for not returning it. In the latter case this ticket should be closed in favour of a server ticket.

**Comment by ramGranell** [comment]
Not sure if this is related to this, but when checking the record https://fairsharing.org/3389 there are values for the "COS TOP GUIDELINES:" (you can see when editing it or but it does not appear in the section ADDITIONAL INFORMATION. Console error "vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'description')"
