### ISSUE TITLE
Please create "simple" urls for the types of record within each registry

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2035]
Right now, subtypes of records don't have a "simple" url in the same way each registry does, e.g. although we have https://fairsharing.org/standards for the standards registry, the subtypes are currently reached with:

https://fairsharing.org/search?recordType=reporting_guideline
https://fairsharing.org/search?recordType=model_and_format
https://fairsharing.org/search?recordType=terminology_artefact
https://fairsharing.org/search?recordType=identifier_schema 

As this will help when we reference different parts of each registry within our upcoming infographics, please could redirects be set up for each of the subtypes within the standards, databases and policies?

e.g. for the examples above they could be

https://fairsharing.org/reporting_guidelines
https://fairsharing.org/model_and_formats (or would this be models_and_formats?)
https://fairsharing.org/terminology_artefacts
https://fairsharing.org/identifier_schemata (or identifier_schemas?) 

Thanks!

**Comment by knirirr** [comment]
Are these acceptable?

https://fairsharing.org/standards/model_and_format
https://fairsharing.org/standards/models_and_formats
https://fairsharing.org/standards/metric
https://fairsharing.org/standards/metrics
https://fairsharing.org/standards/terminology_artefact
https://fairsharing.org/standards/terminology_artefacts
https://fairsharing.org/standards/reporting_guideline
https://fairsharing.org/standards/reporting_guidelines
https://fairsharing.org/standards/identifier_schema
https://fairsharing.org/standards/identifier_schemas

...if so then all of them already exist, as do similar links for other registries. They were added here:

https://github.com/FAIRsharing/fairsharing.github.io/issues/1865

**Comment by allysonlister** [comment]
Yikes - what a redundant ticket! Apologies for forgetting, and thank you! Please close :)
