### ISSUE TITLE
Display licence information for 'collection' record

### ISSUE THREAD

**Issue by delphinedauga** [FAIRsharing/fairsharing.github.io#2069]
Collections only show a subset of fields, and this is deliberate. 
However, it would be good if the licences could be displayed, when the field is filled in (for example: https://fairsharing.org/3541)
It could be something like this:
![licence-collection](https://github.com/FAIRsharing/fairsharing.github.io/assets/59688426/8e04f13b-70b8-44ab-8ad4-0a8e0d908263)

Thanks !

**Comment by allysonlister** [comment]
As @delphinedauga said, just to confirm that if the licence is not present, do not show this field at all :-)

Example above is https://fairsharing.org/3541

**Comment by ramGranell** [comment]
If there are more than one licence, they need to be listed with comma separation.

**Comment by allysonlister** [comment]
Apologies (just noticed this), but the licences are being shown even when there is none present, and the request was that the field is not present if it does not have a value. 

Thanks!

**Comment by knirirr** [comment]
Thanks. At which record were you looking?

**Comment by allysonlister** [comment]
Sorry - meant to add that - am looking at https://fairsharing.org/3773
