### ISSUE TITLE
Slow search times - please investigate

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2071]
There are various pages relating to searching that are taking a longer time to load than expected (might be hard to troubleshoot), e.g. https://fairsharing.org/search?fairsharingRegistry=Collection takes about 15 seconds to load, and others e.g. clicking any of the registry buttons...

thanks!

**Comment by knirirr** [comment]
Looking at this in development mode, and seleting all collections, I see:

```
Completed 200 OK in 13503ms (Views: 26.4ms | Searchkick: 63.0ms | ActiveRecord: 7295.5ms | Allocations: 3106106)
```

...which leaves a further 6118.1ms unaccounted for. Perhaps this is the time Elasticsearch takes to respond. 
Currently I have no ideas as to how to improve the speed of these queries but will continue to investigate.

**Comment by allysonlister** [comment]
thanks for looking into this...

**Comment by knirirr** [comment]
No problem. The mystery still remains, though...

https://stackoverflow.com/questions/76380626/slow-activerecord-query-mystery

**Comment by knirirr** [comment]
One cause of the slowdown was consulting the EditLogs to find the last_editor. No other solutions have cropped up at present so I'll move this ticket aside but keep it open as a reminder to investigate again in future if the opportunity arises.

**Comment by knirirr** [comment]
A further speed increase has been obtained by saving relation counts and thus not looking up record relations when a general search is performed.
I'll close this for now and open a new ticket if any other issues arise.
