### ISSUE TITLE
Counts of relationships different in search result cards and in the records themselves

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2089]
When I search 'EGA, the card that appears in the search box says 14 stds and 10 dbs are linked (https://fairsharing.org/search?q=EGA%20):
![Screenshot from 2023-06-27 08-26-00](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/1ac54ab3-4035-4a44-a18f-82a8b03609e0)

When I click on the record (https://fairsharing.org/FAIRsharing.mya1ff) there are actually 13 and 9.
![Screenshot from 2023-06-27 08-25-49](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/d625b032-b517-4d5b-beed-76fbcec206aa)

**Comment by ramGranell** [comment]
When it is is displayed in the record page, only counts one the record e.g. the EGA record (id=1856) is related twice with the standard https://fairsharing.org/256
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/39826987/0cf1e6ff-6ab6-4ed8-bbe7-e77ae00b838a)

In the associated record summary it seems that what it is counted are the total number of relationships (here it is invoking the function to do this https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/components/Records/Search/Output/RecordsCardColumn.vue#L49C34-L49C52 ). This function "associatedRecords()" is implemented here https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/utils/recordsCardUtils.js#L36 and it does not take into account if a record appears twice. You can modify the code to check for each type of record (database, standard and policy) related to the one you are computing the number of relationships that the ID is not repeated. Obviously, it is going to be more time consuming.

**Comment by allysonlister** [comment]
Happy to leave it as it is :)

**Comment by ramGranell** [comment]
Once discovered the reason of these numbers not being exactly the same and considering:1) the problem that will occur if code is changed to have the exact number (increase of time of displayed for each record that is returned in the search) and 2) a record is not very often related twice or more times to same record, we have decided to keep as it is. 

This ticket can be reconsidered in the future if we are able to importantly decrease the time of the returning and displaying the records search that keeps being problematic: #2071

**Comment by ramGranell** [comment]
Now, it seems that it is necessary to have the number exactly computed in the search view.
