### ISSUE TITLE
Change secondary tagline content/layout on homepage banner

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2090]
Please can we update the secondary tagline (shown in light blue here):
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/76218ea1-1b16-4fd6-8029-e011f7b47ec0)

Here is the text, please note the bold and the newlines.

Guides **consumers** to discover, select and use these resources with confidence
Helps **producers** to make their resources more visible, more widely adopted and cited
Powers **third party tools** by providing trustworthy content to promote standards and database

However, while we really would like the bold, we are completely open to the best way to display this text under the primary (in white) tagline, and are happy for you to suggest your favorite couple of options.

Thanks!
Allyson

**Comment by knirirr** [comment]
N.B. the bold text is not showing up and will need to be checked later.

**Comment by allysonlister** [comment]
Adding to this, but please divert to another ticket if that's better...

We would like to update the third sentence to the following please: "10:55
Provides humans and tools with access to trustworthy content to enable data management tasks"

Thanks!

**Comment by allysonlister** [comment]
(text updated in previous comment)
