### ISSUE TITLE
Update to 'Curator Summary Statistics' report on dashboard

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2095]
Please could the summary statistics be updated to include the following rows and columns? It should begin at 09-2022 and add a row for every month up to the current period. here's an example with fake data

Date | username | this month's edits | this month's new records | this month's updated records|
--|--|--|--|--|
09-2022| roygbiv | 10 | 0 | 2|
10-2022| roygbiv | 5 | 1 | 6|
11-2022| roygbiv | 1 | 3 | 3|
12-2023| roygbiv | 30 | 1 | 5|

...and so on up to the current month, and for every champion. In that way a column total, e.g. summing all of "this month's edits" will get a total number of curator edits over all time.

In addition to this, it would be nice to have aggregate statistics to hand, which may require a separate output file? That would look something like:

Date |  this month's edits | this month's new records | this month's updated records|
--|--|--|--|
09-2022| 40 | 10 | 22|
10-2022| 51 | 21 | 16|
11-2022| 12 | 13 | 10|
12-2023| 31 | 11 | 15|

**Comment by ramGranell** [comment]
Ok, how many buttons (files) would you like to have and which columns to have in each one of the file?

From the current columns of the existing file that can be seen in the ticket https://github.com/FAIRsharing/FAIRsharing-API/issues/634 which ones do you want to preserve for each one of the files? These fields are:
id|username|email|scope|number of edits (all time)| number of edits (last 6 months)|number of records created|number of records updated (not counting created records)

**Comment by allysonlister** [comment]
Thanks for the reminder. Updating the first table above accordingly, please only include the following (the rest can be inferred):


Date | username | email | scope | this month's edits | this month's new records | this month's updated records|
--|--|--|--|--|--|--|
09-2022| roygbiv | an@email.com | Biology | 10 | 0 | 2|
10-2022| roygbiv | an@email.com | Biology | 5 | 1 | 6|
11-2022| roygbiv | an@email.com | Biology | 1 | 3 | 3|
12-2023| roygbiv | an@email.com | Biology | 30 | 1 | 5|

does this make sense?
