### ISSUE TITLE
New Champion: Adam Partridge

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2103]
## updating community_champions and checking his account

Adam (https://fairsharing.org/users/9376) is one of our new Champions. I've already updated his db role to Curator, please could you add him to the champions page, with the following info?

Organisation: University of Sheffield (https://fairsharing.org/organisations/4066)
Scope: Brain Stimulation, Open Research
Years Active: 2023
Photo (attached)
![AdamPartridge_Headshot - Adam Partridge](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/e55743d5-5da7-4066-9695-a09dd542f444)

His ORCID is in his FAIRsharing user profile (https://orcid.org/0000-0002-0133-4155) , but please could you check that his account has the proper ORCID tokens, and if not get in touch with him at a.partridge@sheffield.ac.uk referencing the [docs](https://fairsharing.gitbook.io/fairsharing/#accessing-fairsharing-through-3rd-party-accounts) etc?

## pushing to ORCID
Once everything is sorted on our website, please push his ORCID volunteer attribution. Note that there should be two more Champions joining over the next couple of weeks if you want to wait for this particular step (until they have all completed their setup)

Thanks!

**Comment by ramGranell** [comment]
I can add this new Champion now, but do you prefer I wait for the other new ones? About pushing to ORCID I will wait until we have the new ones.

**Comment by allysonlister** [comment]
Please go ahead and add him to our webpage, as he will be referenced in an upcoming zenodo factsheet - thank you! But yes, please don't bother with ORCID until the others have completed their intake form.

Thank you!

**Comment by ramGranell** [comment]
The new user has been added but the ORCID has not been pushed until the rest of users are added.
