### ISSUE TITLE
Link to Assistant from FAIRsharing home page

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2104]
This ticket can either be reviewed by Susanna or Allyson, but there is no rush - aiming for mid-August to September.

How should we show the Assistant on the homepage? e.g. a third section in the deep blue band partway down the page? Please could you see where you think it would be best to go, and make a logo that is suitable and that includes the "beta" appellation. 

Thanks!

**Comment by knirirr** [comment]
I suspect that this one will require mocking up in some way to show to Susanna before implementing any code. 

My preference (FWIW, probably not much) is to use the same section of the page that holds the subject browser. The SB's image could be moved up a bit and an assistant logo put in below. This will avoid disturbing the page layout and will also put the two convenient tools alongside each other. 

Of, that band, which is IMO too tall anyway, could be made shorter and divided into three colums with the assistant taking up one of them.

**Comment by allysonlister** [comment]
Thanks @knirirr - I think it was the latter (three columns) is what Susanna had in mind I believe. A mock up (without coding) of both options would be good, just to confirm with her/us. Thanks!

**Comment by prakhyatox** [comment]
Layout -1 
![Home-page-layout-1](https://github.com/FAIRsharing/fairsharing.github.io/assets/109139583/3a8ffadf-741e-4ebd-9d60-722a43bf8c17)

**Comment by prakhyatox** [comment]
Layout-2

![Home-page-layout-2](https://github.com/FAIRsharing/fairsharing.github.io/assets/109139583/e68b61c4-c828-4df8-ac35-efb305d084a0)

**Comment by prakhyatox** [comment]
Layout - 3

![Home-page-layout-3](https://github.com/FAIRsharing/fairsharing.github.io/assets/109139583/ef6356fc-e5c9-45dc-84b3-52b0e7824ebf)

**Comment by prakhyatox** [comment]
Layout -4 

![Home-page-layout-4](https://github.com/FAIRsharing/fairsharing.github.io/assets/109139583/6ad63a75-8fbc-4f76-a7dd-f3ddbcda0306)

**Comment by prakhyatox** [comment]
Layout - 5 

![Home-page-layout-5](https://github.com/FAIRsharing/fairsharing.github.io/assets/109139583/59853ed5-85eb-4575-8dc1-96109db70639)

**Comment by prakhyatox** [comment]
Layout - 6

![Home-page-layout-6](https://github.com/FAIRsharing/fairsharing.github.io/assets/109139583/31f1573f-8055-4279-abb3-d5a82240742c)

**Comment by prakhyatox** [comment]
Layout - 7

![Home-page-layout-7](https://github.com/FAIRsharing/fairsharing.github.io/assets/109139583/04fea141-cd5a-4cf9-9247-2466fecfb182)

**Comment by prakhyatox** [comment]
Layout - 8

![Home-page-layout-8](https://github.com/FAIRsharing/fairsharing.github.io/assets/109139583/32018141-2522-447c-90f7-e2d27382526c)

**Comment by prakhyatox** [comment]
Layout - 9 - with new card for ```Community Champions```

![Home-page-layout-9](https://github.com/FAIRsharing/fairsharing.github.io/assets/109139583/0d356461-8fc6-4e8d-8559-51148695d7dc)

**Comment by prakhyatox** [comment]
Reference for the design-- https://docs.google.com/presentation/d/1MZ43krInfs_wGrfPmYpcSGYbt2q_qPhcNVLibVCoApU/edit#slide=id.p

**Comment by allysonlister** [comment]
Thanks for doing this - I can see that there is a version in production now, and it looks great. Is there anything else that needs to be done here, or can it be closed? Thanks!
