### ISSUE TITLE
Logo for Champion Programme, and considerations of where to put it

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2105]
During August, please could you mock up some options for the Champions Programme and pass them to Susanna? As part of this, a re-organisation of the footer may be in our best interests (please contact Susanna via gmail or skype). Thanks!

**Comment by knirirr** [comment]
If the footer is to be changed in any way then I think we could benenfit from changing the educational link to educational/faq or something like that, my reasoning being users might look for FAQ and not realise that "educational" is in fact what they need.

**Comment by allysonlister** [comment]
This makes sense. I think Susanna may have some ideas about which items would go in  a new footer, and it might be best to find out further details (I don't have them) of anything else she might want out of an updated footer. Thanks!
