### ISSUE TITLE
Create internal link to our blue search block on the FAIRsharing homepage

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2106]
In order to be able to link directly to our search options in the main page from our infographics, please can we have a URL that would point to our blue block of search items?
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/360104bb-3b3c-4df9-977a-53b7eee31f5b)

As this relates to the publication (imminently) of a few new infographics, we have marked this as high importance and hope that it can be done today or tomorrow.

What do you recommend for the URL? E.g. 
https://fairsharing.org/#searches
Or
https://fairsharing.org/#searchoptions

I don't know how such internal tags are constructed, apologies if their format is not correct.

**Comment by allysonlister** [comment]
Alternatively we could have it be a non-internal link, e.g. https://fairsharing.org/searchoptions that would still resolve to the same location, and that would allow us greater freedom at a later date if we decide to have a page about searches and searching? Not sure, just wondering what our options would be here. thanks!

**Comment by ramGranell** [comment]
After talking to PG, we saw that it is not technically possible that https://fairsharing.org/searchoptions points to a part of an existing page. We can do the first option: https://fairsharing.org/#searches point to this part of the page in the same way than https://fairsharing.org/communities#governance points to page of the communities page

> Alternatively we could have it be a non-internal link, e.g. https://fairsharing.org/searchoptions that would still resolve to the same location, and that would allow us greater freedom at a later date if we decide to have a page about searches and searching? Not sure, just wondering what our options would be here. thanks!

**Comment by allysonlister** [comment]
OK no problem, just a standard internal link then. Do you have any preference for the label for that link? e.g. #searches or #searchoptions? #searches might be simpler...
