### ISSUE TITLE
ROR logo in records

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2109]
In the same way as we have the small orcid logo linked to a user's profile, please could we have a small ROR logo next to the name of any organisation in a record that has a ROR link? When clicking on the logo, it will take you to that organisations' ROR page. Thanks!

**Comment by ramGranell** [comment]
An example of ROR link to organisation can be found here https://catalogue.cioospacific.ca/dataset/ca-cioos_16ae186b-9d99-42cf-b18d-09f9bb0501d7 (in contacts section). I copied a screenshot
![exampleROR](https://github.com/FAIRsharing/fairsharing.github.io/assets/39826987/f9ea3d66-9016-4085-a446-5b698192d172)

The problem that I see is that we have the link to our organisation page over the name and now a new link over the ROR icon is added (for these organisations with existing ROR link). This may be not very intuitive for people that is not familiar with our system and ROR . In the previous example both the link over the name and the ROR icon goes to the ROR website, however in the user maintainer we have both links as well (our user profile and ORCID).

**Comment by allysonlister** [comment]
Thanks! I see your point. However, I'm happy (if you are) to carry on as we have for our usernames; the link on the organisation babe being to our organisation late, and the ror logo going to the ror page. Thanks!

**Comment by ramGranell** [comment]
After checking the response by the API server I saw that the field ror_link is not sent in the graphql response with all the information about the record. In the field organisationLinks.organisations there is an array of organisations in which each organisation contains the following fields:  "name", "id", "homepage", "types", "urlForLogo" and "countries" but not "rorLink". I think that a server ticket is needed to obtain that field.
