### ISSUE TITLE
New Factsheets - updating site pages

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2110]
We have three new factsheets and have updated the versions of all 6 of our previous factsheets. Therefore please can the following changes be made to the site:

#### societies and alliances
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/ead1acce-53a7-4582-aec3-8a9ca53898ef)
- [x] please replace this grey image with the blue image for published factsheets, using the DOI https://doi.org/10.5281/zenodo.8186504 
![FAIrsharing for you_ soc and alliances](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/e3078fb2-5d70-4cc1-b00a-7c2ec0bda72d)

- [x] The "quick" internal link for this should be https://fairsharing.org/educational#societies

#### librarians and trainers
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/8c7903af-eb5a-4832-9973-291c0450a22b)
- [x] please replace this grey image with the blue image for published factsheets, using the DOI https://doi.org/10.5281/zenodo.818660
![FAIRsharing for you_ librarians and trainers](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/c7430a34-27a3-4a2d-960f-a1e8d02db718)

- [x] The "quick" internal link for this should be https://fairsharing.org/educational#trainers

#### developers and curators
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/253ec9af-14d0-4642-954f-83f00c00ec76)
- [x] please replace this grey image with the blue image for published factsheets, using the DOI https://doi.org/10.5281/zenodo.8186594
![FAIRsharing for you_ devs and curators](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/03ca66c7-0805-42f7-b094-7fe9b5d030a4)

- [x] The "quick" internal link for this should be https://fairsharing.org/educational#developers

#### funders
- [x] Please update the DOI to https://doi.org/10.5281/zenodo.8186623
#### researchers
- [x] Please update the DOI to https://doi.org/10.5281/zenodo.8186952
#### journal publishers
- [x] Please update the DOI to https://doi.org/10.5281/zenodo.8186640
#### databases
- [x] Please update the DOI to https://doi.org/10.5281/zenodo.8186961
#### standards
- [x] Please update the DOI to https://doi.org/10.5281/zenodo.8186982

#### societies and alliances
- [x] "read more" in the societies and alliances carousel item should point to https://fairsharing.org/educational#societies
#### librarians and trainers
- [x] "read more" in the librarians and trainers carousel item should point to https://fairsharing.org/educational#trainers
#### developers and curators
- [x] "read more" in the developers and curators carousel item should point to https://fairsharing.org/educational#developers

**Comment by allysonlister** [comment]
Please could this be completed this week if possible?

**Comment by prakhyatox** [comment]
Link : https://doi.org/10.5281/zenodo.818660 for trainers is not found. Is this still needs to be added?

**Comment by allysonlister** [comment]
Apologies - please use https://doi.org/10.5281/zenodo.8186609 - I seem to have given you a typo there

Thank you!

**Comment by allysonlister** [comment]
I'm very sorry but I forgot to give you the updated DOI for the new version of **FAIRsharing in a nutshell**

Please could you also update its DOI to https://doi.org/10.5281/zenodo.8191958 ?

Thank you for your patience!

I've checked all other links and images, and will approve this once these two comments are finished.

**Comment by prakhyatox** [comment]
Links are updated and pushed
