### ISSUE TITLE
New Champion: Yojana Gadiya

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2113]
We have another new Champion! I've updated her role at https://fairsharing.org/users/9417

I'll send her details via Zulip, but please add her to our_champions, and ensure that her orcid token is all set up.

Once this is done, you can add Yojana's, Kelly's and Adam's awards to ORCID. Our final new champion is a bit delayed, so we'll sort them in the Fall.

Thanks!

**Comment by ramGranell** [comment]
New Champion is added in the same PR https://github.com/FAIRsharing/fairsharing.github.io/pull/2112 (again the user does not appear in the development DB).

**Comment by ramGranell** [comment]
Once this branch is added to master in production, I can run the scripts to assign the awards

**Comment by ramGranell** [comment]
All the awards were assign properly to the new champions in their FAIRsharing user account and in their ORCID profile
