### ISSUE TITLE
Updating Sarah Stewart's (Board member) affiliation

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2117]
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/80d08bed-9b55-412d-be8e-f244a7d1049c)

Please could you change Sarah's affiliations to the following: St. George's, University of London; Oxford Internet Institute

Thanks!

**Comment by ramGranell** [comment]
That's performed.
