### ISSUE TITLE
New Champion: Joy Davidson

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2119]
We have another new Champion! I've updated her role at https://fairsharing.org/users/2428

I'll send her details via Zulip, but please add her to our_champions, and ensure that her orcid token is all set up.

If you have the time, please do add Joy's attribution to ORCID.

Once Joy's new card is on the champions page in production, please let me know and I'll tweet about all four of our new Champions :)

Thanks!

**Comment by ramGranell** [comment]
Curator is added to .json file, however her awards have not been pushed

**Comment by knirirr** [comment]
Additionally, I have added the necessary line to the data file on the server used to create awards. But, she has no third-party logins and so can't be given the award until she has logged in with ORCID (I've sent an email).

**Comment by allysonlister** [comment]
Can this be closed?
