### ISSUE TITLE
Change Annie's Champion role to Alumnus

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2133]
Annie Elkjær Ørum-Kristensen (https://fairsharing.org/users/6182) would like to become an alumnus of the programme now. Please could you update the page at https://fairsharing.org/community_champions/our_champions accordingly? Once you've done so, I can modify her role back to a standard "user" - as long as such a role change will retain all of her attribution e.g. within the records she has curated? For example:
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/01446bb2-a2c6-4799-b23f-a46b9a2d41fb)
https://doi.org/10.25504/FAIRsharing.9ntzb2

Thanks!

**Comment by knirirr** [comment]
> as long as such a role change will retain all of her attribution e.g. within the records she has curated

It will not - she will disappear from the section of the page you've shown above the moment her role is downgraded to user.

I don't have any immediate ideas on how I could change the application's behaviour in relation to this. If something springs to mind then a separate server ticket would be required. 

I've just seen that https://github.com/FAIRsharing/fairsharing.github.io/issues/2134 is also affected by this design decision.

**Comment by knirirr** [comment]
I've changed role and alumnus status for this user.
