### ISSUE TITLE
Update Joe's Champion role to Alumnus

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2134]
Joe Miller (https://fairsharing.org/users/6118) would like to become an alumnus of the programme now. Please could you update the page at https://fairsharing.org/community_champions/our_champions accordingly? Once you've done so, I can modify his role back to a standard "user" - as long as such a role change will retain all of his attribution e.g. within the records he has curated as described in #2133 

thanks!

**Comment by knirirr** [comment]
Another issue has cropped up which also affects #2133, but I'll describe it here as that other ticket already has a long thread talking about something else.

The mechanism by which it is decided if a curator is an alumnus or not is if the years in which they are active (see https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/data/communityCurationCohorts.json#L58) does not include the current year. This suggests that all current curators will change state at the end of the year unless we manually put "2024" in all their data records. It also means that nothing needs to be done with the client in order for the two users under discussion to be retired (on the 1st of Jan.). We would need to change them to the "user" role and "alumnus" flag on the server, but that's it.

**Comment by allysonlister** [comment]
Perfect. Yes, they stay active throughout the rest of the year, and should be moved at the start of next year.

Thanks!
Allyson

**Comment by knirirr** [comment]
Role and alumnus state have been updated.
