### ISSUE TITLE
Saved searches

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#2140]
As per ticket  https://github.com/FAIRsharing/FAIRsharing-API/issues/781 here are some changes which will need to be made on the client:

- [x] A button on the advanced search results page to save the results.
- [x] When saving, a dialog which will show a list of available records to which the saved search may be attached.
- [x] REST API calls for creating the saved search and modifying other records with the relevant saved_search_id.
- [x] A list of saved searches on the user's profile page so they can see what they've saved.
- [x] A display of saved searches on organisations' pages.
- [x] A block on a record's page to list any saved searches associated with it (please refer to the Gitbook documentation linked from the server ticket i.e. "conforming resources"). 
- [x] An additional editor tab will probably be needed to deleted saved searches. 

N.B. there are still some comments in the Gitbook documentation which need clarifying before we can proceed.

**Comment by allysonlister** [comment]
This summarises the zulip discussion around how to display these searches within policy records:

A new box SAVED SEARCHES directly after the two COLLECTIONS & RECOMMENDATIONS and RELATED CONTENT boxes. This box, like the two just named, should only appear if there is any content to show. It should also tile nicely with any existing features that might be around it e.g. organisations, or even tile next to either COLLECTIONS & RECOMMENDATIONS and RELATED CONTENT if one of those boxes is missing, as it will be likely that some policies may only have either SAVED SEARCHES or RELATED CONTENT (though they will sometimes have both).

SAVED SEARCHES box will contain a list of the searches, with each row including all the info currently visible on user profile saved searches except for the Edit icon, as edits can only be performed via the user's account page. However, a Delete icon should be available, with the resulting popup looking like the one in the user account page but with an extra message that this action will ONLY delete the saved search from the policy record; it will remain in the user profile unless it is also deleted there. 

Clicking on a saved search will bring up a pop-up preview similar to how the assistant offers a pop-up preview of search results before coming to the end of the questions. This element would have buttons to return to the record or open the the standard saved search result in a new window.

Let me know if this doesn't cover something, thanks!
