### ISSUE TITLE
Additional tag in the 'Early Adopter' group for Champions

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2143]
> The other tag I wanted to add was for any curators who have really gone above and beyond in their champion role with us; this would be an additional tag in the same way as our existing "Early Adopter", and would likely NOT have an associated URL. This is just FYI as it wouldn't directly relate to this ticket.

Ramon says: I think I can do this quite quick as it seems simple as I can do similar as "Early Adopter" The problem that I can have is there are two tags "Early adopter" and the new tag.

_Originally posted by @ramGranell in https://github.com/FAIRsharing/fairsharing.github.io/issues/1903#issuecomment-1733727081_

**Comment by ramGranell** [comment]
Sorry, what is the tag name that needs to be created? At the moment the existing tag is "Early Adopter", but I think that you want to create a similar tag like this with different name for some users. Which colour do you want the chip (pink background with white characters as "Early Adapter" tag?

**Comment by allysonlister** [comment]
Sorry I can't believe I forgot to add that! Let's presume the label will be the same colour as 'Early Adopter' and the label will be 'Curation Expert'. I may need to ask you to change the label if any champions have a better idea, but it will probably be this.

Thanks!

**Comment by ramGranell** [comment]
This is performed and merged, it is need only to add 
"curator_expert" : true
in 
 src/data/communityCurationCohorts.json src/data/communityCurationCohorts.json
