### ISSUE TITLE
Update to Board website: Replace Sowmya Swaminathan with Graham Smith

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2162]
Please could you remove Sowmya Swaminathan from our board list on https://fairsharing.org/communities#governance.

Please could you also add Graham Smith (all of his details are in the governance page under the RDA FAIRsharing WG c-chairs list) in her place (alphabetically of course ;-) ).

Graham will remain as a RDA WG chair, and also be listed on the board.

Thank you!

**Comment by ramGranell** [comment]
As there is a PR pending to be accepted/rejected that modifies this static web (https://github.com/FAIRsharing/fairsharing.github.io/pull/2156) , it would be great to know what happen with it before performing more modifications. It is not easy to keep changes in both branches.
