### ISSUE TITLE
Adding 2 new champions

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2169]
There are two new Champions, please can we add them to the community_champions tiles?

## Richard Acton
FAIRsharing user account: https://fairsharing.org/users/9832
Scope: Bioinformatics
Mastodon: @RichardJActon@fosstodon.org

Please also push attribution to ORCID
Image is below
![RJA - Richard Acton](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/16565c6e-e1be-4c57-8f47-8d5691d3861c)

## David Tomkins
FAIRsharing user account: https://fairsharing.org/users/5491
Scope: Research Data Management
LinkedIn: https://www.linkedin.com/in/david-tomkins-83b92534/
0009-0000-4679-676X, so please push attribution once he's linked his orcid to FAIRsharing account.
Image is below
![OSS Photo - David T](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/d9013031-f786-4d80-a019-3f04bd6f3de3)

Please let me know if you need anything else :) Thanks!

**Comment by allysonlister** [comment]
David now has an ORCID at 0009-0000-4679-676X and I've asked him to login to FAIRsharing with it.

**Comment by allysonlister** [comment]
Lyndon has just completed registration, and is working on getting his ORCID linked (@ramGranell is helping him with that).

Lyndon Zass:

FAIRsharing account: https://fairsharing.org/users/9946
Scope: Research Data Management, Omics
ORCID: https://orcid.org/0000-0001-8862-1706
LinkedIN: https://za.linkedin.com/in/lyndon-zass-10b731145

Image below
![113_photo_ - Lyndon Zass](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/24a3d16a-0df8-435d-9be2-f0c7667c6af0)


Once this is on production we can post our blog post highlighting our new members, so please let me know when it's complete , thanks!

**Comment by ramGranell** [comment]
Ne Champions are in the webiset and ORCID award are pushed for the following Champions:

https://fairsharing.org/users/9832|Bioinformatics|2023
https://fairsharing.org/users/5491|Research Data Management|2023

For the user https://fairsharing.org/users/9946, he needs to be a curator and the ORCID account linked to his FAIRsharing account.
For the user https://fairsharing.org/users/2428, ther are notcredentials. Please ask them to authenticate with ORCID to be pushed.

**Comment by ramGranell** [comment]
Awards are awrded correctly to the new Champions
