### ISSUE TITLE
File uploader

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#2182]
A report has been received that images added to a record are not being uploaded, with the uploader code claiming that they are over the maximum size when that is not the case.

Not all users are experiencing this. For those with difficulties, some report it working as expected in Firefox but not Chrome, and others the opposite.

**Comment by knirirr** [comment]
Action: Change the error message to ask users to contact us if they're having a problem and the image is still of the correct size.

**Comment by allysonlister** [comment]
Is there any way to use a different library here?

**Comment by knirirr** [comment]
I don't know and, if there is, it will involve some time/effort in refactoring various components.
