### ISSUE TITLE
Update Delphine's picture

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2219]
![Delphine-Dauga-portrait](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/6159768d-2561-43d4-9e52-ca646159a539)

Please could you update @delphinedauga's picture on our Team page on the FAIRsharing site?

Thanks!

**Comment by knirirr** [comment]
Done, and also on the Data Readiness site.
If you don't see the new image please clear cache, reload etc. etc.
