### ISSUE TITLE
Order of edit history is not "newest" first

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2226]
The edit history of https://fairsharing.org/3508 has a November 2023 edit at the top, with a Jan 2023 edit after it.

![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/0c8e3106-e477-4c29-8f11-02d287503226)

**Comment by knirirr** [comment]
In the screenshot above the ordering looks correct to me, with the most recent at the top. Have I missed something?

**Comment by allysonlister** [comment]
Ugh, rushing when I was curating - always a bad idea!

Closing, thank you!
