### ISSUE TITLE
Download button not working as expected in collections

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2228]
When I use the download button at https://fairsharing.org/4566?page=1 I get a file (attached) of everything in FAIRsharing and not just the 51 records in this collection.
[fairsharing_download_1706537488.csv](https://github.com/FAIRsharing/fairsharing.github.io/files/14085752/fairsharing_download_1706537488.csv)

**Comment by knirirr** [comment]
I'm not sure how to proceed with this yet but I can confirm that the client isn't sending search terms to the server, but only on Collection pages. It's probably because the search components were shoe-horned into the record page after the original design.

**Comment by knirirr** [comment]
Done and will be deployed on the next merge to dev.
