### ISSUE TITLE
What type of zenodo DOIs are accepted by our Record Edit Interface?

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2230]
I have just had to manually add https://zenodo.org/doi/10.5281/zenodo.4705073, as the "import from doi / zenodo" function did not succeed.

To reproduce, I've given another similar DOI as this one is now in our system

![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/8fc319a8-1d92-4cab-bdec-6ae9f26a7653)

Try to add https://zenodo.org/doi/10.5281/zenodo.10490288 via the Import from doi/zenodo button and you'll get the above error message "DOI not found!"

Not sure if this is intended, e.g. if the type of publication associated with this DOI is not one that we allow, or if it is a bug...

thanks!

**Comment by knirirr** [comment]
There are two things going on here.

Firstly, DOIs must be submitted in the correct format, i.e. prefix/id. Zenodo doesn't recognise the full URL:

![Screenshot from 2024-02-07 11-36-20](https://github.com/FAIRsharing/fairsharing.github.io/assets/3583375/53d3bd89-7876-4776-bfad-40b1d207ca2a)

Secondly, if I enter it correctly as 10.5281/zenodo.4705073 then Zenodo does find a record and return it, but our system still shows the "DOI not found!" banner. This is presumably a code-rot related bug.

**Comment by allysonlister** [comment]
Thanks!

In addition to the bug, is there some way to EITHER 1) add a tooltip providing info about the expected structure of the DOI, or 2) have the UI see the URL and attempt to parse the correct DOI structure from it.

**Comment by knirirr** [comment]
Probably. Telling the user to paste the correct value would be my preferred solution as it will be harder to debug if we have code modifying what they paste and something goes wrong.

**Comment by allysonlister** [comment]
fine with me!
