### ISSUE TITLE
Updated scope and organisation for Adam Partridge

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2234]
Please could you update this Champion's (https://fairsharing.org/users/9376) scope to "Training, Policies and UKRN link", and he's now added an organisation to his user profile, so if https://fairsharing.org/community_champions/our_champions doesn't get automatically updated, please could you update it to match his profile?

Thanks!
Allyson

**Comment by ramGranell** [comment]
Done and merged in dev.
