### ISSUE TITLE
Add counts to summary boxes on front page

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2249]
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/4bd210cd-c7c5-4076-b41d-e0b742f0a35a)
Please could we have a count of institutional policies here too? We only have 9 at the moment, but that number should be growing in the next year and I'd like to make it more obvious that we cater to that group.

Thanks!

**Comment by allysonlister** [comment]
I've changed the subject as I've seen a few more similar updates to perform please... to summarise all:

1. add institutional policy count to the policy box
2. add journal publisher policy count to policy box
3. add count of institutional repositories (https://fairsharing.org/search?userDefinedTags=institutional%2520repository)  to the summary box

thanks!

**Comment by knirirr** [comment]
>     3. add count of institutional repositories (https://fairsharing.org/search?userDefinedTags=institutional%2520repository)  to the summary box

I'm not sure which box this is - would you mind confirming when you have a moment, please?

**Comment by allysonlister** [comment]
At the bottom of here:
![Screenshot_20240223-111238.png](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/127abc8c-1b01-4a85-89a3-5f412f2da17b)

I realise it's not its own registry but it's a useful count for our users. Thanks!

**Comment by knirirr** [comment]
This will appear on the main site next time a merge to master takes place (which will be when https://github.com/FAIRsharing/fairsharing.github.io/pull/2255 is complete).
