### ISSUE TITLE
Adding tags to a record - UI

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#2261]
Some users don't understand that to add tags to a record they must click "add new term(s)". It's not clear why, but I think they're clicking on the coloured bars showing tags, finding nothing happens, and giving up.
A couple of possibilities spring to mind.

1. Change the button to say "edit tags" (which might be clearer for them).
2. Add a tooltip to the component directing them to that button.

**Comment by delphinedauga** [comment]
I think just changing the text button should be enough. Maybe something like "add / edit tags" ? The "add" seems so clear to me.
