### ISSUE TITLE
AdvancedSearch UI fixes

### ISSUE THREAD

**Issue by prakhyatox** [FAIRsharing/fairsharing.github.io#2281]
Below are the list of the UI fixes for Advanced Search

- [x] Change the operator text to something meaningful along with help text like other components
- [x] Change the ordering of the navigation buttons in mobile layout of the advancedSearch DialogBox
- [x] Check the navigation of only advancedSearch URL
- [x] Increasing margin of the bottom navigation
- [x] Top and bottom pagination text and spacing should match.

**Comment by allysonlister** [comment]
Thanks for figuring out how to change the operator text. Taken from an earlier ticket, if possible could the text and tooltips be:

The grey operator section for the Add Group block should have a title of "Select an Operator between Groups" and a tooltip that says "Connect each group of rules with either "AND" or "OR"."
All other grey operator sections should have a title of "Select an Operator for this Group" and a tooltip that says "Connect the rules inside this group with either "AND" or "OR."


Thanks for the fixes, I have no further comments at this stage. :)
