### ISSUE TITLE
URL for advanced search

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2283]
I noticed our FAIRsharing record in FAIRsharing has a data process for the advanced search:

![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/05a2ca06-d56c-4192-8a90-324a462a2ed8)
 https://fairsharing.org/advanced-search  doesn't point to anything at the moment.

Perhaps could  https://fairsharing.org/advanced-search  point to the popup where you get to when you press "Advanced Search"? Thanks!

**Comment by allysonlister** [comment]
Also, I noticed that middle clicking on the Advanced search doesn't do anything - please can we change this behaviour such that it will open the advanced search in a new tab/window? Thanks!

**Comment by knirirr** [comment]
Related to #2289. If the URL in the data process is correct then this ticket can be closed. If the URL is incorrect then this ticket can be moved and labelled as data modification.

**Comment by allysonlister** [comment]
Honestly I don't mind what the url is. I suspect that what's in the FAIRsharing record is a URL that was used years ago on the old site? Happy to use this URL unless there's another you prefer?

**Comment by prakhyatox** [comment]
Solved in ticket https://github.com/FAIRsharing/fairsharing.github.io/issues/2289
