### ISSUE TITLE
Advanced Search quick link

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2289]
Please could we have a quick link through which we can point - in papers docs etc - to our Advanced Search? Perhaps https://fairsharing.org/advanced or something that you would prefer?

thanks!

**Comment by prakhyatox** [comment]
Unfortunately, we cannot have advanced search quick link because it is popup functionality.
The reason for it this that it is a search functionality which will give the result once the search parameters are filled and will direct the user advanced search page with results.

But if you want you could use link ```https://fairsharing.org/advancedsearch``` but won't give you any result. 
But ideally this link should not be directly accessible since it does not give any results and will be confusing to the user.

**Comment by allysonlister** [comment]
There's no way for https://fairsharing.org/advancedsearch to force the popup to open?

If there's really no way for this to work, theoretically, how hard would it be to make the advanced search NOT be a popup, but otherwise work as it does now?

**Comment by prakhyatox** [comment]
Changing advancedSearch from popup to page ideally is not the correct way to work for this functionality.

But what I can do is to force  popup to open on the link ``` https://fairsharing.org/advancedsearch``` or adding hash before text advancedSearch i.e ``` https://fairsharing.org/#advancedsearch```. Will have to check which way is suitable for this.

**Comment by knirirr** [comment]
I managed to deal with a similar request (a link directly to edit logs IIRC) by passing a query parameter to the URL, e.g. https://fairsharing.org/advancedsearch?active=true.

**Comment by prakhyatox** [comment]
Link https://fairsharing.org/advancedsearch?active=true does not open the popup but redirect the user to advancedSearch page without any results.
So, do we need to open the popup to allow user to fill the parameters or taking users to no result advanced search page?
In my opinion former makes sense.

**Comment by knirirr** [comment]
> Link https://fairsharing.org/advancedsearch?active=true does not open the popup ...

That's a URL I plucked out of the air as an example of what could be written. It would need code on the client to detect the specific query params (whatever they might end up being) and open the popup.

**Comment by prakhyatox** [comment]
Link to open advancedsearch popup:  https://fairsharing.org/advancedsearch
