### ISSUE TITLE
Possible bug: assigning a new publication as the citing pub doesn't work

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2306]
https://fairsharing.org/1716

I just 
a) added a new publication
b) set it as the publication to use when citing
c) set to "no" the other publication that was previously the one to use when citing.

However, when I saved and looked at the record, the publication shown is the old one from 2019 instead of the new one from 2022/23:
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/401a9499-6b29-4b0b-9701-6c83b63b60ed)

I tried to look in the edit history but I couldn't understand the json. Has the edit not been saved, or is it just not being shown, as happened previously with the licence toggle?

Thanks!
Allyson

**Comment by knirirr** [comment]
Is this the JSON to which you refer?

```

{
event: "update",
date: "2024-05-01T14:59:17.832Z",
changes: [
{
op: "remove",
was: {
doi: "10.1093/nar/gkac833",
pubmed_id: null,
publication_id: 4270
},
path: "/metadata/citations/0"
},
{
op: "add",
path: "/metadata/citations/0",
value: {
doi: "10.1093/nar/gky868",
pubmed_id: 30247620,
publication_id: 2483
}
}
],
user: "allysonlister (579)"
}

```

If so then:

op - this is the operation that has happened, e.g. add or remove.
path - this is the part of the metadata (i.e. the column in the database of that name) which has been modified, in this case the first item of the citations.
So, one publication has been removed and another added. 
The one which has been added is the one I see on the record page.

**Comment by allysonlister** [comment]
I added this pub:
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/b1e95348-e1ed-446d-8675-a666386488d9)

And then set it as the publication for citation. This did NOT get reflected in the record view, which stil shows the 2019 publication (the 2019 pub was added ages ago, I did not add it during this session)

Honestly I don't know if that's the right part of the json, even with your explanation I don't quite understand it.

I never removed a publication, just changed the toggle on one from "yes" to "no", added a pub, and changed its toggle from "no" to "yes".

**Comment by knirirr** [comment]
> I never removed a publication,

The edit summary is explaining the specific change made to a particular file. That change is that one entry has been removed and another entry added.

On preview.fairsharing.org I just made an edit to the same record, replacing one citation with another. Everything performed as expected. So, I tried in production and all appeared fine there as well. 

Does the record's citation section currently show the correct record?

**Comment by allysonlister** [comment]
As I explained (probably somewhat badly) in the original comment, the record's citation section shows the wrong record. It shows the record that was originally in the citation section before I 1) added a record and 2) marked that record within the edit interface as the one that should go in the citation section.

**Comment by knirirr** [comment]
As I mentioned in the previous comment, I made the edit in production and I think it was successful. Does this look like the correct record in the citation section?

![Screenshot from 2024-05-07 13-46-51](https://github.com/FAIRsharing/fairsharing.github.io/assets/3583375/e95ba29a-feda-4ec8-9e9f-effd7d1f6cb3)

**Comment by allysonlister** [comment]
Yes that's it.

I presumed it would be a weird issue that is likely conflated with my addition of a publication in the same edit.

In any case, there's not much we can do if it's not reproducible...

**Comment by knirirr** [comment]
Unfortunately not. This is another one I'll have to close, but we can re-open if any other occurrences can be reproduced.
