### ISSUE TITLE
Modified "Last Updated" behaviour

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2307]
https://fairsharing.org/989 shows that, even when a record has been reviewed, that record does NOT change its last updated timestamp. This is expected behaviour, but we would like to change how this works. 

The reason is this: when a curator reviews a record e.g. as I have done with https://fairsharing.org/989, it looks like the record hasn't been touched in 2 years.

I've talked this over with @ramGranell and we feel that it would be best to review our current use of "Last edited" and "Record updated" timestamps. 
![image](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/d049db79-ccb5-4b9f-bd10-022cf9151fe5)

I know that both measure slightly different things, but this might be confusing to the user. 

Last edited is whenever a change has been saved in the record, while Record updated might also mean e.g. an update from an automated process right? What are the other ways in which these two values might be changed?

Perhaps it's best to change the "Last edited" to be instead called "Last edited/reviewed" or perhaps "Last edited or reviewed" and then its value can be the timestamp of the most recent edit OR review.

What do you think is the best way to go here?

Thanks!

**Comment by knirirr** [comment]
"Last edited" is generated by looking through the record's edit_events and finding the most recent one which has a user associated with it. This might be an "automated" process (i.e. a Rake task) if that task has assigned a record to the user before saving it. 

"Record updated" is a timestamp which changes whenever the record is modified in any way, unless the record is explicitly saved with an instruction to not change this timestamp. This may be "automated" or a save via the web client where nothing is changed. 

Neither of these have any relation to record_reviews, which are an entirely separate object. 

If you want to make any changes here I can only suggest adding an additional "last reviewed" field giving the date of the record's most recent record_review.

**Comment by allysonlister** [comment]
If that makes the most sense, I'm happy to add a Last reviewed under "how to cite this record". However, note that this may be confusing for some so the fact that there are two different dates will need to be explained in the docs.

**Comment by knirirr** [comment]
Would "Last reviewed: Never" be appropriate if there are no reviews, or would you prefer that "last reviewed" be hidden. I note that there's an option in the dashboard to add a review when approving a record.

Unfortunately confusion is highly likely (and not just for users ;-) as with this new application we've still ended up with a variety of different timestamps which may or may not be updated when records are modified. I'll see what I can come up with for documentation when I deal with this ticket.

**Comment by allysonlister** [comment]
I would suggest hiding it unless it has a value. I usually toggle the review value when I do a proper update of a record and approve it via the dashboard, so they should be getting a reasonable of number of reviews over time. Do you do the same @delphinedauga ?

It would be great for you to create some documentation after this ticket is finished, thanks.

This makes me think about tooltips etc. As part of the ticket where you're adding tooltips, it might be a good idea to add tooltips to both the "how to cite the record" and "how to cite the resource", that could summarise the contents of those boxes. Then, the additions to gitbook would provide the full information.

**Comment by knirirr** [comment]
>  it might be a good idea to add tooltips to both the "how to cite the record" and "how to cite the resource"

This is already in the PR, e.g. https://deploy-preview-2305--fairsharing.netlify.app/1547

**Comment by delphinedauga** [comment]
> I would suggest hiding it unless it has a value. I usually toggle the review value when I do a proper update of a record and approve it via the dashboard, so they should be getting a reasonable of number of reviews over time. Do you do the same @delphinedauga ?

Yes, exactly, I do the same

**Comment by allysonlister** [comment]
Not rushing you here, just checking that this is still undergoing work as you have time? Thanks!

**Comment by knirirr** [comment]
@allysonlister this is dependent on @prakhyatox having time to look at it.

**Comment by allysonlister** [comment]
Ah no problem - Prakhyat is doing other things right now, thanks!

**Comment by knirirr** [comment]
@allysonlister I was confused by the discussion of a different ticket above - it turns out that all I need for this one is for @prakhyatox to review the code.
