### ISSUE TITLE
New Alumnus: Richard Acton

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2331]
Richard is now an alumnus, though at some point he may come back to the programme. Please can you adjust his role and the webpages accordingly? Thanks!

**Comment by allysonlister** [comment]
(I've changed his account role back to 'user')

**Comment by knirirr** [comment]
As far as I can tell the only way I can do this is to remove 2024 from his "years active". Is that what you want?

**Comment by allysonlister** [comment]
Ah yes, I recall that we did this on an annual basis, no worries, I had forgotten. I'll make  a note to not renew him for 2025, but let's leave this alone for now and close the ticket. Thanks!
