### ISSUE TITLE
ORCID attribution for new Oxford Champions

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2337]
Have the Oxford Champions from #2308 had their ORCID attribution pushed? I didn't see anything on their profile, but perhaps they need to approve such an addition first?

Thanks!

**Comment by ramGranell** [comment]
Can you tell me which Champions do not have their 2024 attribution assigned more than the ones in #2339 as I upload it? Thanks

**Comment by allysonlister** [comment]
I don't know which ones haven't had their ORCID pushed yet - there must be a logfile of which of our champions have had the info pushed to ORCID? I can't tell if the info isn't on their orcid because they declined it somehow, or if it hasn't been pushed. I think all champions need to be checked.

**Comment by ramGranell** [comment]
I ran the script when I ran the ticket https://github.com/FAIRsharing/FAIRsharing-API/issues/985 and I assume that this works properly for these people who don't decline it. I'm missing the new ones in #2339 that I will run it when that ticket is over.
