### ISSUE TITLE
Laurence and Tim need their user profiles linked to the Champions page please

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2338]
Laurence: https://fairsharing.org/users/11053
Tim: https://fairsharing.org/users/10608

Please could you add their info to the champions page, and make sure their champions award is visible on their user profiles?

Thanks!

**Comment by ramGranell** [comment]
I think that's already updated in this ticket https://github.com/FAIRsharing/FAIRsharing-API/issues/985 I can see the award in their user pages and their info is in the Champions page, is there any problem with this?

**Comment by allysonlister** [comment]
Sorry I will close - it's odd, but I couldn't see their links to their user accounts when I made the ticket... anyway, done thank you!
