### ISSUE TITLE
New Champions: Clara Boavida and Hugh Shanahan

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2339]
Please could you add Clara to our champions page (details in the intakes spreadsheet) and also push her attribution to ORCID?

https://fairsharing.org/users/11048

![Clara Boavida123px - Clara Boavida](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/ebaf7330-2b6c-4302-b362-c5b27096db8c)

**Comment by allysonlister** [comment]
Please could you also add Hugh to our champions page, and attribution to ORCID, as with Clara?

![PicOfHS - Hugh Shanahan](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/fbd1b0be-abfa-463a-955b-c87591ff7469)

**Comment by ramGranell** [comment]
This is performed but Clara Boavida has declined to have data sent to ORCID

**Comment by allysonlister** [comment]
Here is an updated, higher res pic of Clara:
![foto_ClaraBoavida](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/d3a42834-2bff-4e5e-bdaf-929cf9ba7525)

**Comment by ramGranell** [comment]
Picture updated in dev and check that works fine. Soon will be deployed in production.
