### ISSUE TITLE
New Champion:: Timothee A

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2344]
Please could you add Timothee (https://fairsharing.org/users/11305) as a Champion and push his award to his orcid? All details on intake spreadsheet, and image here:
![timothee_aubourg_profile - Timothee Aubourg](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/d46cf684-e6ca-4e19-9802-f0815c86e23e)

Thanks!

**Comment by ramGranell** [comment]
Champion is added and award is in its user profile and uploaded in its ORCID account.
