### ISSUE TITLE
Add new tile to /educational

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2351]
In position 1 of the tiles, please could you add the following image:
![FAIR Principles in a nutshell](https://github.com/FAIRsharing/fairsharing.github.io/assets/143586/f30ec8e1-b354-4e22-9f85-435b60eaa6c3)
It has the following DOI: https://zenodo.org/doi/10.5281/zenodo.12167785

Please create the tile in the same way as you have done for the rest of them. Thank you!

**Comment by allysonlister** [comment]
Oh, and please could the quicklink be https://fairsharing.org/educational#fair and https://fairsharing.org/educational#FAIR ?

thanks!

**Comment by knirirr** [comment]
@allysonlister should the image provided in your first post replace the existing one?


![Screenshot from 2024-06-21 13-47-56](https://github.com/FAIRsharing/fairsharing.github.io/assets/3583375/d6985f57-6dbc-4a6e-838c-083649ea566d)

Or, is it an additional tile that should go before the one I pictured?

**Comment by allysonlister** [comment]
This is a completely different factsheet, just with a similar title. The existing factsheet that you screenshotted is "FAIRsharing in a nutshell", while the one I'm asking you to add is "FAIR Principles in a nutshell". So yes, this new one is to become the new first tile.

Thanks!
