### ISSUE TITLE
General tab for collections only: Change "none found" to "N/A" to match other fields in the General tab

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2364]
Please could you update the text that is used when there is no "reference url" from "none found" to "N/A" to match the other fields in the general tab.

thanks!

**Comment by ramGranell** [comment]
Now, the behaviour for that field wants to be changed. If the value of reference_url is the same than the value of homepage then it should put "As above", else the behaviour as previously described.
