### ISSUE TITLE
Marking a Champion as an alumnus mid-year

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2371]
This is a low priority ticket.

We have now had two cases (Richard Acton and Kelly Cobey) who have asked to become alumni mid-year. Rather than waiting until January and possibly confusing people, it would be great if we could have a way of marking a Champion as an alumnus partway through the year.

They should show credit for their activity (e.g. Richard and Kelly will still have "2024" attributed to them), but they should be moved to the alumni page and not be renewed in following years.

Is there a sensible, low effort way to implement this? Thanks!

**Comment by ramGranell** [comment]
I think this cannot be changed easily at all as year was the design decision that was taken (they have cohort by years as you can see https://fairsharing.org/community_champions/our_champions, the ORCID push is by year, the field in the Champion .json file is by year,....)

**Comment by allysonlister** [comment]
I understand, just wondering as this is happening more often mid year. 

Can we not change anything else other than perhaps have a boolean attached to the https://fairsharing.org/community_champions/our_champions tiles that is either visible or not visible?

**Comment by ramGranell** [comment]
Yes, it is possible to include a boolean variable in the .json file that indicates if the Champions should be visible or not. Once the code is created, you (or anyone) can edit the .json file and do a PR to check that it works correclty, each time you want to change the status a Champion.

**Comment by allysonlister** [comment]
Thanks - please could you do this, but the boolean should be active/alumni rather than visible/not visible. All for 2024 are active except Kelly and Richard. Just remember that if they are not active but still with 2024 'given to them',  then they should be shown in the alumni page.
