### ISSUE TITLE
New Champion!

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2373]
Beth Knazook is a new Champion with us. As normal, her details are on the intake form, and she has agreed to have her photo be included / be in socials. I've updated her user account permissions, but please could you add her to the website and push to ORCID? Thanks!
![Beth_Knazook_portrait - Beth Knazook](https://github.com/user-attachments/assets/dcda7d67-6809-4cc7-b8c7-5ee7abcc6022)

**Comment by knirirr** [comment]
The email in the intake form didn't match what was in our user database. I assume that I've found the correct user, but it could be useful to add a UID to future tickets.
