### ISSUE TITLE
UsersList not showing list of users before you start typing

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2382]
when I load https://fairsharing.org/profiles/usersList no users appear. They only start appearing when I start typing - I'm sure they used to load all users as soon as I loaded the page? Otherwise, how can I just see all of the users? Sometimes I might need to - my current use case is wanting to see what the most recently-created users are.

This is low priority!!

**Comment by knirirr** [comment]
The behaviour you're sure used to happen hasn't been the case since the middle of June: https://github.com/FAIRsharing/FAIRsharing-API/issues/997
This is because Elasticsearch can't return all users at once as there are too many. 
This could be re-titled as a "List of N most recently-added users" ticket but I'd have to think on how best to do that.

**Comment by allysonlister** [comment]
Thanks for keeping me on the right track, Milo :)

As I think the only use case for pre-loading user names would be to see the most recently added (otherwise I would know some details about the user I am looking for and therefore could start typing), then renaming the ticket and just loading e.g. the first 10 most recent users and allow pagination to get additional results might be helpful. Again, it's low priority so no rush!

**Comment by knirirr** [comment]
If you need the 10 most recent users then I think that would be better off as something separate and not as a side effect of the way users are found by name/email etc.

**Comment by allysonlister** [comment]
It's a rare occurrence, so happy to close this ticket and ask for specific requirements via one-off requests (as I did recently with @ramGranell) as necessary. thanks!
