### ISSUE TITLE
Adding F-UJI to our tools page

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2402]
Line 9 of our spreadsheet of form responses includes The F-UJI team's information on how they use FAIRsharing. Please could this be added to our tools page? Thanks!
[Zulip comment with spreadsheet link](https://zulip.fairsharing.org/#narrow/dm/10,12-dm/near/57660)

**Comment by knirirr** [comment]
@allysonlister is there an organisation within our database which is associated with F-UJI?

**Comment by allysonlister** [comment]
Thanks - please use this: https://fairsharing.org/organisations/427

**Comment by knirirr** [comment]
Thanks, I've added it.
