### ISSUE TITLE
Dashboard error for policy metadata

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2425]
(https://fairsharing.org/5924)
![image](https://github.com/user-attachments/assets/239c5624-b92b-4782-b616-416c733beb2e)
When I try to add a processing note to a policy record that has only had its basic info added (nothing in additional information) I get this message. Might be something to do with the age of the record and the recent checks we added to the policy metadata fields? Thanks!

**Comment by allysonlister** [comment]
FYI I fixed this by adding in the default values manually.

**Comment by knirirr** [comment]
This error would be expected if a record doesn't match the schema, so there's not anything wrong with the site in this case.
