### ISSUE TITLE
Update David Tomkins' role

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#2426]
David Tomkins is no longer affiliated with Bodleian Libraries. Please can we update the organisation, in some manner, to say "Independent Curator" on https://fairsharing.org/community_champions/our_champions? I'm not quite sure if we must link a Champion's organisation to a FAIRsharing org; if so, let me know and we'll chat about the options. 

Thanks!
Allyson

**Comment by knirirr** [comment]
A user's account doesn't have to be linked to an organisation unless they are using our REST API, which requires a user->org link. I could remove the organisation link from his user account.
The label on the curator page could be changed to say anything but it does have an organisation ID to link back to a specific organisation in our database. I wonder if it's worth creating an "unaffiliated" organisation for users such as this.

**Comment by allysonlister** [comment]
Thanks. I hesitate to add an Unaffiliated as I am concerned it may be used in ways that we don't expect. For now, can we just remove the organisation from his card? Thanks!

**Comment by knirirr** [comment]
Are you sure you don't want the link removed in the database, too? It will show him with a Bodleian affiliation on his user page otherwise.

**Comment by allysonlister** [comment]
Ah yes, we should remove it in the database as well, thanks!
