### ISSUE TITLE
Adapting code to API ROR v2

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/fairsharing.github.io#2434]
A new version for ROR is used (v2) and our code needs to be adapted as we are currently using V1. This is related to this ticket
https://github.com/FAIRsharing/FAIRsharing-API/issues/783

**Comment by ramGranell** [comment]
@allysonlister  In ROR v2 they are using the following types for organisations (https://ror.readme.io/v2/docs/fields) :+archive, company, education, facility, funder, government, healthcare, nonprofit, other
I currently do the following mapping between their organisation type and our types (Government body, Charitable foundation, University, Research Institute, Lab, Company, Consortium, Published, Undefined):
ROR_type -> FAIRsharing_type
archive -> Undefined
company -> Company
education -> University
facility -> Undefined
funder -> Undefined
government -> Government body
healthcare -> Undefined
nonprofit -> Charitable foundation
other -> Undefined

Do you think, do we need another matching? You need to remember that this is later possible to be changed by the user creating the organisation.

**Comment by allysonlister** [comment]
I don't think we can safely modify any of our existing mappings to undefined, so I suggest we leave it as it is. Thanks!

**Comment by ramGranell** [comment]
This is successfully performed with this PR https://github.com/FAIRsharing/fairsharing.github.io/pull/2436
