### ISSUE TITLE
Identifier Schema

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [FAIRsharing/fairsharing.github.io#263]
To support automated assessment of persistent (F1 principle) of data objects, please distinguish persistent identifier schema from non-persistent schema. Currently, the registry list mixes both.
https://fairsharing.org/standards/?q=&selected_facets=type_exact:identifier%20schema

**Comment by terazus** [comment]
Hello,
Sorry but this question is related to the old system. This repo is dedicated to rebuilding fairsharing.org.
Please contact our curators at contact@fairsharing.org and they will be happy to help you out.
Closing the issue.

**Comment by kitchenprinzessin3880** [comment]
@terazus noted. thanks.
