### ISSUE TITLE
Periodic check of links

### ISSUE THREAD

**Issue by kitchenprinzessin3880** [FAIRsharing/fairsharing.github.io#264]
The links included in records should be check periodically and at time of harvesting to avoid broken/dead links.
For example, https://fairsharing.org/FAIRsharing.zcveaz
all links of data release, curation and access are broken (dat/time of access: 29-06-2020, 5:20pm CET)

**Comment by terazus** [comment]
Hello,
Sorry but this question is related to the old system. This repo is dedicated to rebuilding fairsharing.org.
Please contact our curators at contact@fairsharing.org and they will be happy to help you out.
Closing the issue.

**Comment by Drosophilic** [comment]
Dear @kitchenprinzessin3880 - just a note on this from the team - we do check links every month but unfortunately many resource maintainers update their link structure and we're constantly playing a game of catch-up. We'll update https://fairsharing.org/FAIRsharing.zcveaz.

Please email contact@fairsharing.org should you have any other examples.

**Comment by kitchenprinzessin3880** [comment]
@Drosophilic  an automated periodic (random) checks might be helpful here..
