### ISSUE TITLE
adding undefined or other definitions to recordsType for preventing bug

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#314]
the relevant component is recordStatus

**Comment by knirirr** [comment]
As requested:

http://localhost:8080/#/search?isApproved=true&isMaintained=true&isRecommended=true&status=in_development


<img width="929" alt="Screenshot 2020-07-30 at 15 51 05" src="https://user-images.githubusercontent.com/3583375/88937793-7f324500-d27c-11ea-8b57-c97adfb48f38.png">

**Comment by hoseinmirian** [comment]
I also applied these filters and I found out the error happens due to the fact that there was no Identifier_Schema node defined in our stack. I also have attached another filter applied shot to test before approving. You can try other combinations
 and open console and let me know if there were any other problems like these. 
![BUG2](https://user-images.githubusercontent.com/25683981/90011357-5efd7f80-dc99-11ea-87f4-168c7d1782c7.png)
