### ISSUE TITLE
Choose Material Design icons as the final icon source of the project

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#326]
All Font Awesome icons must be replaced with Material Design icons.

**Comment by knirirr** [comment]
In addition, some additional icons may need to be found, such as Pubmed, DOI, title and something for organisations other than a factory. See: https://docs.google.com/document/d/1g1sp9vSFEfkLw6pyiESmjdxRRUiN9tjiz8k7Gbv7_VE/edit# (section 3).
