### ISSUE TITLE
Choose an appropriate license

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/fairsharing.github.io#34]
For the source code:
MIT or BSB ?

Content will be under cc-by right?

**Comment by Drosophilic** [comment]
Content will be CC-BY-SA 4.0.
Let's discuss in person the benefits of MIT, BSB or others.

**Comment by Drosophilic** [comment]
We could look at these for comparison:
https://choosealicense.com/licenses/mit/
https://choosealicense.com/licenses/isc/

**Comment by terazus** [comment]
From what I understand, MIT is better for libraries/modules and BSD3 for software/SaS (after discussing with massy).
So i'd go for BSD3.
I couldn't find a license on the backend github so I'm adding Milo to the assignees. We can then discuss this together and use the same license if it make sense.

**Comment by Drosophilic** [comment]
Hi @knirirr, moving the discussion here. 
@terazus and I were oscillating between MIT and BSD-3 and now there is gpl-3.0. It would be good to see how they compare. From initial inspection, MIT and BSD-3 seem pretty similar. Do you know what benefit would gpl-3.0 have over either of those two?

**Comment by knirirr** [comment]
There's a summary table here: https://choosealicense.com/appendix/
One question is, do you want to require that any modifications made by someone else be released? Presumably using MIT/BSD would allow FAIRsharing code to be incorporated in closed-source or commercial products.

**Comment by Drosophilic** [comment]
Thanks @knirirr, although I have to admit I find that table a little confusing. I think we need to have a quick meeting about this.

**Comment by knirirr** [comment]
@Drosophilic a shorter list which covers a spectrum from restrictive to permissive is here:

https://choosealicense.com/licenses/

Whatever is chosen needs to be endorsed by those managing the project. If the main concern is to merely make sure that copyright notices are preserved then one of the licences lower on the page may be selected.

**Comment by Drosophilic** [comment]
How about this one: https://choosealicense.com/licenses/agpl-3.0/

**Comment by Zigur** [comment]
I personally find the GPL licences extremely restrictive. Any code depending on a GPL-licenced piece of code must be GPL as well. If we ever are to reuse some components for other projects such as Datascriptor or ISA-explorer, that are a BSD or MIT-licenced we will not be able to do that. Same issue if you want to release smaller libraries in the future for more general reuse. Probably, this need will not arise, but in any case. GPL is very rarely used in Web project I'd say...I've personally never met it. In any case, a GPL licence would bar me from using the code thus released. .

**Comment by knirirr** [comment]
I remain unconvinced that this is an issue. But, if it is, then the easiest one to use for what I've been writing is MIT, as the framework already uses that.
However, the choice is not mine alone to make.

**Comment by terazus** [comment]
Could we use GPL for the backend, it's not supposed to be modular anyway, and BSD for the front (MIT is for libraries if i get it right) ? 
Is using the API endpoints with a non GPL license considered as a breach?

**Comment by knirirr** [comment]
As far as I can tell we could legitimately do that. Use of the endpoints would presumably be covered by the provisions of the data use rather than the software licence.

**Comment by Drosophilic** [comment]
> Could we use GPL for the backend, it's not supposed to be modular anyway, and BSD for the front (MIT is for libraries if i get it right) ?
> Is using the API endpoints with a non GPL license considered as a breach?

This should be our working model for now, but we may have to revisit this nearer deployment to ensure it fits our revised use case and strategy, so let's not actually add the licenses for now (but postpone the discussion and decision until nearer deployment).

**Comment by knirirr** [comment]
The  GNU AFFERO GENERAL PUBLIC LICENSE, Version 3, was selected.
