### ISSUE TITLE
Bug affecting AnyAllButton and FilterButtons

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#357]
As mentioned here: https://github.com/FAIRsharing/fairsharing.github.io/pull/356

When the "clear all" button is clicked, in addition to clearing all the chips it should also re-set the filter buttons on the left to "all", but it currently does not.

**Comment by hoseinmirian** [comment]
yes but this is related to @terazus  and I to write a external util file to read the router queries and update the UI. in fact its not a bug in filter button

**Comment by knirirr** [comment]
I have edited the title to one which you might perhaps find more to your liking. 
Now, how to fix it? Can you supply me with any more information about this external util file and how it works?

**Comment by knirirr** [comment]
I note that this also manifests when going directly to a URL, e.g.:

http://localhost:8080/#/search?searchAnd=true&isMaintained=false&subjects=ontology%2520and%2520terminology

**Comment by hoseinmirian** [comment]
> Can you supply me with any more information about this external util

ok. please study first how does this works. Records.vue
![image](https://user-images.githubusercontent.com/25683981/88819973-a1628f00-d1b8-11ea-8eef-6a6788de4002.png)
