### ISSUE TITLE
Create color Pallete 

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#375]
![FairSharing_Assets](https://user-images.githubusercontent.com/25683981/89412666-5fd56500-d71f-11ea-9067-33e6728dc6a3.jpg)
requested by @Drosophilic 
the link will be attached to this ticket
![colorPalete](https://user-images.githubusercontent.com/25683981/89779104-97b91f80-db06-11ea-8f0e-7d4e50c4ea56.jpg)

**Comment by hoseinmirian** [comment]
![FairSharing_Assets](https://user-images.githubusercontent.com/25683981/89410928-7ded9600-d71c-11ea-9ee8-b36d2cc68748.jpg)

@Drosophilic assets is ready

**Comment by Drosophilic** [comment]
Is this related to #389 ?
