### ISSUE TITLE
Create a new method to resend confirmation email

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/fairsharing.github.io#401]
Create a method in the rest client and bind it to a component to allow users to resend their confirmation email in case:
1 - the email isn't confirmed for whatever reason
2 - their token isn't valid anymore.

When there's a "not confirmed email" error when trying to reset a password or login, we should display a link to resend the email.

**Comment by knirirr** [comment]
This is the relevant endpoint: https://github.com/FAIRsharing/FAIRsharing-API/issues/126
