### ISSUE TITLE
after clicking on any button, scrollToTop method must be called. 

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#426]

**Comment by ramGranell** [comment]
Hi, I helped @hoseinmirian in a pair coding session when it was the power failure. We managed to repair it partially but not totally. I haven't done anything more and it seems that it is not completely repaired.

**Comment by hoseinmirian** [comment]
@knirirr @terazus this issue is useless anymore due to there is a pr for that now
