### ISSUE TITLE
Change status labels in the search input

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/fairsharing.github.io#434]
Switch from letters to full text:
U: Uncertain
D: Deprecated
R: Ready
I: In Dev.

**Comment by allysonlister** [comment]
Good morning! Just a quick note that @Drosophilic, @delphinedauga and I requested "In development" rather than "In Dev." Is "In development" not possible due to size?

Thanks very much!

**Comment by knirirr** [comment]
There's not really enough space for that.

**Comment by allysonlister** [comment]
That makes sense, thanks :)
