### ISSUE TITLE
Choosing and Applying final color Pallete to the project

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#436]

**Comment by Drosophilic** [comment]
Is this related to #389 and #375?

Could you add more information here please?

**Comment by hoseinmirian** [comment]
The different Colour palettes will be listed here as an image. 

1- Spot Color Palette
![SpotColorPalette](https://user-images.githubusercontent.com/25683981/97709281-f9f44180-1ab1-11eb-86cf-18fbd64a1b02.jpg)

2- Twisted Color Palette
![TwistedColorPalette](https://user-images.githubusercontent.com/25683981/97712852-ebf4ef80-1ab6-11eb-8bcc-7ecba8c2701d.jpg)

3- Matching Color Palette
![MatchingColorPalette](https://user-images.githubusercontent.com/25683981/97712889-f7e0b180-1ab6-11eb-9024-cdad766d3d7d.jpg)

4- Dotting Color Palette
![DottingColorPalette](https://user-images.githubusercontent.com/25683981/97717002-32008200-1abc-11eb-8b7c-d9028b453a8a.jpg)

5- Neighbor Color Palette
![NeighborColorPalette](https://user-images.githubusercontent.com/25683981/97719870-7d685f80-1abf-11eb-8fe2-929cd11b6f60.jpg)

6- Discreet Color Palette
![DiscreetColorPalette](https://user-images.githubusercontent.com/25683981/97729630-cd005880-1aca-11eb-8419-ff677bedec35.jpg)

7- Shades Color Palette
![ShadesColorPalette](https://user-images.githubusercontent.com/25683981/97729704-dee1fb80-1aca-11eb-8ee3-4edaef4f1632.jpg)

8- Purple Color Palette
![PurpleColorPalette](https://user-images.githubusercontent.com/25683981/97883520-ded93a00-1d1c-11eb-9e7e-ee608ebf4193.jpg)

9- Original Legacy palette
![LegacyColorPalette](https://user-images.githubusercontent.com/25683981/97885483-5314dd00-1d1f-11eb-923e-4da13e76aa81.jpg)

**Comment by hoseinmirian** [comment]
The legacy palette was chosen as the final palette.
