### ISSUE TITLE
Move all json files to /src/data

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/fairsharing.github.io#449]

**Comment by ramGranell** [comment]
Some names are not accurate such as recordsTypeData.json that should be recordRegistryData.json. Check the others in case there are inconsistencies.

**Comment by ramGranell** [comment]
I will wait to have the PR #455 to be approved as there are modifications of some .json files and not having conflicts.

**Comment by ramGranell** [comment]
I check all the .json files in the project and here it is the list:
./tests/fixtures/getGrants.json
./tests/fixtures/metaTemplate.json
./tests/fixtures/getKeywords.json
./tests/fixtures/getRecords.json
./tests/fixtures/getRecord.json
./tests/fixtures/recordAssociations.json
./package-lock.json
./package.json
./src/components/GraphClient/queries/getDomains.json
./src/components/GraphClient/queries/getUserDefinedTags.json
./src/components/GraphClient/queries/getFilters.json
./src/components/GraphClient/queries/getSubjects.json
./src/components/GraphClient/queries/getRecordHistory.json
./src/components/GraphClient/queries/getPublications.json
./src/components/GraphClient/queries/getLicences.json
./src/components/GraphClient/queries/getTaxonomies.json
./src/components/GraphClient/queries/introspection.json
./src/components/GraphClient/queries/getRecordsTypes.json
./src/components/GraphClient/queries/getRecords.json
./src/components/GraphClient/queries/getCountries.json
./src/components/GraphClient/queries/getRecord.json
./src/components/GraphClient/queries/getUserMeta.json
./src/components/GraphClient/queries/getRecordsMini.json
./src/components/Records/FiltersLabelMapping.json
./src/components/Records/Record/organisationRelations.json
./src/components/Records/recordsTypeData.json
./src/components/Editor/data/editRecord.json
./src/components/Editor/data/fieldsDescription.json
./src/components/Editor/status.json
./src/data/recordsTypes.json
./src/store/ButtonOptions.json

I suppose that I have just to put in /scr/data the files that are originally in /src/*, not moving files located in ./ or in ./test/fixtures. My question is about the files located in ./src/components/GraphClient/queries/? Do we want to move them as well? @terazus  any thought about this?

**Comment by terazus** [comment]
I forgot about those indeed. No you should leave them there as they are only used by the graphQL client.
