### ISSUE TITLE
Autocomplete scroll with the body

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/fairsharing.github.io#460]
It creates a strange effect where the autocomplete dropdown won't stick to the input field and move when we scroll.

**Comment by terazus** [comment]
Please, if you open a ticket with vuetify, link it here. Or let is know if you need to make contact with the vuetify team or can fix it on your own.

**Comment by terazus** [comment]
Checked quasar implementation, and it's the same thing: https://v0-17.quasar-framework.org/components/autocomplete.html

**Comment by knirirr** [comment]
@hoseinmirian please work on this today and Monday. Opening a ticket as suggested above ASAP would be advisable to give more time to get a response.
