### ISSUE TITLE
Pass the jwt to the searchFairsharingRecords graphQL API call

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/fairsharing.github.io#471]
Once https://github.com/FAIRsharing/FAIRsharing-API/issues/174 has been implemented.

**Comment by terazus** [comment]
@knirirr should be tag this as "wont fix" and close the issue?

**Comment by knirirr** [comment]
As suggested, closing because of https://github.com/FAIRsharing/FAIRsharing-API/issues/174 also being closed.
