### ISSUE TITLE
No maintainer found

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#523]
Change the sentence in the “Maintainer” section : “None found” by  "This record is in need of a maintainer. If you are affiliated with this project, Claim it now!". 

A link (button) could presumably go here.

**Comment by ramGranell** [comment]
Question: Maintainers component use the component NoneFound (https://github.com/FAIRsharing/fairsharing.github.io/blob/dev/src/components/Records/Record/NoneFound.vue)  when there is not any maintainer. This component is used in other several components such as license, organisations. Do we want to modify the NoneFound component to show a different text for specific Components (ie when Maintainer, then text_to_show="This record is in need of a maintainer. If you are affiliated with this project, Claim it now!") or do we want that Maintainers components do not use NoneFound and display the text when there are not maintainers?

**Comment by knirirr** [comment]
My preference is for the second option as this particularly special case only occurs here.

**Comment by ramGranell** [comment]
Ok, let's go for the second option (not invoking NoneFound component and let's have an ad-hoc solution inside the Maintainer component). @terazus do you agree about this?
