### ISSUE TITLE
Edit system: Metadata

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#575]
To deal with everything that's within the metatadata but not support_links or defined in the fairsharing_record_schema.json file, a separate tab will be necessary.

This will have to query the API to get details of what fields are available. 

```
post '/fairsharing_records/metadata_fields', headers: auth_headers(users(:one)),
         params: {registry: 'Standard', type: 'metric'}.to_json
```

**Comment by terazus** [comment]
This includes #576 (same page?).

**Comment by knirirr** [comment]
I'd suggest a separate page for support_links (inc. TeSS), with a separate "record specific info" tab. for the fields which must be got from the API as described in the OP.
