### ISSUE TITLE
Finish Understanding FairSharing Concepts

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#61]
I must have got a good sense of knowledge of what fair sharing is and what it does and its pathway in the feature.

**Comment by Drosophilic** [comment]
@hoseinmirian - you and I should set up a call and I can give you a tour around the current front-end and data therein.
If anyone else would like to join, please register your interest here.

**Comment by hoseinmirian** [comment]
sure Pete will set a separate meet up with you in this regard.
