### ISSUE TITLE
If a request ownership is rejected a banner should appeared in the record indicating it

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/fairsharing.github.io#628]
In function requestOwnerhsip() of Record.vue (https://github.com/FAIRsharing/fairsharing.github.io/blob/dev/src/views/Records/Record.vue#L303), when the value of a request of ownership has value "rejected" (claim === "rejected"), the banner needs to be properly updated. I think there are two options:
1) Have same banner note than when there is an error: "Sorry, your request to claim this record failed. Please contact us.", i.e. if (claim.error || claim === "rejected"){
                _module.error = "Sorry, your request to claim this record failed. Please contact us.";
                _module.canClaim = false;
...
2) Have a different third behaviour

Maybe, the option 1) is the easiest one to code. Then @allysonlister , do you agree with current message that appears in 1)?

**Comment by allysonlister** [comment]
I suggest that @Drosophilic  and @delphinedauga respond to ensure that we agree. (By the way, I only see two options, not three?)

In my opinion, I would prefer option 1, that the banner note is updated to reflect a rejection. Would it be possible to put a time limit on such a banner, e.g. 24 or 48 hours? (If Pete and Delphine agree up to this point, perhaps they also have some preference with regards to the time limit).

As for the text, how about this (again, happy to have Pete/Delphine overrule it): "Thank you for your interest in claiming ownership of this record. However, the FAIRsharing curation team has declined your submission. Please contact us if you have any questions."

Thanks!
