### ISSUE TITLE
mocking alert in an alert box

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#710]
Due to multiple alerts can take up too much space, task should resolve the issue by defining a way to show alerts in a more compact way..

![logger](https://user-images.githubusercontent.com/25683981/109299236-b4137400-782c-11eb-9c07-2e16b7f75e75.jpg)

**Comment by knirirr** [comment]
@hoseinmirian I think that this has been completed, other than #670. Please would you confirm (and close if so)?
