### ISSUE TITLE
Converting all none-human friendly time and data into a human-friendly one

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#758]
![image](https://user-images.githubusercontent.com/25683981/109822705-1acece00-7c2f-11eb-84bc-6e21b076b570.png)

**Comment by knirirr** [comment]
Possibly related to https://github.com/FAIRsharing/fairsharing.github.io/issues/716 ?

**Comment by hoseinmirian** [comment]
> 
> 
> Possibly related to #716 ?

yes I am going to delete this task cz its duplicate
