### ISSUE TITLE
Internal links

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#804]
Some internal links are constructed incorrectly, for example:

https://github.com/FAIRsharing/fairsharing.github.io/blob/master/src/components/Records/Record/Maintainers.vue#L53

This is `<a :href="maintainer.username + '/' + maintainer.id">` and should be `<a :href="'/users/' + maintainer.id">`

But, even then, this link will fail as it will go to /users/1#/ rather than /#/users/1. The question is therefore if it's necessary to put the hash in every internal URL, or if some function exist that will add this depending on the status of history mode.

See also: https://github.com/FAIRsharing/fairsharing.github.io/pull/786#discussion_r595901605

**Comment by knirirr** [comment]
Further comment:

> 
> We will have history mode in production, which means that we will need to removed all href '#'.
> The easiest way i found to deal with this is to use a goTo(link) { this.$router.push({path:link}) } method instead bound through a @click. Because $router already knows which mode we are on.

**Comment by knirirr** [comment]
And also: https://github.com/FAIRsharing/fairsharing.github.io/pull/783#issuecomment-801834724

...relates to navigating to the same page.

**Comment by hoseinmirian** [comment]
I read all the discussions and I believe the all the reported issues will be resolved after merging this branch 
https://github.com/FAIRsharing/fairsharing.github.io/pull/1192

for testing please use netlify link:
https://deploy-preview-1192--fairsharing.netlify.app/

@allysonlister @knirirr if the result was satisfying @knirirr then please close the issue. thanks.
