### ISSUE TITLE
Deprecation links

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#828]
These will need to be displayed on the record pages; they can be created using the record relations editing form.
Here's a ticket which discusses some aspects of their display:

https://github.com/ISA-tools/biosharing/issues/1328#issuecomment-809602603

Both recordAssociations and reverseRecordAssociations will need to be checked for "deprecates" relations.

**Comment by Drosophilic** [comment]
Hi @knirirr, we think the deprecation relationships can be edited via the record relation editing form and displayed in the relationships table.

We have a few other questions and comments and it may be useful to arrange a call on this with @hoseinmirian and @terazus (and @knirirr of course)

**Comment by knirirr** [comment]
> Hi @knirirr, we think the deprecation relationships can be edited via the record relation editing form 

This will definitely have to be the case. 

> and displayed in the relationships table.

This could be done easily now as part of the ongoing collections PR (https://github.com/FAIRsharing/fairsharing.github.io/pull/898). But, it will require that the existing "in collections/recommendations" and "related records" components be re-named to something like "Records linking to this one" and "Records to which this one links" respectively.

**Comment by Drosophilic** [comment]
Hi @knirirr, I understand your dislike of meetings, but I think these things are quicker and easier to discuss on a call with screen sharing etc. We will arrange a time on Zulip.
