### ISSUE TITLE
Watch record

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#832]
The button needs to be connected up to the API once it is modified as here:
https://github.com/FAIRsharing/FAIRsharing-API/issues/261

In addition, something will have to be shown on the record page to indicate to users that they are watching it (e.g. a banner, icon etc.).

**Comment by knirirr** [comment]
Button complete but waiting for curators to comment on whether they want the banner, icon etc.

**Comment by allysonlister** [comment]
We would like an informational banner displayed at the top of every watched record that a user "watches". This banner should always be present for that user until they unwatch the record.

(This is in addition to the Watch/Unwatch toggle in the Action Menu that is already present.) No icons are necessary. Please let us know if you need any other information!

Thanks!
