### ISSUE TITLE
Network graph icons

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#835]
Currently, the network graph shows geometric shapes to indicate the record registry. instead, icons could be shown, but special icons of a smaller size (15px?) would be required. But, for now, the current shapes are sufficient. 

This would probably also require modifications to the API to indicate the required icon. 

our post in hichart forum:
https://www.highcharts.com/forum/viewtopic.php?f=9&t=47527&p=171944#p171944

created github ticket of the issue
https://github.com/highcharts/highcharts/issues/16659

**Comment by hoseinmirian** [comment]
![image](https://user-images.githubusercontent.com/25683981/129897392-1ab86648-2344-43d7-8232-14115db6971b.png)


@knirirr 
Do I have to also update the graph icons for this ticket? if yes is the API ready for that to get the data?tnx

![image](https://user-images.githubusercontent.com/25683981/129897331-fe2d49f5-adb6-4384-9bdc-e7d77d759233.png)

**Comment by knirirr** [comment]
The API currently only returns the shape to be displayed (https://github.com/FAIRsharing/FAIRsharing-API/blob/master/app/graphql/queries/fairsharing_graph.rb#L13-L20). 
Changing it so that it specifies the registry or type of a record will be part of https://github.com/FAIRsharing/FAIRsharing-API/issues/310, and I can't currently give an estimate on that as it's dependent on other work outside my control.

**Comment by hoseinmirian** [comment]
if the data is returning as shapes I can return the equivalent registry for it. For e.g if we have defined rect as database perhaps I can return database icon? sounds good? so I wont depend on your ticket until its ready

**Comment by knirirr** [comment]
> if the data is returning as shapes I can return the equivalent registry for it. For e.g if we have defined rect as database perhaps I can return database icon? sounds good?

That will work for now but you'll have to change it later, as other graph modifications will mean changes to the data structure returned by the API.

**Comment by hoseinmirian** [comment]
its done. need to test the app
![image](https://user-images.githubusercontent.com/25683981/129921826-a0cdd470-8842-461e-b253-d38c9272a542.png)

**Comment by knirirr** [comment]
This is on hold as problems with saving graph images cannot be resolved.

**Comment by knirirr** [comment]
I'll close as we'll be redesigning the graph anyway.
