### ISSUE TITLE
Statistics static page

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/fairsharing.github.io#842]
1. Content divided by type
 - [x] API data
 - [x] Data processing
 - [x] Layout
2. Top 10 disciplines covered by standards (rename: ontology subjects)
 - [x] API data
 - [x] Data processing
 - [x] Layout
3. Top 10 disciplines covered by databases (rename: ontology subjects)
 - [x] API data
 - [x] Data processing
 - [x] Layout
4. Top 10 disciplines covered by policies (rename: ontology subjects)
 - [x] API data
 - [x] Data processing
 - [x] Layout
5. Top 10 countries by content
 - [x] API data
 - [x] Data processing
 - [x] Layout
6. Top 10 standard producing countries
 - [x] API data
 - [x] Data processing
 - [x] Layout
7. Top 10 database producing countries
 - [x] API data
 - [x] Data processing
 - [x] Layout
8. Top 10 policy producing countries
 - [x] API data
 - [x] Data processing
 - [x] Layout
9. Top 10 species covered by standards
 - [x] API data
 - [x] Data processing
 - [x] Layout
10. Top 10 species covered by databases
 - [x] API data
 - [x] Data processing
 - [x] Layout
11. Top 10 species covered by policies
 - [x] API data
 - [x] Data processing
 - [x] Layout
12. Top 10 standards implemented by policies
 - [x] API data
 - [x] Data processing
 - [x] Layout
13. Top 10 databases that implement the most standards
 - [x] API data
 - [x] Data processing
 - [x] Layout
14. Standards that have been implemented by a database
 - [x] API data
 - [x] Data processing
 - [x] Layout
15. Databases that are linked to one or more standard
 - [x] API data
 - [x] Data processing
 - [x] Layout
16. Policies that are linked to one or more standard or database
 - [x] API data
 - [x] Data processing
 - [x] Layout
17. Top 10 standards recommended by journal publishers
 - [x] API data
 - [x] Data processing
 - [x] Layout
18. Top 10 databases recommended by journal publishers
 - [x] API data
 - [x] Data processing
 - [x] Layout
19. Top 10 licenses for standards
 - [x] API data
 - [x] Data processing
 - [x] Layout
20. Top 10 licenses for database content
 - [x] API data
 - [x] Data processing
 - [x] Layout
21. Top 10 funders of standards
 - [x] API data
 - [x] Data processing
 - [x] Layout
22. Top 10 funders of databases
 - [x] API data
 - [x] Data processing
 - [x] Layout
23. Top 10 funders of policies
 - [x] API data
 - [x] Data processing
 - [x] Layout
24. Top 10 organisations (excluding funder) of standards
 - [x] API data
 - [x] Data processing
 - [x] Layout
25. Top 10 organisations (excluding funder) of databases
 - [x] API data
 - [x] Data processing
 - [x] Layout
26. Top 10 organisations (excluding funder) of policies
 - [x] API data
 - [x] Data processing
 - [x] Layout
27. Standard records that have maintainers
 - [x] API data
 - [x] Data processing
 - [x] Layout
28. Database records that have maintainers
 - [x] API data
 - [x] Data processing
 - [x] Layout
29. Policy records that have maintainers
 - [x] API data
 - [x] Data processing
 - [x] Layout
30. Standards that have a publication
 - [x] API data
 - [x] Data processing
 - [x] Layout
31. Databases that have a publication
 - [x] API data
 - [x] Data processing
 - [x] Layout

**Comment by ramGranell** [comment]
In the current implementation, there are some anomalous functionality:
https://deploy-preview-896--fairsharing.netlify.app/#/summary-statistics
The first main page seems to work properly showing the current 16 charts.

When pressing over the standard button, two of the current charts should be showed:
https://github.com/FAIRsharing/fairsharing.github.io/blob/RG-stats-allCharts/src/views/Static/Stats/Statistics.vue#L404 
however only the first one of the charts is showed (https://github.com/FAIRsharing/fairsharing.github.io/blob/RG-stats-allCharts/src/views/Static/Stats/Statistics.vue#L419-L425) but the second one isn't the correct chart.
The code said to show the chart of countries by standard (https://github.com/FAIRsharing/fairsharing.github.io/blob/RG-stats-allCharts/src/views/Static/Stats/Statistics.vue#L439-L445) and it is showing the same previous charts.
The same code to show the chart of countries by standard is used successfully in the all button (https://github.com/FAIRsharing/fairsharing.github.io/blob/RG-stats-allCharts/src/views/Static/Stats/Statistics.vue#L179-L185) and it is displayed properly.

The same issue happens when going from all and using the database button or policy button.

I put a console log in the bar component to show if it is mounted and I show that the second chart is not mounted when pressing the "standard button. I was wondering if it is the "if" that I have before invoking the component (https://github.com/FAIRsharing/fairsharing.github.io/blob/RG-stats-allCharts/src/views/Static/Stats/Statistics.vue#L434) but removing it there is not any change.

**Comment by knirirr** [comment]
Are the issues above now resolved?
If not I'll move this out of "done" so it can be looked at.

**Comment by ramGranell** [comment]
This is sorted out. Feel free to close the ticket
