### ISSUE TITLE
Need of data

### ISSUE THREAD

**Issue by terazus** [FAIRsharing/fairsharing.github.io#87]
We now need some real data (or a sample of real data) in the database so that we can start working on facetting and authentication.

**Comment by Drosophilic** [comment]
It may make sense for this to be a subset of FAIRsharing data, e.g. maybe 1 recommendation and 1 collection?
For example:
https://fairsharing.org/recommendation/ScientificData
https://fairsharing.org/collection/Chemistry

Would that make sense @knirirr, @ramGranell ?

**Comment by knirirr** [comment]
Real data: I could add that in a week once I have @ramGranell 's latest dump. However, I would probably want to restrict access to api.fairsharing.org by IP address during development. @Drosophilic  is there any objection to more than simply two records, if the precaution above is implemented? It is easiest to load the full dump (and may also increase the chances of front-end developers spotting problems with the migration). 

Authentication: Some aspects should be able to be worked on even without data, and I can provide assistance. These files are worth a look:

https://github.com/FAIRsharing/FAIRsharing-API/blob/master/test/integration/user_auth_test.rb 
https://github.com/FAIRsharing/FAIRsharing-API/blob/master/test/test_helper.rb#L46-L52

**Comment by Drosophilic** [comment]
If limited by IP address, no problem.

**Comment by knirirr** [comment]
Thanks. In which case, any static IP addresses supplied to me can be added to the iptables rules on api.fairsharing.org.

**Comment by terazus** [comment]
i'll provide them to you tomorrow on a piece of paper if that's ok for you
