### ISSUE TITLE
How to cite us page

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#892]
@knirirr I checked the legacy website and how to cite us is linked to education page so I am not sure if we still need to keep this ticket.
@allysonlister  this is the redundant ticket for an investigation.. tnx

just link it to the doi 
https://www.nature.com/articles/s41587-019-0080-8

**Comment by allysonlister** [comment]
Thanks @hoseinmirian !

For now, please can you use the following link to the FAIRsharing publication for the "How To Cite Us" part of the footer: https://doi.org/10.1038/s41587-019-0080-8 

I have checked this with Susanna.

Thanks, please let me know if you have any questions :-)
