### ISSUE TITLE
Statistics website not working

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/fairsharing.github.io#938]
When I go to to the statistics page (https://dev--fairsharing.netlify.app/#/summary-statistics) , there is the following error: 
Uncaught (in promise) TypeError: a.latestStats is undefined
    t Statistics.vue:781

**Comment by knirirr** [comment]
This was caused by pre-generated stats data not being present after a migration; the generation code didn't run due to a typo that had mysteriously crept in.

**Comment by ramGranell** [comment]
@knirirr I think there is a new problem with the API when accessing the data for creating the statistics. https://dev--fairsharing.netlify.app/#/summary-statistics

**Comment by knirirr** [comment]
Can be prevented by adding `RecordStats.create(data: RecordStats.generate)` to the end of the migration script.
