### ISSUE TITLE
Center for Open Science Transparent Open Science rankings 

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#942]
These two tickets discuss a field which was omitted from the new specification:

https://github.com/ISA-tools/biosharing/issues/1399
https://github.com/FAIRsharing/FAIRsharing-API/issues/278

This will need to be displayed on the record page for policies (only), if present, in the new. Here's an example of it in the old system:

https://fairsharing.org/FAIRsharing.pf13h9

The text from there can be used (Unless @allysonlister or @Drosophilic want to change it); the data will be found in the record's metadata field (see the linked tickets above).

**Comment by allysonlister** [comment]
I have no need to change the text found there, thank you. 

As a note, this is not something that needs to be added to the edit interface (for the foreseeable future at least).

**Comment by knirirr** [comment]
If I add it to the schema (https://github.com/FAIRsharing/FAIRsharing-API/issues/278) it should appear in the relevant part of the edit interface automatically, unless we do some hacks to suppress it (not recommended).
