### ISSUE TITLE
Displaying deprecation records

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/fairsharing.github.io#948]
See https://docs.google.com/document/d/1K7i_mmV5syR9ZDvUvg4kDROCvUN4kWWIEtMfsoBWz7Y/edit, though we cannot do exactly what is described there.

> Add “Deprecation Information” in red after the DOI / before “Type”. This consists of (Example: https://fairsharing.org/FAIRsharing.7xkx69):
> Deprecation Note would read: “This record was deprecated on April 10, 2018 for the following reason(s): This resource is now obsolete and, together with CSA (https://fairsharing.org/FAIRsharing.2ajtcf), has formed the basis of the M-CSA resource.”
> Please note this incorporates the “deprecation date” field.
> If a “deprecates” relationship exists in the incoming or outgoing direction, please list those relationships. In this example it is an incoming relationship and it would say “This record is replaced by: Mechanism and Catalytic Site Atlas“. If there were an outgoing “deprecates” relationship, another sentence would be added e.g. “This record replaces or incorporates the following deprecated resources: XYZ”

This is dependent on the completion of https://github.com/FAIRsharing/FAIRsharing-API/issues/282 first.

**Comment by allysonlister** [comment]
> If a “deprecates” relationship exists in the incoming or outgoing direction, please list those relationships. In this example it is an incoming relationship and it would say “This record is replaced by: Mechanism and Catalytic Site Atlas“. If there were an outgoing “deprecates” relationship, another sentence would be added e.g. “This record replaces or incorporates the following deprecated resources: XYZ”

I've tried looking at the various sites (preview, dev--fairsharing) and cannot find this part of this ticket, although it has been closed. I note that the deprecates relationship is visible lower down the record, in Related Content -> Related Databases, and that is good. However, it is not listed with the other red text within the general information as requested.

Thanks!
