### ISSUE TITLE
Use UK spelling within the app

### ISSUE THREAD

**Issue by hoseinmirian** [FAIRsharing/fairsharing.github.io#978]
please make a list of all the US spelling and then replace all of them with its UK version. 
@knirirr I think you are best for doing it but please let me know if you are interested to take this ticket. tnx

**Comment by knirirr** [comment]
The ones listed in the Google doc are:

artefact (UK), artifact (US)
organisation (UK), organization (US)
licence (UK), license (US) (N.B. "licensing" is correct, as is "license" as a verb). 

I'll change any more that I see.

**Comment by knirirr** [comment]
I'll close this as I don't think there are any more, but I'll correct them as necessary if any more pop up.
